---
title: "NFL RF PREDICTIONS"
output: word_document
---
```{r}
library(readxl)
WEEKLY_TEAM_PERFORMANCE <- read_excel("C:/Users/ericr/Desktop/NFL STATISTICS/NFL PROJECT DATA/T test data/WEEKLY TEAM PERFORMANCE.xlsx")


WEEKLY_TEAM_PERFORMANCE[4:34] <- lapply(WEEKLY_TEAM_PERFORMANCE[4:34], as.numeric)

WEEKLY_TEAM_PERFORMANCE$TO[is.na(WEEKLY_TEAM_PERFORMANCE$TO)] = 0

WEEKLY_TEAM_PERFORMANCE$DTO[is.na(WEEKLY_TEAM_PERFORMANCE$DTO)] = 0

WEEKLY_TEAM_PERFORMANCE<- na.omit(WEEKLY_TEAM_PERFORMANCE)


IWTP <- read_excel("C:/Users/ericr/Desktop/NFL STATISTICS/NFL PROJECT DATA/T test data/IWTP.xlsx")


IWTP[3:33] <- lapply(IWTP[3:33], as.numeric)
IWTP[35:50] <- lapply(IWTP[35:50], as.numeric)

IWTP$TO[is.na(IWTP$TO)] = 0

IWTP$DTO[is.na(IWTP$DTO)] = 0

IWTP<- na.omit(IWTP)


```


```{r}
# prediction models

Rams_SV1 <- data.frame(TT = 2.7875, CAY= 5.8608,AGG = 6.6085, AYTS = -.8908, COMP = 63.56, Week = 17, TLOS = 2.57, EFF=4.65,EM=32.01,CUSH=5.47, SEP=1.95, TAY=9.79, CTCH=65.50,YACR=5.95,AVG=4.89)

ARI_SV1 <- data.frame(TT =2.22 , CAY=4.52 ,AGG =11.057 , AYTS =-4.01 , COMP =65 , Week = 17, TLOS =2.57 , EFF=3.89,EM=18.6993,CUSH=5.62, SEP=1.9688, TAY=7.475, CTCH=67.86,YACR=4.75,AVG=4.73)


RAMS_SV2 <- data.frame(TT = 2.7875 , CAY= 5.925 ,AGG = 11.575 , AYTS =-1.21  , COMP =61.95 , Week = 17, TLOS =2.94 , EFF=4.66,EM=32.76,CUSH=6.35, SEP=3.28, TAY=8.9, CTCH=65.3,YACR=5.69,AVG=3.91)


ARI_SV2 <- data.frame(TT = 2.683, CAY=4.9 ,AGG =13.825 , AYTS =-2.46 , COMP =64.61 , Week = 17, TLOS =2.94 , EFF=4.02,EM=18.48,CUSH=6.01, SEP=3.25, TAY=8.57, CTCH=67.45,YACR=4.714,AVG=4.53)



SC_Rams_SV1 <- data.frame(TT = 2.7875, CAY= 5.8608,AGG = 6.6085, AYTS = -.8908, COMP = 63.56, Week = 17, TLOS = 2.57, EFF=4.65,EM=32.01,CUSH=5.47, SEP=1.95, TAY=9.79, CTCH=65.50,YACR=5.95,AVG=4.89)

SC_ARI_SV1 <- data.frame(TT =2.22 , CAY=4.52 ,AGG =11.057 , AYTS =-4.01 , COMP =65 , Week = 17, TLOS =2.57 , EFF=3.89,EM=18.6993,CUSH=5.62, SEP=1.9688, TAY=7.475, CTCH=67.86,YACR=4.75,AVG=4.73)


SC_RAMS_SV2 <- data.frame(TT = 2.7875 , CAY= 5.925 ,AGG = 11.575 , AYTS =-1.21  , COMP =61.95 , Week = 17, TLOS =2.94 , EFF=4.66,EM=32.76,CUSH=6.35, SEP=3.28, TAY=8.9, CTCH=65.3,YACR=5.69,AVG=3.91)


SC_ARI_SV2 <- data.frame(TT = 2.683, CAY=4.9 ,AGG =13.825 , AYTS =-2.46 , COMP =64.61 , Week = 17, TLOS =2.94 , EFF=4.02,EM=18.48,CUSH=6.01, SEP=3.25, TAY=8.57, CTCH=67.45,YACR=4.714,AVG=4.53)


#ARI_SV1 <- data.frame(TT = , CAY= ,AGG = , AYTS = , COMP = , Week = 17, TLOS = , EFF=,ED=,CUSH=, SEP=, TAY=, CTCH=,YACR=,AVG=)


```


```{r}


library(caTools)

#TT
sample_WP_TT <- sample.split(WEEKLY_TEAM_PERFORMANCE$TT,SplitRatio = 0.9)
train_WP_TT <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_TT == TRUE)
testWPTT <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_TT == FALSE)


#outcome
sample_WP_outcome <- sample.split(WEEKLY_TEAM_PERFORMANCE$outcome,SplitRatio = 0.9)
train_WP_outcome <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_outcome == TRUE)
testWPoutcome <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_outcome == FALSE)


#OPPS
sample_WP_OPPS <- sample.split(WEEKLY_TEAM_PERFORMANCE$OPPS,SplitRatio = 0.9)
train_WP_OPPS <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_OPPS == TRUE)
testWPOPPS <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_OPPS == FALSE)

#TEAMS
sample_WP_TEAMS <- sample.split(WEEKLY_TEAM_PERFORMANCE$TEAMS,SplitRatio = 0.9)
train_WP_TEAMS <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_TEAMS == TRUE)
testWPTEAMS <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_TEAMS == FALSE)

#FD
sample_WP_FD <- sample.split(WEEKLY_TEAM_PERFORMANCE$FD,SplitRatio = 0.9)
train_WP_FD <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_FD == TRUE)
testWPFD <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_FD == FALSE)

#PY
sample_WP_PY <- sample.split(WEEKLY_TEAM_PERFORMANCE$PY,SplitRatio = 0.9)
train_WP_PY <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_PY == TRUE)
testWPPY <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_PY == FALSE)

#RY
sample_WP_RY <- sample.split(WEEKLY_TEAM_PERFORMANCE$RY,SplitRatio = 0.9)
train_WP_RY <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_RY == TRUE)
testWPRY <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_RY == FALSE)

#TO
sample_WP_TO <- sample.split(WEEKLY_TEAM_PERFORMANCE$TO,SplitRatio = 0.9)
train_WP_TO <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_TO == TRUE)
testWPTO <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_TO == FALSE)

#DFD
sample_WP_DFD <- sample.split(WEEKLY_TEAM_PERFORMANCE$DFD,SplitRatio = 0.9)
train_WP_DFD <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_DFD == TRUE)
testWPDFD <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_DFD == FALSE)

#DPY
sample_WP_DPY <- sample.split(WEEKLY_TEAM_PERFORMANCE$DPY,SplitRatio = 0.9)
train_WP_DPY <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_DPY == TRUE)
testWPDPY <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_DPY == FALSE)

#DRY
sample_WP_DRY <- sample.split(WEEKLY_TEAM_PERFORMANCE$DRY,SplitRatio = 0.9)
train_WP_DRY <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_DRY == TRUE)
testWPDRY <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_DRY == FALSE)

#DTO
sample_WP_DTO <- sample.split(WEEKLY_TEAM_PERFORMANCE$DTO,SplitRatio = 0.9)
train_WP_DTO <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_DTO == TRUE)
testWPDTO <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_DTO == FALSE)

#CAY
sample_WP_CAY <- sample.split(WEEKLY_TEAM_PERFORMANCE$CAY,SplitRatio = 0.9)
train_WP_CAY <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_CAY == TRUE)
testWPCAY <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_CAY == FALSE)

#AGG
sample_WP_AGG <- sample.split(WEEKLY_TEAM_PERFORMANCE$AGG,SplitRatio = 0.9)
train_WP_AGG <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_AGG == TRUE)
testWPAGG <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_AGG == FALSE)

#LCAD
sample_WP_LCAD <- sample.split(WEEKLY_TEAM_PERFORMANCE$LCAD,SplitRatio = 0.9)
train_WP_LCAD <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_LCAD == TRUE)
testWPLCAD <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_LCAD == FALSE)

#AYTS
sample_WP_AYTS <- sample.split(WEEKLY_TEAM_PERFORMANCE$AYTS,SplitRatio = 0.9)
train_WP_AYTS <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_AYTS == TRUE)
testWPAYTS <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_AYTS == FALSE)

#ATT
sample_WP_ATT <- sample.split(WEEKLY_TEAM_PERFORMANCE$ATT,SplitRatio = 0.9)
train_WP_ATT <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_ATT == TRUE)
testWPATT <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_ATT == FALSE)

#TD
sample_WP_TD <- sample.split(WEEKLY_TEAM_PERFORMANCE$TD,SplitRatio = 0.9)
train_WP_TD <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_TD == TRUE)
testWPTD <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_TD == FALSE)

#INT
sample_WP_INT <- sample.split(WEEKLY_TEAM_PERFORMANCE$INT,SplitRatio = 0.9)
train_WP_INT <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_INT == TRUE)
testWPINT <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_INT == FALSE)

#COMP
sample_WP_COMP <- sample.split(WEEKLY_TEAM_PERFORMANCE$COMP,SplitRatio = 0.9)
train_WP_COMP <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_COMP == TRUE)
testWPCOMP <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_COMP == FALSE)

#RUSHATT
sample_WP_RUSHATT <- sample.split(WEEKLY_TEAM_PERFORMANCE$RUSHATT,SplitRatio = 0.9)
train_WP_RUSHATT <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_RUSHATT == TRUE)
testWPRUSHATT <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_RUSHATT == FALSE)

#RUSHTD
sample_WP_RUSHTD <- sample.split(WEEKLY_TEAM_PERFORMANCE$RUSHTD,SplitRatio = 0.9)
train_WP_RUSHTD <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_RUSHTD == TRUE)
testWPRUSHTD <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_RUSHTD == FALSE)

#EFF
sample_WP_EFF <- sample.split(WEEKLY_TEAM_PERFORMANCE$EFF,SplitRatio = 0.9)
train_WP_EFF <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_EFF == TRUE)
testWPEFF <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_EFF == FALSE)

#EM
sample_WP_EM <- sample.split(WEEKLY_TEAM_PERFORMANCE$EM,SplitRatio = 0.9)
train_WP_EM <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_EM == TRUE)
testWPEM <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_EM == FALSE)

#TLOS
sample_WP_TLOS <- sample.split(WEEKLY_TEAM_PERFORMANCE$TLOS,SplitRatio = 0.9)
train_WP_TLOS <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_TLOS == TRUE)
testWPTLOS <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_TLOS == FALSE)

#AVG
sample_WP_AVG <- sample.split(WEEKLY_TEAM_PERFORMANCE$AVG,SplitRatio = 0.9)
train_WP_AVG <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_AVG == TRUE)
testWPAVG <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_AVG == FALSE)

#CUSH
sample_WP_CUSH <- sample.split(WEEKLY_TEAM_PERFORMANCE$CUSH,SplitRatio = 0.9)
train_WP_CUSH <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_CUSH == TRUE)
testWPCUSH <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_CUSH == FALSE)

#SEP
sample_WP_SEP <- sample.split(WEEKLY_TEAM_PERFORMANCE$SEP,SplitRatio = 0.9)
train_WP_SEP <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_SEP == TRUE)
testWPSEP <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_SEP == FALSE)

#TAY
sample_WP_TAY <- sample.split(WEEKLY_TEAM_PERFORMANCE$TAY,SplitRatio = 0.9)
train_WP_TAY <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_TAY == TRUE)
testWPTAY <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_TAY == FALSE)

#CTCH
sample_WP_CTCH <- sample.split(WEEKLY_TEAM_PERFORMANCE$CTCH,SplitRatio = 0.9)
train_WP_CTCH <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_CTCH == TRUE)
testWPCTCH <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_CTCH == FALSE)

#YACR
sample_WP_YACR <- sample.split(WEEKLY_TEAM_PERFORMANCE$YACR,SplitRatio = 0.9)
train_WP_YACR <- subset(WEEKLY_TEAM_PERFORMANCE,sample_WP_YACR == TRUE)
testWPYACR <- subset(WEEKLY_TEAM_PERFORMANCE, sample_WP_YACR == FALSE)







library(randomForest)


#Adjust random forest models 
library(randomForest)
ARFM1<-randomForest(outcome~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_outcome, importance=TRUE)
ARFM2<-randomForest(TEAMS~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_TEAMS, importance=TRUE)
ARFM3<-randomForest(OPPS~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_OPPS, importance=TRUE)
ARFM4<-randomForest(FD~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_FD, importance=TRUE)
ARFM5<-randomForest(PY~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_PY, importance=TRUE)
ARFM6<-randomForest(RY~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_RY, importance=TRUE)
ARFM7<-randomForest(TO~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_TO, importance=TRUE)
ARFM8<-randomForest(DFD~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_DFD, importance=TRUE)
ARFM9<-randomForest(DPY~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_DPY, importance=TRUE)
ARFM10<-randomForest(DRY~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_DRY, importance=TRUE)
ARFM11<-randomForest(DTO~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_DTO, importance=TRUE)
ARFM12<-randomForest(TT~CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_TT, importance=TRUE)
ARFM13<-randomForest(CAY~TT+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_CAY, importance=TRUE)
ARFM14<-randomForest(AGG~TT+CAY+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_AGG, importance=TRUE)
ARFM15<-randomForest(LCAD~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_LCAD, importance=TRUE)
ARFM16<-randomForest(AYTS~TT+CAY+AGG+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_AYTS, importance=TRUE)
ARFM17<-randomForest(ATT~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_ATT, importance=TRUE)
ARFM18<-randomForest(TD~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_TD, importance=TRUE)
ARFM19<-randomForest(INT~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_INT, importance=TRUE)
ARFM20<-randomForest(COMP~TT+CAY+AGG+AYTS+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_COMP, importance=TRUE)
ARFM21<-randomForest(RUSHATT~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_RUSHATT, importance=TRUE)
ARFM22<-randomForest(RUSHTD~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_RUSHTD, importance=TRUE)
ARFM23<-randomForest(EFF~TT+CAY+AGG+AYTS+COMP+Week+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_EFF, importance=TRUE)
ARFM24<-randomForest(EM~TT+CAY+AGG+AYTS+COMP+Week+EFF+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_EM, importance=TRUE)
ARFM25<-randomForest(TLOS~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+AVG+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_TLOS, importance=TRUE)
ARFM26<-randomForest(AVG~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+CUSH+SEP+TAY+CTCH+YACR,data=train_WP_AVG, importance=TRUE)
ARFM27<-randomForest(CUSH~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+SEP+TAY+CTCH+YACR,data=train_WP_CUSH, importance=TRUE)
ARFM28<-randomForest(SEP~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+TAY+CTCH+YACR,data=train_WP_SEP, importance=TRUE)
ARFM29<-randomForest(TAY~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+CTCH+YACR,data=train_WP_TAY, importance=TRUE)
ARFM30<-randomForest(CTCH~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+YACR,data=train_WP_CTCH, importance=TRUE)
ARFM31<-randomForest(YACR~TT+CAY+AGG+AYTS+COMP+Week+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH,data=train_WP_YACR, importance=TRUE)

```


```{r}

#TT
sample_WP_TT <- sample.split(IWTP$TT,SplitRatio = 0.9)
train_WP_TT <- subset(IWTP,sample_WP_TT == TRUE)
testWPTT <- subset(IWTP, sample_WP_TT == FALSE)


#outcome
sample_WP_outcome <- sample.split(IWTP$outcome,SplitRatio = 0.9)
train_WP_outcome <- subset(IWTP,sample_WP_outcome == TRUE)
testWPoutcome <- subset(IWTP, sample_WP_outcome == FALSE)


#OPPS
sample_WP_OPPS <- sample.split(IWTP$OPPS,SplitRatio = 0.9)
train_WP_OPPS <- subset(IWTP,sample_WP_OPPS == TRUE)
testWPOPPS <- subset(IWTP, sample_WP_OPPS == FALSE)

#TEAMS
sample_WP_TEAMS <- sample.split(IWTP$TEAMS,SplitRatio = 0.9)
train_WP_TEAMS <- subset(IWTP,sample_WP_TEAMS == TRUE)
testWPTEAMS <- subset(IWTP, sample_WP_TEAMS == FALSE)

#FD
sample_WP_FD <- sample.split(IWTP$FD,SplitRatio = 0.9)
train_WP_FD <- subset(IWTP,sample_WP_FD == TRUE)
testWPFD <- subset(IWTP, sample_WP_FD == FALSE)

#PY
sample_WP_PY <- sample.split(IWTP$PY,SplitRatio = 0.9)
train_WP_PY <- subset(IWTP,sample_WP_PY == TRUE)
testWPPY <- subset(IWTP, sample_WP_PY == FALSE)

#RY
sample_WP_RY <- sample.split(IWTP$RY,SplitRatio = 0.9)
train_WP_RY <- subset(IWTP,sample_WP_RY == TRUE)
testWPRY <- subset(IWTP, sample_WP_RY == FALSE)

#TO
sample_WP_TO <- sample.split(IWTP$TO,SplitRatio = 0.9)
train_WP_TO <- subset(IWTP,sample_WP_TO == TRUE)
testWPTO <- subset(IWTP, sample_WP_TO == FALSE)

#DFD
sample_WP_DFD <- sample.split(IWTP$DFD,SplitRatio = 0.9)
train_WP_DFD <- subset(IWTP,sample_WP_DFD == TRUE)
testWPDFD <- subset(IWTP, sample_WP_DFD == FALSE)

#DPY
sample_WP_DPY <- sample.split(IWTP$DPY,SplitRatio = 0.9)
train_WP_DPY <- subset(IWTP,sample_WP_DPY == TRUE)
testWPDPY <- subset(IWTP, sample_WP_DPY == FALSE)

#DRY
sample_WP_DRY <- sample.split(IWTP$DRY,SplitRatio = 0.9)
train_WP_DRY <- subset(IWTP,sample_WP_DRY == TRUE)
testWPDRY <- subset(IWTP, sample_WP_DRY == FALSE)

#DTO
sample_WP_DTO <- sample.split(IWTP$DTO,SplitRatio = 0.9)
train_WP_DTO <- subset(IWTP,sample_WP_DTO == TRUE)
testWPDTO <- subset(IWTP, sample_WP_DTO == FALSE)

#CAY
sample_WP_CAY <- sample.split(IWTP$CAY,SplitRatio = 0.9)
train_WP_CAY <- subset(IWTP,sample_WP_CAY == TRUE)
testWPCAY <- subset(IWTP, sample_WP_CAY == FALSE)

#AGG
sample_WP_AGG <- sample.split(IWTP$AGG,SplitRatio = 0.9)
train_WP_AGG <- subset(IWTP,sample_WP_AGG == TRUE)
testWPAGG <- subset(IWTP, sample_WP_AGG == FALSE)

#LCAD
sample_WP_LCAD <- sample.split(IWTP$LCAD,SplitRatio = 0.9)
train_WP_LCAD <- subset(IWTP,sample_WP_LCAD == TRUE)
testWPLCAD <- subset(IWTP, sample_WP_LCAD == FALSE)

#AYTS
sample_WP_AYTS <- sample.split(IWTP$AYTS,SplitRatio = 0.9)
train_WP_AYTS <- subset(IWTP,sample_WP_AYTS == TRUE)
testWPAYTS <- subset(IWTP, sample_WP_AYTS == FALSE)

#ATT
sample_WP_ATT <- sample.split(IWTP$ATT,SplitRatio = 0.9)
train_WP_ATT <- subset(IWTP,sample_WP_ATT == TRUE)
testWPATT <- subset(IWTP, sample_WP_ATT == FALSE)

#TD
sample_WP_TD <- sample.split(IWTP$TD,SplitRatio = 0.9)
train_WP_TD <- subset(IWTP,sample_WP_TD == TRUE)
testWPTD <- subset(IWTP, sample_WP_TD == FALSE)

#INT
sample_WP_INT <- sample.split(IWTP$INT,SplitRatio = 0.9)
train_WP_INT <- subset(IWTP,sample_WP_INT == TRUE)
testWPINT <- subset(IWTP, sample_WP_INT == FALSE)

#COMP
sample_WP_COMP <- sample.split(IWTP$COMP,SplitRatio = 0.9)
train_WP_COMP <- subset(IWTP,sample_WP_COMP == TRUE)
testWPCOMP <- subset(IWTP, sample_WP_COMP == FALSE)

#RUSHATT
sample_WP_RUSHATT <- sample.split(IWTP$RUSHATT,SplitRatio = 0.9)
train_WP_RUSHATT <- subset(IWTP,sample_WP_RUSHATT == TRUE)
testWPRUSHATT <- subset(IWTP, sample_WP_RUSHATT == FALSE)

#RUSHTD
sample_WP_RUSHTD <- sample.split(IWTP$RUSHTD,SplitRatio = 0.9)
train_WP_RUSHTD <- subset(IWTP,sample_WP_RUSHTD == TRUE)
testWPRUSHTD <- subset(IWTP, sample_WP_RUSHTD == FALSE)

#EFF
sample_WP_EFF <- sample.split(IWTP$EFF,SplitRatio = 0.9)
train_WP_EFF <- subset(IWTP,sample_WP_EFF == TRUE)
testWPEFF <- subset(IWTP, sample_WP_EFF == FALSE)

#EM
sample_WP_EM <- sample.split(IWTP$EM,SplitRatio = 0.9)
train_WP_EM <- subset(IWTP,sample_WP_EM == TRUE)
testWPEM <- subset(IWTP, sample_WP_EM == FALSE)

#TLOS
sample_WP_TLOS <- sample.split(IWTP$TLOS,SplitRatio = 0.9)
train_WP_TLOS <- subset(IWTP,sample_WP_TLOS == TRUE)
testWPTLOS <- subset(IWTP, sample_WP_TLOS == FALSE)

#AVG
sample_WP_AVG <- sample.split(IWTP$AVG,SplitRatio = 0.9)
train_WP_AVG <- subset(IWTP,sample_WP_AVG == TRUE)
testWPAVG <- subset(IWTP, sample_WP_AVG == FALSE)

#CUSH
sample_WP_CUSH <- sample.split(IWTP$CUSH,SplitRatio = 0.9)
train_WP_CUSH <- subset(IWTP,sample_WP_CUSH == TRUE)
testWPCUSH <- subset(IWTP, sample_WP_CUSH == FALSE)

#SEP
sample_WP_SEP <- sample.split(IWTP$SEP,SplitRatio = 0.9)
train_WP_SEP <- subset(IWTP,sample_WP_SEP == TRUE)
testWPSEP <- subset(IWTP, sample_WP_SEP == FALSE)

#TAY
sample_WP_TAY <- sample.split(IWTP$TAY,SplitRatio = 0.9)
train_WP_TAY <- subset(IWTP,sample_WP_TAY == TRUE)
testWPTAY <- subset(IWTP, sample_WP_TAY == FALSE)

#CTCH
sample_WP_CTCH <- sample.split(IWTP$CTCH,SplitRatio = 0.9)
train_WP_CTCH <- subset(IWTP,sample_WP_CTCH == TRUE)
testWPCTCH <- subset(IWTP, sample_WP_CTCH == FALSE)

#YACR
sample_WP_YACR <- sample.split(IWTP$YACR,SplitRatio = 0.9)
train_WP_YACR <- subset(IWTP,sample_WP_YACR == TRUE)
testWPYACR <- subset(IWTP, sample_WP_YACR == FALSE)



# new section

#TT_OPP
sample_WP_TT_OPP <- sample.split(IWTP$TT_OPP,SplitRatio = 0.9)
train_WP_TT_OPP <- subset(IWTP,sample_WP_TT_OPP == TRUE)
testWPTT_OPP <- subset(IWTP, sample_WP_TT_OPP == FALSE)


#CAY_OPP
sample_WP_CAY_OPP <- sample.split(IWTP$CAY_OPP,SplitRatio = 0.9)
train_WP_CAY_OPP <- subset(IWTP,sample_WP_CAY_OPP == TRUE)
testWPCAY_OPP <- subset(IWTP, sample_WP_CAY_OPP == FALSE)

#AGG_OPP
sample_WP_AGG_OPP <- sample.split(IWTP$AGG_OPP,SplitRatio = 0.9)
train_WP_AGG_OPP <- subset(IWTP,sample_WP_AGG_OPP == TRUE)
testWPAGG_OPP <- subset(IWTP, sample_WP_AGG_OPP == FALSE)

#LCAD_OPP
sample_WP_LCAD_OPP <- sample.split(IWTP$LCAD_OPP,SplitRatio = 0.9)
train_WP_LCAD_OPP <- subset(IWTP,sample_WP_LCAD_OPP == TRUE)
testWPLCAD_OPP <- subset(IWTP, sample_WP_LCAD_OPP == FALSE)

#AYTS_OPP
sample_WP_AYTS_OPP <- sample.split(IWTP$AYTS_OPP,SplitRatio = 0.9)
train_WP_AYTS_OPP <- subset(IWTP,sample_WP_AYTS_OPP == TRUE)
testWPAYTS_OPP <- subset(IWTP, sample_WP_AYTS_OPP == FALSE)

#ATT_OPP
sample_WP_ATT_OPP <- sample.split(IWTP$ATT_OPP,SplitRatio = 0.9)
train_WP_ATT_OPP <- subset(IWTP,sample_WP_ATT_OPP == TRUE)
testWPATT_OPP <- subset(IWTP, sample_WP_ATT_OPP == FALSE)

#TD_OPP
sample_WP_TD_OPP <- sample.split(IWTP$TD_OPP,SplitRatio = 0.9)
train_WP_TD_OPP <- subset(IWTP,sample_WP_TD_OPP == TRUE)
testWPTD_OPP <- subset(IWTP, sample_WP_TD_OPP == FALSE)

#INT_OPP
sample_WP_INT_OPP <- sample.split(IWTP$INT_OPP,SplitRatio = 0.9)
train_WP_INT_OPP <- subset(IWTP,sample_WP_INT_OPP == TRUE)
testWPINT_OPP <- subset(IWTP, sample_WP_INT_OPP == FALSE)

#COMP_OPP
sample_WP_COMP_OPP <- sample.split(IWTP$COMP_OPP,SplitRatio = 0.9)
train_WP_COMP_OPP <- subset(IWTP,sample_WP_COMP_OPP == TRUE)
testWPCOMP_OPP <- subset(IWTP, sample_WP_COMP_OPP == FALSE)

#RUSHATT_OPP
sample_WP_RUSHATT_OPP <- sample.split(IWTP$RUSHATT_OPP,SplitRatio = 0.9)
train_WP_RUSHATT_OPP <- subset(IWTP,sample_WP_RUSHATT_OPP == TRUE)
testWPRUSHATT_OPP <- subset(IWTP, sample_WP_RUSHATT_OPP == FALSE)

#RUSHTD_OPP
sample_WP_RUSHTD_OPP <- sample.split(IWTP$RUSHTD_OPP,SplitRatio = 0.9)
train_WP_RUSHTD_OPP <- subset(IWTP,sample_WP_RUSHTD_OPP == TRUE)
testWPRUSHTD_OPP <- subset(IWTP, sample_WP_RUSHTD_OPP == FALSE)

#EFF_OPP
sample_WP_EFF_OPP <- sample.split(IWTP$EFF_OPP,SplitRatio = 0.9)
train_WP_EFF_OPP <- subset(IWTP,sample_WP_EFF_OPP == TRUE)
testWPEFF_OPP <- subset(IWTP, sample_WP_EFF_OPP == FALSE)

#EM_OPP
sample_WP_EM_OPP <- sample.split(IWTP$EM_OPP,SplitRatio = 0.9)
train_WP_EM_OPP <- subset(IWTP,sample_WP_EM_OPP == TRUE)
testWPEM_OPP <- subset(IWTP, sample_WP_EM_OPP == FALSE)

#TLOS_OPP
sample_WP_TLOS_OPP <- sample.split(IWTP$TLOS_OPP,SplitRatio = 0.9)
train_WP_TLOS_OPP <- subset(IWTP,sample_WP_TLOS_OPP == TRUE)
testWPTLOS_OPP <- subset(IWTP, sample_WP_TLOS_OPP == FALSE)

#AVG_OPP
sample_WP_AVG_OPP <- sample.split(IWTP$AVG_OPP,SplitRatio = 0.9)
train_WP_AVG_OPP <- subset(IWTP,sample_WP_AVG_OPP == TRUE)
testWPAVG_OPP <- subset(IWTP, sample_WP_AVG_OPP == FALSE)

#CUSH_OPP
sample_WP_CUSH_OPP <- sample.split(IWTP$CUSH_OPP,SplitRatio = 0.9)
train_WP_CUSH_OPP <- subset(IWTP,sample_WP_CUSH_OPP == TRUE)
testWPCUSH_OPP <- subset(IWTP, sample_WP_CUSH_OPP == FALSE)

#SEP_OPP
sample_WP_SEP_OPP <- sample.split(IWTP$SEP_OPP,SplitRatio = 0.9)
train_WP_SEP_OPP <- subset(IWTP,sample_WP_SEP_OPP == TRUE)
testWPSEP_OPP <- subset(IWTP, sample_WP_SEP_OPP == FALSE)

#TAY_OPP
sample_WP_TAY_OPP <- sample.split(IWTP$TAY_OPP,SplitRatio = 0.9)
train_WP_TAY_OPP <- subset(IWTP,sample_WP_TAY_OPP == TRUE)
testWPTAY_OPP <- subset(IWTP, sample_WP_TAY_OPP == FALSE)

#CTCH_OPP
sample_WP_CTCH_OPP <- sample.split(IWTP$CTCH_OPP,SplitRatio = 0.9)
train_WP_CTCH_OPP <- subset(IWTP,sample_WP_CTCH_OPP == TRUE)
testWPCTCH_OPP <- subset(IWTP, sample_WP_CTCH_OPP == FALSE)

#YACR_OPP
sample_WP_YACR_OPP <- sample.split(IWTP$YACR_OPP,SplitRatio = 0.9)
train_WP_YACR_OPP <- subset(IWTP,sample_WP_YACR_OPP == TRUE)
testWPYACR_OPP <- subset(IWTP, sample_WP_YACR_OPP == FALSE)
#IRF

IRF1<-randomForest(outcome~COMP+EM+CTCH+AYTS_OPP+COMP_OPP+SEP_OPP+CTCH_OPP+YACR_OPP,data=train_WP_outcome,importance=TRUE)


IRF2<-randomForest(TEAMS~CAY+AYTS+COMP+EFF+AVG+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AYTS_OPP+EFF_OPP+EM_OPP+TLOS_OPP+TAY_OPP+CTCH_OPP,data=train_WP_TEAMS,importance=TRUE)



IRF3<-randomForest(OPPS~TT+AGG+EM+CAY_OPP+AYTS_OPP+EM_OPP+CTCH_OPP+YACR_OPP,data=train_WP_OPPS,importance=TRUE)



IRF4<-randomForest(FD~AGG+AYTS+COMP+EFF+AVG+SEP+TAY+CTCH+YACR+TT_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+YACR_OPP,data=train_WP_FD,importance=TRUE)


IRF5<-randomForest(PY~COMP+EFF+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+YACR_OPP,data=train_WP_PY,importance=TRUE)


IRF6<-randomForest(RY~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_RY,importance=TRUE)
IRF7<-randomForest(TO~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_TO,importance=TRUE)
IRF8<-randomForest(DFD~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_DFD,importance=TRUE)
IRF9<-randomForest(DPY~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_DPY,importance=TRUE)
IRF10<-randomForest(DRY~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_DRY,importance=TRUE)
IRF11<-randomForest(DTO~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_DTO,importance=TRUE)
IRF12<-randomForest(ATT~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_ATT,importance=TRUE)
IRF13<-randomForest(TD~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_TD,importance=TRUE)
IRF14<-randomForest(INT~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_INT,importance=TRUE)
IRF15<-randomForest(RUSHATT~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_RUSHATT,importance=TRUE)
IRF16<-randomForest(RUSHTD~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_RUSHTD,importance=TRUE)
IRF17<-randomForest(ATT_OPP~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_ATT_OPP,importance=TRUE)
IRF18<-randomForest(TD_OPP~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_TD_OPP,importance=TRUE)
IRF19<-randomForest(INT_OPP~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_INT_OPP,importance=TRUE)
IRF20<-randomForest(RUSHATT_OPP~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_RUSHATT_OPP,importance=TRUE)
IRF21<-randomForest(RUSHTD_OPP~TT+CAY+AGG+AYTS+COMP+EFF+EM+TLOS+AVG+CUSH+SEP+TAY+CTCH+YACR+TT_OPP+CAY_OPP+AGG_OPP+AYTS_OPP+COMP_OPP+EFF_OPP+EM_OPP+TLOS_OPP+AVG_OPP+CUSH_OPP+SEP_OPP+TAY_OPP+CTCH_OPP+YACR_OPP,data=train_WP_RUSHTD_OPP,importance=TRUE)

```

```{r}
#Dolphins VS LAC
LAC_SV1 <- data.frame(TT=2.585,
CAY=6.02,
AGG=14.48,
AYTS=-0.81,
ATT=35.8,
TD=1.7,
INT=1.3,
COMP=67.61,
EFF=4.493,
EM=17.7375,
TLOS=2.852,
AVG=3.965,
CUSH=5.258333,
SEP=2.936667,
TAY=10.85667,
CTCH=71.2115,
YACR=3.993333,
Week=4 )

#Dallas vs. NYG week 7
DAL_SV1 <- data.frame(TT=2.812143,
CAY=7.371429,
AGG=17.65,
AYTS=0.2428571,
ATT=37.92857,
TD=1.714286,
INT=0.7142857,
COMP=66.25,
EFF=4.013571,
EM=22.90107,
TLOS=2.763571,
AVG=4.117857,
CUSH=5.657024,
SEP=2.57631,
TAY=10.92202,
CTCH=67.72182,
YACR=4.314286,
Week=7
)
#Houston vs. Pats
HOU_SV1 <- data.frame(TT=2.805,
CAY=6.45,
AGG=15.51,
AYTS=0.4,
ATT=34,
TD=1.7,
INT=0.8,
COMP=66.53,
EFF=4.195,
EM=20.158,
TLOS=2.685,
AVG=3.78,
CUSH=5.445833,
SEP=3.015,
TAY=10.6225,
CTCH=65.96517,
YACR=4.638333,
Week= 13
)

#Pats Vs. Houston week 13
NE_SV1 <- data.frame(TT=2.761667,
CAY=5.658333,
AGG=16.4,
AYTS=-1.566667,
ATT=37.75,
TD=1.416667,
INT=0.5,
COMP=60.2,
EFF=4.098333,
EM=41.28583,
TLOS=2.7075,
AVG=4.041667,
CUSH=5.234722,
SEP=2.603472,
TAY=10.03611,
CTCH=54.95278,
YACR=3.210417,
Week=13
)

#MIA vs. Chargers week 4 
MIA_SV1 <- data.frame(TT=2.616667,
CAY=6.733333,
AGG=23.42222,
AYTS=-0.3444444,
ATT=33.77778,
TD=2,
INT=1.111111,
COMP=61.9,
EFF=6.448889,
EM=28.13333,
TLOS=2.768889,
AVG=2.833333,
CUSH=5.628704,
SEP=2.515741,
TAY=10.81389,
CTCH=60.82852,
YACR=3.99537,
Week=4
)

# Saints vs. TB week 5 
NO_SV1 <- data.frame(TT=2.682857,
CAY=4.85,
AGG=12.62143,
AYTS=-2.55,
ATT=35.21429,
TD=2.285714,
INT=0.3571429,
COMP=70.34286,
EFF=4.182857,
EM=24.24214,
TLOS=2.723571,
AVG=4.378571,
CUSH=5.569048,
SEP=2.819048,
TAY=9.671429,
CTCH=68.09631,
YACR=4.619048,
Week= 5 
)
#OAK VS HOUSTON week 7
OAK_SV1 <- data.frame(TT=2.896923,
CAY=5.092308,
AGG=13.30769,
AYTS=-2.115385,
ATT=31.84615,
TD=1.307692,
INT=0.4615385,
COMP=70.69231,
EFF=3.731538,
EM=20.81538,
TLOS=2.713077,
AVG=4.476923,
CUSH=5.887179,
SEP=2.970513,
TAY=8.946154,
CTCH=71.2391,
YACR=5.776923,
Week=7 
)
#NYG vs. DALLAS week 7 
NYG_SV1 <- data.frame(TT=2.82,
CAY=5.853846,
AGG=21.66923,
AYTS=-1.069231,
ATT=37.38462,
TD=1.692308,
INT=1.230769,
COMP=61.66154,
EFF=14.86577,
EM=18.05923,
TLOS=2.857692,
AVG=4.238462,
CUSH=5.373718,
SEP=2.502564,
TAY=9.224359,
CTCH=61.88724,
YACR=4.267308,
Week=7 
)
#SEA vs. SF week 17 
SEA_SV1 <- data.frame(TT=2.843333,
CAY=6.791667,
AGG=17.65833,
AYTS=0.375,
ATT=33,
TD=1.833333,
INT=0.3333333,
COMP=62.33333,
EFF=3.970417,
EM=23.8825,
TLOS=2.862083,
AVG=4.845833,
CUSH=5.525,
SEP=3.0375,
TAY=10.92778,
CTCH=70.80903,
YACR=4.5375,
Week=17
)

#TB vs. Saints week 5 
TB_SV1 <- data.frame(TT=2.780769,
CAY=8.461538,
AGG=15.15385,
AYTS=1.192308,
ATT=39.07692,
TD=1.846154,
INT=1.923077,
COMP=62.51538,
EFF=4.099231,
EM=27.30077,
TLOS=2.670385,
AVG=4.134615,
CUSH=5.671154,
SEP=2.498077,
TAY=13.33397,
CTCH=62.88096,
YACR=4.782051,
Week=5
)

#SF vs seattle week 17
SF_SV1 <- data.frame(TT=2.660667,
CAY=5.426667,
AGG=16.81333,
AYTS=-2.353333,
ATT=31.26667,
TD=1.733333,
INT=0.8,
COMP=68.32667,
EFF=5.163778,
EM=40.854,
TLOS=2.939556,
AVG=4.568889,
CUSH=4.936111,
SEP=3.072222,
TAY=7.687778,
CTCH=74.04972,
YACR=6.507778,
Week=17
)

```

```{r}
#Team Matchups 

# LAC for LAC vs. MIA 

LAC_MIA_MU <- data.frame(TT=2.585,
CAY=6.02,
AGG=14.48,
AYTS=-0.81,
ATT=35.8,
TD=1.7,
INT=1.3,
COMP=67.61,
EFF=4.493,
EM=17.7375,
TLOS=2.852,
AVG=3.965,
CUSH=5.258333,
SEP=2.936667,
TAY=10.85667,
CTCH=71.2115,
YACR=3.993333,
TT_OPP=2.616667,
CAY_OPP=6.733333,
AGG_OPP=23.42222,
AYTS_OPP=-0.3444444,
ATT_OPP=33.77778,
TD_OPP=2,
INT_OPP=1.111111,
COMP_OPP=61.9,
EFF_OPP=6.448889,
EM_OPP=28.13333,
TLOS_OPP=2.768889,
AVG_OPP=2.833333,
CUSH_OPP=5.628704,
SEP_OPP=2.515741,
TAY_OPP=10.81389,
CTCH_OPP=60.82852,
YACR_OPP=3.99537
)


# MIA for MIA vS. LAC

MIA_LAC_MU <- data.frame(TT=2.616667,
CAY=6.733333,
AGG=23.42222,
AYTS=-0.3444444,
ATT=33.77778,
TD=2,
INT=1.111111,
COMP=61.9,
EFF=6.448889,
EM=28.13333,
TLOS=2.768889,
AVG=2.833333,
CUSH=5.628704,
SEP=2.515741,
TAY=10.81389,
CTCH=60.82852,
YACR=3.99537,
TT_OPP=2.585,
CAY_OPP=6.02,
AGG_OPP=14.48,
AYTS_OPP=-0.81,
ATT_OPP=35.8,
TD_OPP=1.7,
INT_OPP=1.3,
COMP_OPP=67.61,
EFF_OPP=4.493,
EM_OPP=17.7375,
TLOS_OPP=2.852,
AVG_OPP=3.965,
CUSH_OPP=5.258333,
SEP_OPP=2.936667,
TAY_OPP=10.85667,
CTCH_OPP=71.2115,
YACR_OPP=3.993333
)


# DALLAS FOR DAL VS. NYG
DAL_NYG_MU <- data.frame(TT=2.812143,
CAY=7.371429,
AGG=17.65,
AYTS=0.2428571,
ATT=37.92857,
TD=1.714286,
INT=0.7142857,
COMP=66.25,
EFF=4.013571,
EM=22.90107,
TLOS=2.763571,
AVG=4.117857,
CUSH=5.657024,
SEP=2.57631,
TAY=10.92202,
CTCH=67.72182,
YACR=4.314286,
TT_OPP=2.82,
CAY_OPP=5.853846,
AGG_OPP=21.66923,
AYTS_OPP=-1.069231,
ATT_OPP=37.38462,
TD_OPP=1.692308,
INT_OPP=1.230769,
COMP_OPP=61.66154,
EFF_OPP=14.86577,
EM_OPP=18.05923,
TLOS_OPP=2.857692,
AVG_OPP=4.238462,
CUSH_OPP=5.373718,
SEP_OPP=2.502564,
TAY_OPP=9.224359,
CTCH_OPP=61.88724,
YACR_OPP=4.267308
)


# NYG for NYG VS. DAL
NYG_DAL_MU <- data.frame(TT=2.82,
CAY=5.853846,
AGG=21.66923,
AYTS=-1.069231,
ATT=37.38462,
TD=1.692308,
INT=1.230769,
COMP=61.66154,
EFF=14.86577,
EM=18.05923,
TLOS=2.857692,
AVG=4.238462,
CUSH=5.373718,
SEP=2.502564,
TAY=9.224359,
CTCH=61.88724,
YACR=4.267308,
TT_OPP=2.812143,
CAY_OPP=7.371429,
AGG_OPP=17.65,
AYTS_OPP=0.2428571,
ATT_OPP=37.92857,
TD_OPP=1.714286,
INT_OPP=0.7142857,
COMP_OPP=66.25,
EFF_OPP=4.013571,
EM_OPP=22.90107,
TLOS_OPP=2.763571,
AVG_OPP=4.117857,
CUSH_OPP=5.657024,
SEP_OPP=2.57631,
TAY_OPP=10.92202,
CTCH_OPP=67.72182,
YACR_OPP=4.314286
)


# HOU for HOU VS. NE
HOU_NE_MU <- data.frame(TT=2.805,
CAY=6.45,
AGG=15.51,
AYTS=0.4,
ATT=34,
TD=1.7,
INT=0.8,
COMP=66.53,
EFF=4.195,
EM=20.158,
TLOS=2.685,
AVG=3.78,
CUSH=5.445833,
SEP=3.015,
TAY=10.6225,
CTCH=65.96517,
YACR=4.638333,
TT_OPP=2.761667,
CAY_OPP=5.658333,
AGG_OPP=16.4,
AYTS_OPP=-1.566667,
ATT_OPP=37.75,
TD_OPP=1.416667,
INT_OPP=0.5,
COMP_OPP=60.2,
EFF_OPP=4.098333,
EM_OPP=41.28583,
TLOS_OPP=2.7075,
AVG_OPP=4.041667,
CUSH_OPP=5.234722,
SEP_OPP=2.603472,
TAY_OPP=10.03611,
CTCH_OPP=54.95278,
YACR_OPP=3.210417
)


# NE for NE vs. HOU
NE_HOU_MU <- data.frame(TT=2.761667,
CAY=5.658333,
AGG=16.4,
AYTS=-1.566667,
ATT=37.75,
TD=1.416667,
INT=0.5,
COMP=60.2,
EFF=4.098333,
EM=41.28583,
TLOS=2.7075,
AVG=4.041667,
CUSH=5.234722,
SEP=2.603472,
TAY=10.03611,
CTCH=54.95278,
YACR=3.210417,
TT_OPP=2.805,
CAY_OPP=6.45,
AGG_OPP=15.51,
AYTS_OPP=0.4,
ATT_OPP=34,
TD_OPP=1.7,
INT_OPP=0.8,
COMP_OPP=66.53,
EFF_OPP=4.195,
EM_OPP=20.158,
TLOS_OPP=2.685,
AVG_OPP=3.78,
CUSH_OPP=5.445833,
SEP_OPP=3.015,
TAY_OPP=10.6225,
CTCH_OPP=65.96517,
YACR_OPP=4.638333
)


#SAINTS for NO vs. TB
NO_TB_MU <- data.frame(TT=2.682857,
CAY=4.85,
AGG=12.62143,
AYTS=-2.55,
ATT=35.21429,
TD=2.285714,
INT=0.3571429,
COMP=70.34286,
EFF=4.182857,
EM=24.24214,
TLOS=2.723571,
AVG=4.378571,
CUSH=5.569048,
SEP=2.819048,
TAY=9.671429,
CTCH=68.09631,
YACR=4.619048,
TT_OPP=2.780769,
CAY_OPP=8.461538,
AGG_OPP=15.15385,
AYTS_OPP=1.192308,
ATT_OPP=39.07692,
TD_OPP=1.846154,
INT_OPP=1.923077,
COMP_OPP=62.51538,
EFF_OPP=4.099231,
EM_OPP=27.30077,
TLOS_OPP=2.670385,
AVG_OPP=4.134615,
CUSH_OPP=5.671154,
SEP_OPP=2.498077,
TAY_OPP=13.33397,
CTCH_OPP=62.88096,
YACR_OPP=4.782051
)


#TB for TB vs. NO 
TB_NO_MU <- data.frame(TT=2.780769,
CAY=8.461538,
AGG=15.15385,
AYTS=1.192308,
ATT=39.07692,
TD=1.846154,
INT=1.923077,
COMP=62.51538,
EFF=4.099231,
EM=27.30077,
TLOS=2.670385,
AVG=4.134615,
CUSH=5.671154,
SEP=2.498077,
TAY=13.33397,
CTCH=62.88096,
YACR=4.782051,
TT_OPP=2.682857,
CAY_OPP=4.85,
AGG_OPP=12.62143,
AYTS_OPP=-2.55,
ATT_OPP=35.21429,
TD_OPP=2.285714,
INT_OPP=0.3571429,
COMP_OPP=70.34286,
EFF_OPP=4.182857,
EM_OPP=24.24214,
TLOS_OPP=2.723571,
AVG_OPP=4.378571,
CUSH_OPP=5.569048,
SEP_OPP=2.819048,
TAY_OPP=9.671429,
CTCH_OPP=68.09631,
YACR_OPP=4.619048
)


# OAK VS. HOU 
OAK_HOU_MU <- data.frame(TT=2.896923,
CAY=5.092308,
AGG=13.30769,
AYTS=-2.115385,
ATT=31.84615,
TD=1.307692,
INT=0.4615385,
COMP=70.69231,
EFF=3.731538,
EM=20.81538,
TLOS=2.713077,
AVG=4.476923,
CUSH=5.887179,
SEP=2.970513,
TAY=8.946154,
CTCH=71.2391,
YACR=5.776923,
TT_OPP=2.805,
CAY_OPP=6.45,
AGG_OPP=15.51,
AYTS_OPP=0.4,
ATT_OPP=34,
TD_OPP=1.7,
INT_OPP=0.8,
COMP_OPP=66.53,
EFF_OPP=4.195,
EM_OPP=20.158,
TLOS_OPP=2.685,
AVG_OPP=3.78,
CUSH_OPP=5.445833,
SEP_OPP=3.015,
TAY_OPP=10.6225,
CTCH_OPP=65.96517,
YACR_OPP=4.638333
)


#SF for SF vs. SEA
SF_SEA_MU <- data.frame(TT=2.660667,
CAY=5.426667,
AGG=16.81333,
AYTS=-2.353333,
ATT=31.26667,
TD=1.733333,
INT=0.8,
COMP=68.32667,
EFF=5.163778,
EM=40.854,
TLOS=2.939556,
AVG=4.568889,
CUSH=4.936111,
SEP=3.072222,
TAY=7.687778,
CTCH=74.04972,
YACR=6.507778,
TT_OPP=2.843333,
CAY_OPP=6.791667,
AGG_OPP=17.65833,
AYTS_OPP=0.375,
ATT_OPP=33,
TD_OPP=1.833333,
INT_OPP=0.3333333,
COMP_OPP=62.33333,
EFF_OPP=3.970417,
EM_OPP=23.8825,
TLOS_OPP=2.862083,
AVG_OPP=4.845833,
CUSH_OPP=5.525,
SEP_OPP=3.0375,
TAY_OPP=10.92778,
CTCH_OPP=70.80903,
YACR_OPP=4.5375
)


# SEA for SEA vs. SF
SEA_SF_MU <- data.frame(TT=2.843333,
CAY=6.791667,
AGG=17.65833,
AYTS=0.375,
ATT=33,
TD=1.833333,
INT=0.3333333,
COMP=62.33333,
EFF=3.970417,
EM=23.8825,
TLOS=2.862083,
AVG=4.845833,
CUSH=5.525,
SEP=3.0375,
TAY=10.92778,
CTCH=70.80903,
YACR=4.5375,
TT_OPP=2.660667,
CAY_OPP=5.426667,
AGG_OPP=16.81333,
AYTS_OPP=-2.353333,
ATT_OPP=31.26667,
TD_OPP=1.733333,
INT_OPP=0.8,
COMP_OPP=68.32667,
EFF_OPP=5.163778,
EM_OPP=40.854,
TLOS_OPP=2.939556,
AVG_OPP=4.568889,
CUSH_OPP=4.936111,
SEP_OPP=3.072222,
TAY_OPP=7.687778,
CTCH_OPP=74.04972,
YACR_OPP=6.507778
)



NE_SB <- data.frame(TT=2.44,
CAY=6.1,
AGG=22.9,
AYTS=-0.5,
ATT=35,
TD=0,
INT=1,
COMP=60,
EFF=2.97,
EM=55.56,
TLOS=2.52,
AVG=5.2,
CUSH=5.6,
SEP=2.87,
TAY=10.57,
CTCH=70,
YACR=7.05,
TT_OPP=3.16,
CAY_OPP=7.4,
AGG_OPP=26.3,
AYTS_OPP=1.4,
ATT_OPP=38,
TD_OPP=0,
INT_OPP=1,
COMP_OPP=50,
EFF_OPP=4.25,
EM_OPP=20.158,
TLOS_OPP=2.93,
AVG_OPP=3.5,
CUSH_OPP=6.1,
SEP_OPP=2.1,
TAY_OPP=12.53,
CTCH_OPP=51.47,
YACR_OPP=4.07, 
Week = 17
)

LAR_SB <- data.frame(TT=3.16,
CAY=7.4,
AGG=26.3,
AYTS=1.4,
ATT=38,
TD=0,
INT=1,
COMP=50,
EFF=4.25,
EM=20.158,
TLOS=2.93,
AVG=3.5,
CUSH=6.1,
SEP=2.1,
TAY=12.53,
CTCH=51.47,
YACR=4.07,
TT_OPP=2.44,
CAY_OPP=6.1,
AGG_OPP=22.9,
AYTS_OPP=-0.5,
ATT_OPP=35,
TD_OPP=0,
INT_OPP=1,
COMP_OPP=60,
EFF_OPP=2.97,
EM_OPP=55.56,
TLOS_OPP=2.52,
AVG_OPP=5.2,
CUSH_OPP=5.6,
SEP_OPP=2.87,
TAY_OPP=10.57,
CTCH_OPP=70,
YACR_OPP=7.05,
Week = 17
)




HOUOAK<- data.frame(TT=2.805,
CAY=6.45,
AGG=15.51,
AYTS=0.4,
ATT=34,
TD=1.7,
INT=0.8,
COMP=66.53,
EFF=4.195,
EM=20.158,
TLOS=2.685,
AVG=3.78,
CUSH=5.445833,
SEP=3.015,
TAY=10.6225,
CTCH=65.96517,
YACR=4.638333,
TT_OPP=2.896923,
CAY_OPP=5.092308,
AGG_OPP=13.30769,
AYTS_OPP=-2.115385,
ATT_OPP=31.84615,
TD_OPP=1.307692,
INT_OPP=0.4615385,
COMP_OPP=70.69231,
EFF_OPP=3.731538,
EM_OPP=20.81538,
TLOS_OPP=2.713077,
AVG_OPP=4.476923,
CUSH_OPP=5.887179,
SEP_OPP=2.970513,
TAY_OPP=8.946154,
CTCH_OPP=71.2391,
YACR_OPP=5.776923
)
```



```{r}
# new dataframes

BALPIT <- data.frame(
TT=2.96,
CAY=6.4,
AGG=14.6,
AYTS=-0.8,
ATT=27.4,
TD=1.55,
INT=0.55,
COMP=64,
EFF=3.56,
EM=22.88333,
TLOS=2.84,
AVG=4.7,
CUSH=6.2667,
SEP=3.133,
TAY=11.333,
CTCH=65.4,
YACR=4.5,
TT_OPP=2.31,
CAY_OPP=4.8,
AGG_OPP=16.2,
AYTS_OPP=-1.4,
ATT_OPP=37.11,
TD_OPP=2.44,
INT_OPP=0.44,
COMP_OPP=66.8,
EFF_OPP=4.08,
EM_OPP=22.73,
TLOS_OPP=2.85,
AVG_OPP=4.2,
CUSH_OPP=6,
SEP_OPP=3.06,
TAY_OPP=9.22,
CTCH_OPP=64.246,
YACR_OPP=5.12, Week = 12
)


PITBAL <- data.frame(TT=2.31,
CAY=4.8,
AGG=16.2,
AYTS=-1.4,
ATT=37.11,
TD=2.44,
INT=0.44,
COMP=66.8,
EFF=4.08,
EM=22.73,
TLOS=2.85,
AVG=4.2,
CUSH=6,
SEP=3.06,
TAY=9.22,
CTCH=64.246,
YACR=5.12,
TT_OPP=2.96,
CAY_OPP=6.4,
AGG_OPP=14.6,
AYTS_OPP=-0.8,
ATT_OPP=27.4,
TD_OPP=1.55,
INT_OPP=0.55,
COMP_OPP=64,
EFF_OPP=3.56,
EM_OPP=22.88333,
TLOS_OPP=2.84,
AVG_OPP=4.7,
CUSH_OPP=6.2667,
SEP_OPP=3.133,
TAY_OPP=11.333,
CTCH_OPP=65.4,
YACR_OPP=4.5, Week = 12
)

ARILAR <- data.frame(TT=2.74,
CAY=6.3,
AGG=12.2,
AYTS=-0.7,
ATT=34.556,
TD=1.889,
INT=0.889,
COMP=68.2,
EFF=3.555,
EM=10.895,
TLOS=2.8,
AVG=4.7,
CUSH=6.3,
SEP=3.23,
TAY=9.3,
CTCH=69.77,
YACR=4.4,
TT_OPP=2.73,
CAY_OPP=5.2,
AGG_OPP=13.7,
AYTS_OPP=-1.2,
ATT_OPP=35.667,
TD_OPP=1.44,
INT_OPP=0.667,
COMP_OPP=66.4,
EFF_OPP=3.785,
EM_OPP=21.13,
TLOS_OPP=2.8,
AVG_OPP=4.55,
CUSH_OPP=6.26,
SEP_OPP=3.28,
TAY_OPP=8,
CTCH_OPP=69.594,
YACR_OPP=6.04, Week = 13
)

ATLCAR <- data.frame(TT=2.89,
CAY=7.6,
AGG=14.5,
AYTS=0.4,
ATT=39,
TD=1.667,
INT=0.556,
COMP=67.2,
EFF=4.345,
EM=17.52,
TLOS=2.86,
AVG=4,
CUSH=6.62,
SEP=3.12,
TAY=11.2,
CTCH=68.03,
YACR=3.98,
TT_OPP=2.6,
CAY_OPP=4.7,
AGG_OPP=10.6,
AYTS_OPP=-2.1,
ATT_OPP=33,
TD_OPP=1.3,
INT_OPP=0.7,
COMP_OPP=72.1,
EFF_OPP=4.14,
EM_OPP=25.08,
TLOS_OPP=2.875,
AVG_OPP=4,
CUSH_OPP=6.3667,
SEP_OPP=2.9667,
TAY_OPP=9.333,
CTCH_OPP=72.12,
YACR_OPP=5.5, Week = 7
)

CARATL <- data.frame(TT=2.6,
CAY=4.7,
AGG=10.6,
AYTS=-2.1,
ATT=33,
TD=1.3,
INT=0.7,
COMP=72.1,
EFF=4.14,
EM=25.08,
TLOS=2.875,
AVG=4,
CUSH=6.3667,
SEP=2.9667,
TAY=9.333,
CTCH=72.12,
YACR=5.5,
TT_OPP=2.89,
CAY_OPP=7.6,
AGG_OPP=14.5,
AYTS_OPP=0.4,
ATT_OPP=39,
TD_OPP=1.667,
INT_OPP=0.556,
COMP_OPP=67.2,
EFF_OPP=4.345,
EM_OPP=17.52,
TLOS_OPP=2.86,
AVG_OPP=4,
CUSH_OPP=6.62,
SEP_OPP=3.12,
TAY_OPP=11.2,
CTCH_OPP=68.03,
YACR_OPP=3.98, Week = 7
)



BUFNYJ <- data.frame(TT=3.05,
CAY=6.8,
AGG=14.6,
AYTS=-1.1,
ATT=36.4,
TD=2.1,
INT=0.7,
COMP=68.4,
EFF=4.22,
EM=9.14,
TLOS=2.92,
AVG=3.95,
CUSH=5.525,
SEP=3.325,
TAY=11.075,
CTCH=68.8425,
YACR=4.25,
TT_OPP=2.89,
CAY_OPP=6,
AGG_OPP=19.2,
AYTS_OPP=1.8,
ATT_OPP=35,
TD_OPP=1.33,
INT_OPP=0.667,
COMP_OPP=56.7,
EFF_OPP=4.14,
EM_OPP=8.33,
TLOS_OPP=2.67,
AVG_OPP=3.6,
CUSH_OPP=5.725,
SEP_OPP=2.875,
TAY_OPP=9.775,
CTCH_OPP=55.5975,
YACR_OPP=4.275, Week = 7 
)



NYJNE <- data.frame(TT=2.89,
CAY=6,
AGG=19.2,
AYTS=1.8,
ATT=35,
TD=1.33,
INT=0.667,
COMP=56.7,
EFF=4.14,
EM=8.33,
TLOS=2.67,
AVG=3.6,
CUSH=5.725,
SEP=2.875,
TAY=9.775,
CTCH=55.5975,
YACR=4.275,
TT_OPP=2.83,
CAY_OPP=5.5,
AGG_OPP=13,
AYTS_OPP=-2.4,
ATT_OPP=26,
TD_OPP=0.375,
INT_OPP=0.875,
COMP_OPP=68.8,
EFF_OPP=3.52,
EM_OPP=30.495,
TLOS_OPP=2.67,
AVG_OPP=4.85,
CUSH_OPP=5.9,
SEP_OPP=2.88,
TAY_OPP=9.82,
CTCH_OPP=62.478,
YACR_OPP=3.4, Week = 17
)



CHIGB <- data.frame(TT=2.49,
CAY=5.4,
AGG=21.4,
AYTS=-1,
ATT=40.7,
TD=1.42,
INT=1,
COMP=65.6,
EFF=4.31,
EM=10.69,
TLOS=2.91,
AVG=3.6,
CUSH=6,
SEP=2.65,
TAY=10.25,
CTCH=62.02675,
YACR=3.25,
TT_OPP=2.68,
CAY_OPP=5.9,
AGG_OPP=13.1,
AYTS_OPP=0.1,
ATT_OPP=34.889,
TD_OPP=2.889,
INT_OPP=0.333,
COMP_OPP=67.8,
EFF_OPP=3.73,
EM_OPP=24.15,
TLOS_OPP=2.69,
AVG_OPP=4.55,
CUSH_OPP=5.4,
SEP_OPP=3.5,
TAY_OPP=11.9667,
CTCH_OPP=69.52667,
YACR_OPP=5.9, Week = 12
)

GBCHI <- data.frame(TT=2.68,
CAY=5.9,
AGG=13.1,
AYTS=0.1,
ATT=34.889,
TD=2.889,
INT=0.333,
COMP=67.8,
EFF=3.73,
EM=24.15,
TLOS=2.69,
AVG=4.55,
CUSH=5.4,
SEP=3.5,
TAY=11.9667,
CTCH=69.52667,
YACR=5.9,
TT_OPP=2.49,
CAY_OPP=5.4,
AGG_OPP=21.4,
AYTS_OPP=-1,
ATT_OPP=40.7,
TD_OPP=1.42,
INT_OPP=1,
COMP_OPP=65.6,
EFF_OPP=4.31,
EM_OPP=10.69,
TLOS_OPP=2.91,
AVG_OPP=3.6,
CUSH_OPP=6,
SEP_OPP=2.65,
TAY_OPP=10.25,
CTCH_OPP=62.02675,
YACR_OPP=3.25, Week = 12
)

CINCLE <- data.frame(TT=2.67,
CAY=5.8,
AGG=21.6,
AYTS=-0.4,
ATT=41.11,
TD=1.333,
INT=0.556,
COMP=65.4,
EFF=4.46,
EM=8.4,
TLOS=2.79,
AVG=3.6,
CUSH=5.8,
SEP=2.725,
TAY=10.225,
CTCH=65.385,
YACR=4.125,
TT_OPP=3.11,
CAY_OPP=7.2,
AGG_OPP=16.9,
AYTS_OPP=0.2,
ATT_OPP=27,
TD_OPP=1.667,
INT_OPP=0.778,
COMP_OPP=61.3,
EFF_OPP=3.495,
EM_OPP=28.475,
TLOS_OPP=2.96,
AVG_OPP=5.4,
CUSH_OPP=5.6,
SEP_OPP=2.9333,
TAY_OPP=10.1,
CTCH_OPP=61.55,
YACR_OPP=3.733, Week = 2 
)


CLECIN <- data.frame(TT=3.11,
CAY=7.2,
AGG=16.9,
AYTS=0.2,
ATT=27,
TD=1.667,
INT=0.778,
COMP=61.3,
EFF=3.495,
EM=28.475,
TLOS=2.96,
AVG=5.4,
CUSH=5.6,
SEP=2.9333,
TAY=10.1,
CTCH=61.55,
YACR=3.733,
TT_OPP=2.67,
CAY_OPP=5.8,
AGG_OPP=21.6,
AYTS_OPP=-0.4,
ATT_OPP=41.11,
TD_OPP=1.333,
INT_OPP=0.556,
COMP_OPP=65.4,
EFF_OPP=4.46,
EM_OPP=8.4,
TLOS_OPP=2.79,
AVG_OPP=3.6,
CUSH_OPP=5.8,
SEP_OPP=2.725,
TAY_OPP=10.225,
CTCH_OPP=65.385,
YACR_OPP=4.125, Week = 2 
)

DENKC <- data.frame(TT=2.93,
CAY=6.4,
AGG=18.9,
AYTS=0.7,
ATT=26.4,
TD=0.778,
INT=1.11,
COMP=55,
EFF=3.86,
EM=10.46,
TLOS=2.905,
AVG=4.8,
CUSH=6.14,
SEP=3.02,
TAY=11.66,
CTCH=58.144,
YACR=4.7,
TT_OPP=2.86,
CAY_OPP=6.3,
AGG_OPP=11.2,
AYTS_OPP=-0.5,
ATT_OPP=36.556,
TD_OPP=2.778,
INT_OPP=0.111,
COMP_OPP=66.9,
EFF_OPP=3.66,
EM_OPP=9.52,
TLOS_OPP=2.81,
AVG_OPP=4.7,
CUSH_OPP=5.78,
SEP_OPP=3.72,
TAY_OPP=10.04,
CTCH_OPP=70.356,
YACR_OPP=5.3, Week = 13
)

KCDEN <- data.frame(TT=2.86,
CAY=6.3,
AGG=11.2,
AYTS=-0.5,
ATT=36.556,
TD=2.778,
INT=0.111,
COMP=66.9,
EFF=3.66,
EM=9.52,
TLOS=2.81,
AVG=4.7,
CUSH=5.78,
SEP=3.72,
TAY=10.04,
CTCH=70.356,
YACR=5.3,
TT_OPP=2.93,
CAY_OPP=6.4,
AGG_OPP=18.9,
AYTS_OPP=0.7,
ATT_OPP=26.4,
TD_OPP=0.778,
INT_OPP=1.11,
COMP_OPP=55,
EFF_OPP=3.86,
EM_OPP=10.46,
TLOS_OPP=2.905,
AVG_OPP=4.8,
CUSH_OPP=6.14,
SEP_OPP=3.02,
TAY_OPP=11.66,
CTCH_OPP=58.144,
YACR_OPP=4.7, Week = 13
)

DETMIN <- data.frame(TT=2.62,
CAY=6.5,
AGG=16.7,
AYTS=-0.4,
ATT=34.556,
TD=1.889,
INT=0.778,
COMP=63.7,
EFF=3.925,
EM=27.49,
TLOS=2.75,
AVG=4.25,
CUSH=6.075,
SEP=2.85,
TAY=10.125,
CTCH=64.6925,
YACR=4.675,
TT_OPP=2.94,
CAY_OPP=7.9,
AGG_OPP=19.1,
AYTS_OPP=0.3,
ATT_OPP=26.125,
TD_OPP=1.875,
INT_OPP=1.25,
COMP_OPP=65.6,
EFF_OPP=3.62,
EM_OPP=29.945,
TLOS_OPP=2.87,
AVG_OPP=5.05,
CUSH_OPP=6.2,
SEP_OPP=2.55,
TAY_OPP=12.95,
CTCH_OPP=70.675,
YACR_OPP=4.8, Week = 17
)


MINDET <- data.frame(TT=2.94,
CAY=7.9,
AGG=19.1,
AYTS=0.3,
ATT=26.125,
TD=1.875,
INT=1.25,
COMP=65.6,
EFF=3.62,
EM=29.945,
TLOS=2.87,
AVG=5.05,
CUSH=6.2,
SEP=2.55,
TAY=12.95,
CTCH=70.675,
YACR=4.8,
TT_OPP=2.62,
CAY_OPP=6.5,
AGG_OPP=16.7,
AYTS_OPP=-0.4,
ATT_OPP=34.556,
TD_OPP=1.889,
INT_OPP=0.778,
COMP_OPP=63.7,
EFF_OPP=3.925,
EM_OPP=27.49,
TLOS_OPP=2.75,
AVG_OPP=4.25,
CUSH_OPP=6.075,
SEP_OPP=2.85,
TAY_OPP=10.125,
CTCH_OPP=64.6925,
YACR_OPP=4.675, Week = 17
)

INDTEN <- data.frame(TT=2.49,
CAY=5,
AGG=15.3,
AYTS=-1.6,
ATT=34.778,
TD=1.22,
INT=0.778,
COMP=68.7,
EFF=4.275,
EM=26.8,
TLOS=2.84,
AVG=3.75,
CUSH=5.66,
SEP=2.94,
TAY=8.6,
CTCH=68.596,
YACR=4.74,
TT_OPP=2.62,
CAY_OPP=7.1,
AGG_OPP=19.9,
AYTS_OPP=-0.4,
ATT_OPP=31.222,
TD_OPP=2.22,
INT_OPP=0.33,
COMP_OPP=64.8,
EFF_OPP=3.88,
EM_OPP=23.88,
TLOS_OPP=2.77,
AVG_OPP=4.7,
CUSH_OPP=6.22,
SEP_OPP=2.6,
TAY_OPP=8.88,
CTCH_OPP=67.468,
YACR_OPP=4.56, Week = 12
)


TENIND <- data.frame(TT=2.62,
CAY=7.1,
AGG=19.9,
AYTS=-0.4,
ATT=31.222,
TD=2.22,
INT=0.33,
COMP=64.8,
EFF=3.88,
EM=23.88,
TLOS=2.77,
AVG=4.7,
CUSH=6.22,
SEP=2.6,
TAY=8.88,
CTCH=67.468,
YACR=4.56,
TT_OPP=2.49,
CAY_OPP=5,
AGG_OPP=15.3,
AYTS_OPP=-1.6,
ATT_OPP=34.778,
TD_OPP=1.22,
INT_OPP=0.778,
COMP_OPP=68.7,
EFF_OPP=4.275,
EM_OPP=26.8,
TLOS_OPP=2.84,
AVG_OPP=3.75,
CUSH_OPP=5.66,
SEP_OPP=2.94,
TAY_OPP=8.6,
CTCH_OPP=68.596,
YACR_OPP=4.74, Week = 12
)


JAXIND <- data.frame(TT=2.77,
CAY=5.7,
AGG=15.7,
AYTS=-0.2,
ATT=29.667,
TD=1.44,
INT=0.556,
COMP=65.9,
EFF=3.6,
EM=19.35,
TLOS=2.72,
AVG=4.4,
CUSH=6.18,
SEP=2.96,
TAY=9.96,
CTCH=65.026,
YACR=4.36,
TT_OPP=2.49,
CAY_OPP=5,
AGG_OPP=15.3,
AYTS_OPP=-1.6,
ATT_OPP=34.778,
TD_OPP=1.22,
INT_OPP=0.778,
COMP_OPP=68.7,
EFF_OPP=4.275,
EM_OPP=26.8,
TLOS_OPP=2.84,
AVG_OPP=3.75,
CUSH_OPP=5.66,
SEP_OPP=2.94,
TAY_OPP=8.6,
CTCH_OPP=68.596,
YACR_OPP=4.74, Week = 17
)

PHIWAS <- data.frame(TT=2.9,
CAY=6.3,
AGG=17.8,
AYTS=0.2,
ATT=38,
TD=1.33,
INT=1.33,
COMP=58.2,
EFF=3.16,
EM=3.49,
TLOS=2.97,
AVG=6,
CUSH=6.4,
SEP=2.96,
TAY=9.66,
CTCH=62.22,
YACR=3.06,
TT_OPP=2.74,
CAY_OPP=3.8,
AGG_OPP=8.7,
AYTS_OPP=-3.9,
ATT_OPP=34.667,
TD_OPP=0.33,
INT_OPP=1,
COMP_OPP=68.3,
EFF_OPP=3.92,
EM_OPP=9.71,
TLOS_OPP=2.84,
AVG_OPP=4.2,
CUSH_OPP=6.35,
SEP_OPP=3.45,
TAY_OPP=7.725,
CTCH_OPP=66.9275,
YACR_OPP=4.7, Week = 17
)


WASPHI <- data.frame(TT=2.74,
CAY=3.8,
AGG=8.7,
AYTS=-3.9,
ATT=34.667,
TD=0.33,
INT=1,
COMP=68.3,
EFF=3.92,
EM=9.71,
TLOS=2.84,
AVG=4.2,
CUSH=6.35,
SEP=3.45,
TAY=7.725,
CTCH=66.9275,
YACR=4.7,
TT_OPP=2.9,
CAY_OPP=6.3,
AGG_OPP=17.8,
AYTS_OPP=0.2,
ATT_OPP=38,
TD_OPP=1.33,
INT_OPP=1.33,
COMP_OPP=58.2,
EFF_OPP=3.16,
EM_OPP=3.49,
TLOS_OPP=2.97,
AVG_OPP=6,
CUSH_OPP=6.4,
SEP_OPP=2.96,
TAY_OPP=9.66,
CTCH_OPP=62.22,
YACR_OPP=3.06, Week = 17
)

LAR2 <- data.frame(TT=2.73,
CAY=5.2,
AGG=13.7,
AYTS=-1.2,
ATT=35.667,
TD=1.44,
INT=0.667,
COMP=66.4,
EFF=3.785,
EM=21.13,
TLOS=2.8,
AVG=4.55,
CUSH=6.26,
SEP=3.28,
TAY=8,
CTCH=69.594,
YACR=6.04,
TT_OPP=2.74,
CAY_OPP=6.3,
AGG_OPP=12.2,
AYTS_OPP=-0.7,
ATT_OPP=34.556,
TD_OPP=1.889,
INT_OPP=0.889,
COMP_OPP=68.2,
EFF_OPP=3.555,
EM_OPP=10.895,
TLOS_OPP=2.8,
AVG_OPP=4.7,
CUSH_OPP=6.3,
SEP_OPP=3.23,
TAY_OPP=9.3,
CTCH_OPP=69.77,
YACR_OPP=4.4,
Week = 14)

NE2 <- data.frame(TT=2.83,
CAY=5.5,
AGG=13,
AYTS=-2.4,
ATT=26,
TD=0.375,
INT=0.875,
COMP=68.8,
EFF=3.52,
EM=30.495,
TLOS=2.67,
AVG=4.85,
CUSH=5.9,
SEP=2.88,
TAY=9.82,
CTCH=62.478,
YACR=3.4,
TT_OPP=2.89,
CAY_OPP=6,
AGG_OPP=19.2,
AYTS_OPP=1.8,
ATT_OPP=35,
TD_OPP=1.33,
INT_OPP=0.667,
COMP_OPP=56.7,
EFF_OPP=4.14,
EM_OPP=8.33,
TLOS_OPP=2.67,
AVG_OPP=3.6,
CUSH_OPP=5.725,
SEP_OPP=2.875,
TAY_OPP=9.775,
CTCH_OPP=55.5975,
YACR_OPP=4.275,
Week = 17)

```




```{r}
#predictions 

# Match Up predictions 
LAC_P1<-predict(IRF1,newdata=LAC_MIA_MU)
LAC_P2<-predict(IRF2,newdata=LAC_MIA_MU)
LAC_P3<-predict(IRF3,newdata=LAC_MIA_MU)
LAC_P4<-predict(IRF4,newdata=LAC_MIA_MU)
LAC_P5<-predict(IRF5,newdata=LAC_MIA_MU)
LAC_P6<-predict(IRF6,newdata=LAC_MIA_MU)
LAC_P7<-predict(IRF7,newdata=LAC_MIA_MU)
LAC_P8<-predict(IRF8,newdata=LAC_MIA_MU)
LAC_P9<-predict(IRF9,newdata=LAC_MIA_MU)
LAC_P10<-predict(IRF10,newdata=LAC_MIA_MU)
LAC_P11<-predict(IRF11,newdata=LAC_MIA_MU)
LAC_P12<-predict(IRF12,newdata=LAC_MIA_MU)
LAC_P13<-predict(IRF13,newdata=LAC_MIA_MU)
LAC_P14<-predict(IRF14,newdata=LAC_MIA_MU)
LAC_P15<-predict(IRF15,newdata=LAC_MIA_MU)
LAC_P16<-predict(IRF16,newdata=LAC_MIA_MU)
LAC_P17<-predict(IRF17,newdata=LAC_MIA_MU)
LAC_P18<-predict(IRF18,newdata=LAC_MIA_MU)
LAC_P19<-predict(IRF19,newdata=LAC_MIA_MU)
LAC_P20<-predict(IRF20,newdata=LAC_MIA_MU)
LAC_P21<-predict(IRF21,newdata=LAC_MIA_MU)
MIA_P1<-predict(IRF1,newdata=MIA_LAC_MU)
MIA_P2<-predict(IRF2,newdata=MIA_LAC_MU)
MIA_P3<-predict(IRF3,newdata=MIA_LAC_MU)
MIA_P4<-predict(IRF4,newdata=MIA_LAC_MU)
MIA_P5<-predict(IRF5,newdata=MIA_LAC_MU)
MIA_P6<-predict(IRF6,newdata=MIA_LAC_MU)
MIA_P7<-predict(IRF7,newdata=MIA_LAC_MU)
MIA_P8<-predict(IRF8,newdata=MIA_LAC_MU)
MIA_P9<-predict(IRF9,newdata=MIA_LAC_MU)
MIA_P10<-predict(IRF10,newdata=MIA_LAC_MU)
MIA_P11<-predict(IRF11,newdata=MIA_LAC_MU)
MIA_P12<-predict(IRF12,newdata=MIA_LAC_MU)
MIA_P13<-predict(IRF13,newdata=MIA_LAC_MU)
MIA_P14<-predict(IRF14,newdata=MIA_LAC_MU)
MIA_P15<-predict(IRF15,newdata=MIA_LAC_MU)
MIA_P16<-predict(IRF16,newdata=MIA_LAC_MU)
MIA_P17<-predict(IRF17,newdata=MIA_LAC_MU)
MIA_P18<-predict(IRF18,newdata=MIA_LAC_MU)
MIA_P19<-predict(IRF19,newdata=MIA_LAC_MU)
MIA_P20<-predict(IRF20,newdata=MIA_LAC_MU)
MIA_P21<-predict(IRF21,newdata=MIA_LAC_MU)
DAL_P1<-predict(IRF1,newdata=DAL_NYG_MU)
DAL_P2<-predict(IRF2,newdata=DAL_NYG_MU)
DAL_P3<-predict(IRF3,newdata=DAL_NYG_MU)
DAL_P4<-predict(IRF4,newdata=DAL_NYG_MU)
DAL_P5<-predict(IRF5,newdata=DAL_NYG_MU)
DAL_P6<-predict(IRF6,newdata=DAL_NYG_MU)
DAL_P7<-predict(IRF7,newdata=DAL_NYG_MU)
DAL_P8<-predict(IRF8,newdata=DAL_NYG_MU)
DAL_P9<-predict(IRF9,newdata=DAL_NYG_MU)
DAL_P10<-predict(IRF10,newdata=DAL_NYG_MU)
DAL_P11<-predict(IRF11,newdata=DAL_NYG_MU)
DAL_P12<-predict(IRF12,newdata=DAL_NYG_MU)
DAL_P13<-predict(IRF13,newdata=DAL_NYG_MU)
DAL_P14<-predict(IRF14,newdata=DAL_NYG_MU)
DAL_P15<-predict(IRF15,newdata=DAL_NYG_MU)
DAL_P16<-predict(IRF16,newdata=DAL_NYG_MU)
DAL_P17<-predict(IRF17,newdata=DAL_NYG_MU)
DAL_P18<-predict(IRF18,newdata=DAL_NYG_MU)
DAL_P19<-predict(IRF19,newdata=DAL_NYG_MU)
DAL_P20<-predict(IRF20,newdata=DAL_NYG_MU)
DAL_P21<-predict(IRF21,newdata=DAL_NYG_MU)
NYG_P1<-predict(IRF1,newdata=NYG_DAL_MU)
NYG_P2<-predict(IRF2,newdata=NYG_DAL_MU)
NYG_P3<-predict(IRF3,newdata=NYG_DAL_MU)
NYG_P4<-predict(IRF4,newdata=NYG_DAL_MU)
NYG_P5<-predict(IRF5,newdata=NYG_DAL_MU)
NYG_P6<-predict(IRF6,newdata=NYG_DAL_MU)
NYG_P7<-predict(IRF7,newdata=NYG_DAL_MU)
NYG_P8<-predict(IRF8,newdata=NYG_DAL_MU)
NYG_P9<-predict(IRF9,newdata=NYG_DAL_MU)
NYG_P10<-predict(IRF10,newdata=NYG_DAL_MU)
NYG_P11<-predict(IRF11,newdata=NYG_DAL_MU)
NYG_P12<-predict(IRF12,newdata=NYG_DAL_MU)
NYG_P13<-predict(IRF13,newdata=NYG_DAL_MU)
NYG_P14<-predict(IRF14,newdata=NYG_DAL_MU)
NYG_P15<-predict(IRF15,newdata=NYG_DAL_MU)
NYG_P16<-predict(IRF16,newdata=NYG_DAL_MU)
NYG_P17<-predict(IRF17,newdata=NYG_DAL_MU)
NYG_P18<-predict(IRF18,newdata=NYG_DAL_MU)
NYG_P19<-predict(IRF19,newdata=NYG_DAL_MU)
NYG_P20<-predict(IRF20,newdata=NYG_DAL_MU)
NYG_P21<-predict(IRF21,newdata=NYG_DAL_MU)
HOU_P1<-predict(IRF1,newdata=HOU_NE_MU)
HOU_P2<-predict(IRF2,newdata=HOU_NE_MU)
HOU_P3<-predict(IRF3,newdata=HOU_NE_MU)
HOU_P4<-predict(IRF4,newdata=HOU_NE_MU)
HOU_P5<-predict(IRF5,newdata=HOU_NE_MU)
HOU_P6<-predict(IRF6,newdata=HOU_NE_MU)
HOU_P7<-predict(IRF7,newdata=HOU_NE_MU)
HOU_P8<-predict(IRF8,newdata=HOU_NE_MU)
HOU_P9<-predict(IRF9,newdata=HOU_NE_MU)
HOU_P10<-predict(IRF10,newdata=HOU_NE_MU)
HOU_P11<-predict(IRF11,newdata=HOU_NE_MU)
HOU_P12<-predict(IRF12,newdata=HOU_NE_MU)
HOU_P13<-predict(IRF13,newdata=HOU_NE_MU)
HOU_P14<-predict(IRF14,newdata=HOU_NE_MU)
HOU_P15<-predict(IRF15,newdata=HOU_NE_MU)
HOU_P16<-predict(IRF16,newdata=HOU_NE_MU)
HOU_P17<-predict(IRF17,newdata=HOU_NE_MU)
HOU_P18<-predict(IRF18,newdata=HOU_NE_MU)
HOU_P19<-predict(IRF19,newdata=HOU_NE_MU)
HOU_P20<-predict(IRF20,newdata=HOU_NE_MU)
HOU_P21<-predict(IRF21,newdata=HOU_NE_MU)
NE_P1<-predict(IRF1,newdata=NE_HOU_MU)
NE_P2<-predict(IRF2,newdata=NE_HOU_MU)
NE_P3<-predict(IRF3,newdata=NE_HOU_MU)
NE_P4<-predict(IRF4,newdata=NE_HOU_MU)
NE_P5<-predict(IRF5,newdata=NE_HOU_MU)
NE_P6<-predict(IRF6,newdata=NE_HOU_MU)
NE_P7<-predict(IRF7,newdata=NE_HOU_MU)
NE_P8<-predict(IRF8,newdata=NE_HOU_MU)
NE_P9<-predict(IRF9,newdata=NE_HOU_MU)
NE_P10<-predict(IRF10,newdata=NE_HOU_MU)
NE_P11<-predict(IRF11,newdata=NE_HOU_MU)
NE_P12<-predict(IRF12,newdata=NE_HOU_MU)
NE_P13<-predict(IRF13,newdata=NE_HOU_MU)
NE_P14<-predict(IRF14,newdata=NE_HOU_MU)
NE_P15<-predict(IRF15,newdata=NE_HOU_MU)
NE_P16<-predict(IRF16,newdata=NE_HOU_MU)
NE_P17<-predict(IRF17,newdata=NE_HOU_MU)
NE_P18<-predict(IRF18,newdata=NE_HOU_MU)
NE_P19<-predict(IRF19,newdata=NE_HOU_MU)
NE_P20<-predict(IRF20,newdata=NE_HOU_MU)
NE_P21<-predict(IRF21,newdata=NE_HOU_MU)
NO_P1<-predict(IRF1,newdata=NO_TB_MU)
NO_P2<-predict(IRF2,newdata=NO_TB_MU)
NO_P3<-predict(IRF3,newdata=NO_TB_MU)
NO_P4<-predict(IRF4,newdata=NO_TB_MU)
NO_P5<-predict(IRF5,newdata=NO_TB_MU)
NO_P6<-predict(IRF6,newdata=NO_TB_MU)
NO_P7<-predict(IRF7,newdata=NO_TB_MU)
NO_P8<-predict(IRF8,newdata=NO_TB_MU)
NO_P9<-predict(IRF9,newdata=NO_TB_MU)
NO_P10<-predict(IRF10,newdata=NO_TB_MU)
NO_P11<-predict(IRF11,newdata=NO_TB_MU)
NO_P12<-predict(IRF12,newdata=NO_TB_MU)
NO_P13<-predict(IRF13,newdata=NO_TB_MU)
NO_P14<-predict(IRF14,newdata=NO_TB_MU)
NO_P15<-predict(IRF15,newdata=NO_TB_MU)
NO_P16<-predict(IRF16,newdata=NO_TB_MU)
NO_P17<-predict(IRF17,newdata=NO_TB_MU)
NO_P18<-predict(IRF18,newdata=NO_TB_MU)
NO_P19<-predict(IRF19,newdata=NO_TB_MU)
NO_P20<-predict(IRF20,newdata=NO_TB_MU)
NO_P21<-predict(IRF21,newdata=NO_TB_MU)
TB_P1<-predict(IRF1,newdata=TB_NO_MU)
TB_P2<-predict(IRF2,newdata=TB_NO_MU)
TB_P3<-predict(IRF3,newdata=TB_NO_MU)
TB_P4<-predict(IRF4,newdata=TB_NO_MU)
TB_P5<-predict(IRF5,newdata=TB_NO_MU)
TB_P6<-predict(IRF6,newdata=TB_NO_MU)
TB_P7<-predict(IRF7,newdata=TB_NO_MU)
TB_P8<-predict(IRF8,newdata=TB_NO_MU)
TB_P9<-predict(IRF9,newdata=TB_NO_MU)
TB_P10<-predict(IRF10,newdata=TB_NO_MU)
TB_P11<-predict(IRF11,newdata=TB_NO_MU)
TB_P12<-predict(IRF12,newdata=TB_NO_MU)
TB_P13<-predict(IRF13,newdata=TB_NO_MU)
TB_P14<-predict(IRF14,newdata=TB_NO_MU)
TB_P15<-predict(IRF15,newdata=TB_NO_MU)
TB_P16<-predict(IRF16,newdata=TB_NO_MU)
TB_P17<-predict(IRF17,newdata=TB_NO_MU)
TB_P18<-predict(IRF18,newdata=TB_NO_MU)
TB_P19<-predict(IRF19,newdata=TB_NO_MU)
TB_P20<-predict(IRF20,newdata=TB_NO_MU)
TB_P21<-predict(IRF21,newdata=TB_NO_MU)
OAK_P1<-predict(IRF1,newdata=OAK_HOU_MU)
OAK_P2<-predict(IRF2,newdata=OAK_HOU_MU)
OAK_P3<-predict(IRF3,newdata=OAK_HOU_MU)
OAK_P4<-predict(IRF4,newdata=OAK_HOU_MU)
OAK_P5<-predict(IRF5,newdata=OAK_HOU_MU)
OAK_P6<-predict(IRF6,newdata=OAK_HOU_MU)
OAK_P7<-predict(IRF7,newdata=OAK_HOU_MU)
OAK_P8<-predict(IRF8,newdata=OAK_HOU_MU)
OAK_P9<-predict(IRF9,newdata=OAK_HOU_MU)
OAK_P10<-predict(IRF10,newdata=OAK_HOU_MU)
OAK_P11<-predict(IRF11,newdata=OAK_HOU_MU)
OAK_P12<-predict(IRF12,newdata=OAK_HOU_MU)
OAK_P13<-predict(IRF13,newdata=OAK_HOU_MU)
OAK_P14<-predict(IRF14,newdata=OAK_HOU_MU)
OAK_P15<-predict(IRF15,newdata=OAK_HOU_MU)
OAK_P16<-predict(IRF16,newdata=OAK_HOU_MU)
OAK_P17<-predict(IRF17,newdata=OAK_HOU_MU)
OAK_P18<-predict(IRF18,newdata=OAK_HOU_MU)
OAK_P19<-predict(IRF19,newdata=OAK_HOU_MU)
OAK_P20<-predict(IRF20,newdata=OAK_HOU_MU)
OAK_P21<-predict(IRF21,newdata=OAK_HOU_MU)
SF_P1<-predict(IRF1,newdata=SF_SEA_MU)
SF_P2<-predict(IRF2,newdata=SF_SEA_MU)
SF_P3<-predict(IRF3,newdata=SF_SEA_MU)
SF_P4<-predict(IRF4,newdata=SF_SEA_MU)
SF_P5<-predict(IRF5,newdata=SF_SEA_MU)
SF_P6<-predict(IRF6,newdata=SF_SEA_MU)
SF_P7<-predict(IRF7,newdata=SF_SEA_MU)
SF_P8<-predict(IRF8,newdata=SF_SEA_MU)
SF_P9<-predict(IRF9,newdata=SF_SEA_MU)
SF_P10<-predict(IRF10,newdata=SF_SEA_MU)
SF_P11<-predict(IRF11,newdata=SF_SEA_MU)
SF_P12<-predict(IRF12,newdata=SF_SEA_MU)
SF_P13<-predict(IRF13,newdata=SF_SEA_MU)
SF_P14<-predict(IRF14,newdata=SF_SEA_MU)
SF_P15<-predict(IRF15,newdata=SF_SEA_MU)
SF_P16<-predict(IRF16,newdata=SF_SEA_MU)
SF_P17<-predict(IRF17,newdata=SF_SEA_MU)
SF_P18<-predict(IRF18,newdata=SF_SEA_MU)
SF_P19<-predict(IRF19,newdata=SF_SEA_MU)
SF_P20<-predict(IRF20,newdata=SF_SEA_MU)
SF_P21<-predict(IRF21,newdata=SF_SEA_MU)
SEA_P1<-predict(IRF1,newdata=SEA_SF_MU)
SEA_P2<-predict(IRF2,newdata=SEA_SF_MU)
SEA_P3<-predict(IRF3,newdata=SEA_SF_MU)
SEA_P4<-predict(IRF4,newdata=SEA_SF_MU)
SEA_P5<-predict(IRF5,newdata=SEA_SF_MU)
SEA_P6<-predict(IRF6,newdata=SEA_SF_MU)
SEA_P7<-predict(IRF7,newdata=SEA_SF_MU)
SEA_P8<-predict(IRF8,newdata=SEA_SF_MU)
SEA_P9<-predict(IRF9,newdata=SEA_SF_MU)
SEA_P10<-predict(IRF10,newdata=SEA_SF_MU)
SEA_P11<-predict(IRF11,newdata=SEA_SF_MU)
SEA_P12<-predict(IRF12,newdata=SEA_SF_MU)
SEA_P13<-predict(IRF13,newdata=SEA_SF_MU)
SEA_P14<-predict(IRF14,newdata=SEA_SF_MU)
SEA_P15<-predict(IRF15,newdata=SEA_SF_MU)
SEA_P16<-predict(IRF16,newdata=SEA_SF_MU)
SEA_P17<-predict(IRF17,newdata=SEA_SF_MU)
SEA_P18<-predict(IRF18,newdata=SEA_SF_MU)
SEA_P19<-predict(IRF19,newdata=SEA_SF_MU)
SEA_P20<-predict(IRF20,newdata=SEA_SF_MU)
SEA_P21<-predict(IRF21,newdata=SEA_SF_MU)





# Own team Predictions 
LAC_OP1<-predict(ARFM1,newdata=LAC_SV1)
LAC_OP2<-predict(ARFM2,newdata=LAC_SV1)
LAC_OP3<-predict(ARFM3,newdata=LAC_SV1)
LAC_OP4<-predict(ARFM4,newdata=LAC_SV1)
LAC_OP5<-predict(ARFM5,newdata=LAC_SV1)
LAC_OP6<-predict(ARFM6,newdata=LAC_SV1)
LAC_OP7<-predict(ARFM7,newdata=LAC_SV1)
LAC_OP8<-predict(ARFM8,newdata=LAC_SV1)
LAC_OP9<-predict(ARFM9,newdata=LAC_SV1)
LAC_OP10<-predict(ARFM10,newdata=LAC_SV1)
LAC_OP11<-predict(ARFM11,newdata=LAC_SV1)
LAC_OP12<-predict(ARFM12,newdata=LAC_SV1)
LAC_OP13<-predict(ARFM13,newdata=LAC_SV1)
LAC_OP14<-predict(ARFM14,newdata=LAC_SV1)
LAC_OP15<-predict(ARFM15,newdata=LAC_SV1)
LAC_OP16<-predict(ARFM16,newdata=LAC_SV1)
LAC_OP17<-predict(ARFM17,newdata=LAC_SV1)
LAC_OP18<-predict(ARFM18,newdata=LAC_SV1)
LAC_OP19<-predict(ARFM19,newdata=LAC_SV1)
LAC_OP20<-predict(ARFM20,newdata=LAC_SV1)
LAC_OP21<-predict(ARFM21,newdata=LAC_SV1)
LAC_OP22<-predict(ARFM22,newdata=LAC_SV1)
LAC_OP23<-predict(ARFM23,newdata=LAC_SV1)
LAC_OP24<-predict(ARFM24,newdata=LAC_SV1)
LAC_OP25<-predict(ARFM25,newdata=LAC_SV1)
LAC_OP26<-predict(ARFM26,newdata=LAC_SV1)
LAC_OP27<-predict(ARFM27,newdata=LAC_SV1)
LAC_OP28<-predict(ARFM28,newdata=LAC_SV1)
LAC_OP29<-predict(ARFM29,newdata=LAC_SV1)
LAC_OP30<-predict(ARFM30,newdata=LAC_SV1)
LAC_OP31<-predict(ARFM31,newdata=LAC_SV1)
MIA_OP1<-predict(ARFM1,newdata=MIA_SV1)
MIA_OP2<-predict(ARFM2,newdata=MIA_SV1)
MIA_OP3<-predict(ARFM3,newdata=MIA_SV1)
MIA_OP4<-predict(ARFM4,newdata=MIA_SV1)
MIA_OP5<-predict(ARFM5,newdata=MIA_SV1)
MIA_OP6<-predict(ARFM6,newdata=MIA_SV1)
MIA_OP7<-predict(ARFM7,newdata=MIA_SV1)
MIA_OP8<-predict(ARFM8,newdata=MIA_SV1)
MIA_OP9<-predict(ARFM9,newdata=MIA_SV1)
MIA_OP10<-predict(ARFM10,newdata=MIA_SV1)
MIA_OP11<-predict(ARFM11,newdata=MIA_SV1)
MIA_OP12<-predict(ARFM12,newdata=MIA_SV1)
MIA_OP13<-predict(ARFM13,newdata=MIA_SV1)
MIA_OP14<-predict(ARFM14,newdata=MIA_SV1)
MIA_OP15<-predict(ARFM15,newdata=MIA_SV1)
MIA_OP16<-predict(ARFM16,newdata=MIA_SV1)
MIA_OP17<-predict(ARFM17,newdata=MIA_SV1)
MIA_OP18<-predict(ARFM18,newdata=MIA_SV1)
MIA_OP19<-predict(ARFM19,newdata=MIA_SV1)
MIA_OP20<-predict(ARFM20,newdata=MIA_SV1)
MIA_OP21<-predict(ARFM21,newdata=MIA_SV1)
MIA_OP22<-predict(ARFM22,newdata=MIA_SV1)
MIA_OP23<-predict(ARFM23,newdata=MIA_SV1)
MIA_OP24<-predict(ARFM24,newdata=MIA_SV1)
MIA_OP25<-predict(ARFM25,newdata=MIA_SV1)
MIA_OP26<-predict(ARFM26,newdata=MIA_SV1)
MIA_OP27<-predict(ARFM27,newdata=MIA_SV1)
MIA_OP28<-predict(ARFM28,newdata=MIA_SV1)
MIA_OP29<-predict(ARFM29,newdata=MIA_SV1)
MIA_OP30<-predict(ARFM30,newdata=MIA_SV1)
MIA_OP31<-predict(ARFM31,newdata=MIA_SV1)
DAL_OP1<-predict(ARFM1,newdata=DAL_SV1)
DAL_OP2<-predict(ARFM2,newdata=DAL_SV1)
DAL_OP3<-predict(ARFM3,newdata=DAL_SV1)
DAL_OP4<-predict(ARFM4,newdata=DAL_SV1)
DAL_OP5<-predict(ARFM5,newdata=DAL_SV1)
DAL_OP6<-predict(ARFM6,newdata=DAL_SV1)
DAL_OP7<-predict(ARFM7,newdata=DAL_SV1)
DAL_OP8<-predict(ARFM8,newdata=DAL_SV1)
DAL_OP9<-predict(ARFM9,newdata=DAL_SV1)
DAL_OP10<-predict(ARFM10,newdata=DAL_SV1)
DAL_OP11<-predict(ARFM11,newdata=DAL_SV1)
DAL_OP12<-predict(ARFM12,newdata=DAL_SV1)
DAL_OP13<-predict(ARFM13,newdata=DAL_SV1)
DAL_OP14<-predict(ARFM14,newdata=DAL_SV1)
DAL_OP15<-predict(ARFM15,newdata=DAL_SV1)
DAL_OP16<-predict(ARFM16,newdata=DAL_SV1)
DAL_OP17<-predict(ARFM17,newdata=DAL_SV1)
DAL_OP18<-predict(ARFM18,newdata=DAL_SV1)
DAL_OP19<-predict(ARFM19,newdata=DAL_SV1)
DAL_OP20<-predict(ARFM20,newdata=DAL_SV1)
DAL_OP21<-predict(ARFM21,newdata=DAL_SV1)
DAL_OP22<-predict(ARFM22,newdata=DAL_SV1)
DAL_OP23<-predict(ARFM23,newdata=DAL_SV1)
DAL_OP24<-predict(ARFM24,newdata=DAL_SV1)
DAL_OP25<-predict(ARFM25,newdata=DAL_SV1)
DAL_OP26<-predict(ARFM26,newdata=DAL_SV1)
DAL_OP27<-predict(ARFM27,newdata=DAL_SV1)
DAL_OP28<-predict(ARFM28,newdata=DAL_SV1)
DAL_OP29<-predict(ARFM29,newdata=DAL_SV1)
DAL_OP30<-predict(ARFM30,newdata=DAL_SV1)
DAL_OP31<-predict(ARFM31,newdata=DAL_SV1)
NYG_OP1<-predict(ARFM1,newdata=NYG_SV1)
NYG_OP2<-predict(ARFM2,newdata=NYG_SV1)
NYG_OP3<-predict(ARFM3,newdata=NYG_SV1)
NYG_OP4<-predict(ARFM4,newdata=NYG_SV1)
NYG_OP5<-predict(ARFM5,newdata=NYG_SV1)
NYG_OP6<-predict(ARFM6,newdata=NYG_SV1)
NYG_OP7<-predict(ARFM7,newdata=NYG_SV1)
NYG_OP8<-predict(ARFM8,newdata=NYG_SV1)
NYG_OP9<-predict(ARFM9,newdata=NYG_SV1)
NYG_OP10<-predict(ARFM10,newdata=NYG_SV1)
NYG_OP11<-predict(ARFM11,newdata=NYG_SV1)
NYG_OP12<-predict(ARFM12,newdata=NYG_SV1)
NYG_OP13<-predict(ARFM13,newdata=NYG_SV1)
NYG_OP14<-predict(ARFM14,newdata=NYG_SV1)
NYG_OP15<-predict(ARFM15,newdata=NYG_SV1)
NYG_OP16<-predict(ARFM16,newdata=NYG_SV1)
NYG_OP17<-predict(ARFM17,newdata=NYG_SV1)
NYG_OP18<-predict(ARFM18,newdata=NYG_SV1)
NYG_OP19<-predict(ARFM19,newdata=NYG_SV1)
NYG_OP20<-predict(ARFM20,newdata=NYG_SV1)
NYG_OP21<-predict(ARFM21,newdata=NYG_SV1)
NYG_OP22<-predict(ARFM22,newdata=NYG_SV1)
NYG_OP23<-predict(ARFM23,newdata=NYG_SV1)
NYG_OP24<-predict(ARFM24,newdata=NYG_SV1)
NYG_OP25<-predict(ARFM25,newdata=NYG_SV1)
NYG_OP26<-predict(ARFM26,newdata=NYG_SV1)
NYG_OP27<-predict(ARFM27,newdata=NYG_SV1)
NYG_OP28<-predict(ARFM28,newdata=NYG_SV1)
NYG_OP29<-predict(ARFM29,newdata=NYG_SV1)
NYG_OP30<-predict(ARFM30,newdata=NYG_SV1)
NYG_OP31<-predict(ARFM31,newdata=NYG_SV1)
HOU_OP1<-predict(ARFM1,newdata=HOU_SV1)
HOU_OP2<-predict(ARFM2,newdata=HOU_SV1)
HOU_OP3<-predict(ARFM3,newdata=HOU_SV1)
HOU_OP4<-predict(ARFM4,newdata=HOU_SV1)
HOU_OP5<-predict(ARFM5,newdata=HOU_SV1)
HOU_OP6<-predict(ARFM6,newdata=HOU_SV1)
HOU_OP7<-predict(ARFM7,newdata=HOU_SV1)
HOU_OP8<-predict(ARFM8,newdata=HOU_SV1)
HOU_OP9<-predict(ARFM9,newdata=HOU_SV1)
HOU_OP10<-predict(ARFM10,newdata=HOU_SV1)
HOU_OP11<-predict(ARFM11,newdata=HOU_SV1)
HOU_OP12<-predict(ARFM12,newdata=HOU_SV1)
HOU_OP13<-predict(ARFM13,newdata=HOU_SV1)
HOU_OP14<-predict(ARFM14,newdata=HOU_SV1)
HOU_OP15<-predict(ARFM15,newdata=HOU_SV1)
HOU_OP16<-predict(ARFM16,newdata=HOU_SV1)
HOU_OP17<-predict(ARFM17,newdata=HOU_SV1)
HOU_OP18<-predict(ARFM18,newdata=HOU_SV1)
HOU_OP19<-predict(ARFM19,newdata=HOU_SV1)
HOU_OP20<-predict(ARFM20,newdata=HOU_SV1)
HOU_OP21<-predict(ARFM21,newdata=HOU_SV1)
HOU_OP22<-predict(ARFM22,newdata=HOU_SV1)
HOU_OP23<-predict(ARFM23,newdata=HOU_SV1)
HOU_OP24<-predict(ARFM24,newdata=HOU_SV1)
HOU_OP25<-predict(ARFM25,newdata=HOU_SV1)
HOU_OP26<-predict(ARFM26,newdata=HOU_SV1)
HOU_OP27<-predict(ARFM27,newdata=HOU_SV1)
HOU_OP28<-predict(ARFM28,newdata=HOU_SV1)
HOU_OP29<-predict(ARFM29,newdata=HOU_SV1)
HOU_OP30<-predict(ARFM30,newdata=HOU_SV1)
HOU_OP31<-predict(ARFM31,newdata=HOU_SV1)
NE_OP1<-predict(ARFM1,newdata=NE_SV1)
NE_OP2<-predict(ARFM2,newdata=NE_SV1)
NE_OP3<-predict(ARFM3,newdata=NE_SV1)
NE_OP4<-predict(ARFM4,newdata=NE_SV1)
NE_OP5<-predict(ARFM5,newdata=NE_SV1)
NE_OP6<-predict(ARFM6,newdata=NE_SV1)
NE_OP7<-predict(ARFM7,newdata=NE_SV1)
NE_OP8<-predict(ARFM8,newdata=NE_SV1)
NE_OP9<-predict(ARFM9,newdata=NE_SV1)
NE_OP10<-predict(ARFM10,newdata=NE_SV1)
NE_OP11<-predict(ARFM11,newdata=NE_SV1)
NE_OP12<-predict(ARFM12,newdata=NE_SV1)
NE_OP13<-predict(ARFM13,newdata=NE_SV1)
NE_OP14<-predict(ARFM14,newdata=NE_SV1)
NE_OP15<-predict(ARFM15,newdata=NE_SV1)
NE_OP16<-predict(ARFM16,newdata=NE_SV1)
NE_OP17<-predict(ARFM17,newdata=NE_SV1)
NE_OP18<-predict(ARFM18,newdata=NE_SV1)
NE_OP19<-predict(ARFM19,newdata=NE_SV1)
NE_OP20<-predict(ARFM20,newdata=NE_SV1)
NE_OP21<-predict(ARFM21,newdata=NE_SV1)
NE_OP22<-predict(ARFM22,newdata=NE_SV1)
NE_OP23<-predict(ARFM23,newdata=NE_SV1)
NE_OP24<-predict(ARFM24,newdata=NE_SV1)
NE_OP25<-predict(ARFM25,newdata=NE_SV1)
NE_OP26<-predict(ARFM26,newdata=NE_SV1)
NE_OP27<-predict(ARFM27,newdata=NE_SV1)
NE_OP28<-predict(ARFM28,newdata=NE_SV1)
NE_OP29<-predict(ARFM29,newdata=NE_SV1)
NE_OP30<-predict(ARFM30,newdata=NE_SV1)
NE_OP31<-predict(ARFM31,newdata=NE_SV1)
NO_OP1<-predict(ARFM1,newdata=NO_SV1)
NO_OP2<-predict(ARFM2,newdata=NO_SV1)
NO_OP3<-predict(ARFM3,newdata=NO_SV1)
NO_OP4<-predict(ARFM4,newdata=NO_SV1)
NO_OP5<-predict(ARFM5,newdata=NO_SV1)
NO_OP6<-predict(ARFM6,newdata=NO_SV1)
NO_OP7<-predict(ARFM7,newdata=NO_SV1)
NO_OP8<-predict(ARFM8,newdata=NO_SV1)
NO_OP9<-predict(ARFM9,newdata=NO_SV1)
NO_OP10<-predict(ARFM10,newdata=NO_SV1)
NO_OP11<-predict(ARFM11,newdata=NO_SV1)
NO_OP12<-predict(ARFM12,newdata=NO_SV1)
NO_OP13<-predict(ARFM13,newdata=NO_SV1)
NO_OP14<-predict(ARFM14,newdata=NO_SV1)
NO_OP15<-predict(ARFM15,newdata=NO_SV1)
NO_OP16<-predict(ARFM16,newdata=NO_SV1)
NO_OP17<-predict(ARFM17,newdata=NO_SV1)
NO_OP18<-predict(ARFM18,newdata=NO_SV1)
NO_OP19<-predict(ARFM19,newdata=NO_SV1)
NO_OP20<-predict(ARFM20,newdata=NO_SV1)
NO_OP21<-predict(ARFM21,newdata=NO_SV1)
NO_OP22<-predict(ARFM22,newdata=NO_SV1)
NO_OP23<-predict(ARFM23,newdata=NO_SV1)
NO_OP24<-predict(ARFM24,newdata=NO_SV1)
NO_OP25<-predict(ARFM25,newdata=NO_SV1)
NO_OP26<-predict(ARFM26,newdata=NO_SV1)
NO_OP27<-predict(ARFM27,newdata=NO_SV1)
NO_OP28<-predict(ARFM28,newdata=NO_SV1)
NO_OP29<-predict(ARFM29,newdata=NO_SV1)
NO_OP30<-predict(ARFM30,newdata=NO_SV1)
NO_OP31<-predict(ARFM31,newdata=NO_SV1)
OAK_OP1<-predict(ARFM1,newdata=OAK_SV1)
OAK_OP2<-predict(ARFM2,newdata=OAK_SV1)
OAK_OP3<-predict(ARFM3,newdata=OAK_SV1)
OAK_OP4<-predict(ARFM4,newdata=OAK_SV1)
OAK_OP5<-predict(ARFM5,newdata=OAK_SV1)
OAK_OP6<-predict(ARFM6,newdata=OAK_SV1)
OAK_OP7<-predict(ARFM7,newdata=OAK_SV1)
OAK_OP8<-predict(ARFM8,newdata=OAK_SV1)
OAK_OP9<-predict(ARFM9,newdata=OAK_SV1)
OAK_OP10<-predict(ARFM10,newdata=OAK_SV1)
OAK_OP11<-predict(ARFM11,newdata=OAK_SV1)
OAK_OP12<-predict(ARFM12,newdata=OAK_SV1)
OAK_OP13<-predict(ARFM13,newdata=OAK_SV1)
OAK_OP14<-predict(ARFM14,newdata=OAK_SV1)
OAK_OP15<-predict(ARFM15,newdata=OAK_SV1)
OAK_OP16<-predict(ARFM16,newdata=OAK_SV1)
OAK_OP17<-predict(ARFM17,newdata=OAK_SV1)
OAK_OP18<-predict(ARFM18,newdata=OAK_SV1)
OAK_OP19<-predict(ARFM19,newdata=OAK_SV1)
OAK_OP20<-predict(ARFM20,newdata=OAK_SV1)
OAK_OP21<-predict(ARFM21,newdata=OAK_SV1)
OAK_OP22<-predict(ARFM22,newdata=OAK_SV1)
OAK_OP23<-predict(ARFM23,newdata=OAK_SV1)
OAK_OP24<-predict(ARFM24,newdata=OAK_SV1)
OAK_OP25<-predict(ARFM25,newdata=OAK_SV1)
OAK_OP26<-predict(ARFM26,newdata=OAK_SV1)
OAK_OP27<-predict(ARFM27,newdata=OAK_SV1)
OAK_OP28<-predict(ARFM28,newdata=OAK_SV1)
OAK_OP29<-predict(ARFM29,newdata=OAK_SV1)
OAK_OP30<-predict(ARFM30,newdata=OAK_SV1)
OAK_OP31<-predict(ARFM31,newdata=OAK_SV1)
SEA_OP1<-predict(ARFM1,newdata=SEA_SV1)
SEA_OP2<-predict(ARFM2,newdata=SEA_SV1)
SEA_OP3<-predict(ARFM3,newdata=SEA_SV1)
SEA_OP4<-predict(ARFM4,newdata=SEA_SV1)
SEA_OP5<-predict(ARFM5,newdata=SEA_SV1)
SEA_OP6<-predict(ARFM6,newdata=SEA_SV1)
SEA_OP7<-predict(ARFM7,newdata=SEA_SV1)
SEA_OP8<-predict(ARFM8,newdata=SEA_SV1)
SEA_OP9<-predict(ARFM9,newdata=SEA_SV1)
SEA_OP10<-predict(ARFM10,newdata=SEA_SV1)
SEA_OP11<-predict(ARFM11,newdata=SEA_SV1)
SEA_OP12<-predict(ARFM12,newdata=SEA_SV1)
SEA_OP13<-predict(ARFM13,newdata=SEA_SV1)
SEA_OP14<-predict(ARFM14,newdata=SEA_SV1)
SEA_OP15<-predict(ARFM15,newdata=SEA_SV1)
SEA_OP16<-predict(ARFM16,newdata=SEA_SV1)
SEA_OP17<-predict(ARFM17,newdata=SEA_SV1)
SEA_OP18<-predict(ARFM18,newdata=SEA_SV1)
SEA_OP19<-predict(ARFM19,newdata=SEA_SV1)
SEA_OP20<-predict(ARFM20,newdata=SEA_SV1)
SEA_OP21<-predict(ARFM21,newdata=SEA_SV1)
SEA_OP22<-predict(ARFM22,newdata=SEA_SV1)
SEA_OP23<-predict(ARFM23,newdata=SEA_SV1)
SEA_OP24<-predict(ARFM24,newdata=SEA_SV1)
SEA_OP25<-predict(ARFM25,newdata=SEA_SV1)
SEA_OP26<-predict(ARFM26,newdata=SEA_SV1)
SEA_OP27<-predict(ARFM27,newdata=SEA_SV1)
SEA_OP28<-predict(ARFM28,newdata=SEA_SV1)
SEA_OP29<-predict(ARFM29,newdata=SEA_SV1)
SEA_OP30<-predict(ARFM30,newdata=SEA_SV1)
SEA_OP31<-predict(ARFM31,newdata=SEA_SV1)
TB_OP1<-predict(ARFM1,newdata=TB_SV1)
TB_OP2<-predict(ARFM2,newdata=TB_SV1)
TB_OP3<-predict(ARFM3,newdata=TB_SV1)
TB_OP4<-predict(ARFM4,newdata=TB_SV1)
TB_OP5<-predict(ARFM5,newdata=TB_SV1)
TB_OP6<-predict(ARFM6,newdata=TB_SV1)
TB_OP7<-predict(ARFM7,newdata=TB_SV1)
TB_OP8<-predict(ARFM8,newdata=TB_SV1)
TB_OP9<-predict(ARFM9,newdata=TB_SV1)
TB_OP10<-predict(ARFM10,newdata=TB_SV1)
TB_OP11<-predict(ARFM11,newdata=TB_SV1)
TB_OP12<-predict(ARFM12,newdata=TB_SV1)
TB_OP13<-predict(ARFM13,newdata=TB_SV1)
TB_OP14<-predict(ARFM14,newdata=TB_SV1)
TB_OP15<-predict(ARFM15,newdata=TB_SV1)
TB_OP16<-predict(ARFM16,newdata=TB_SV1)
TB_OP17<-predict(ARFM17,newdata=TB_SV1)
TB_OP18<-predict(ARFM18,newdata=TB_SV1)
TB_OP19<-predict(ARFM19,newdata=TB_SV1)
TB_OP20<-predict(ARFM20,newdata=TB_SV1)
TB_OP21<-predict(ARFM21,newdata=TB_SV1)
TB_OP22<-predict(ARFM22,newdata=TB_SV1)
TB_OP23<-predict(ARFM23,newdata=TB_SV1)
TB_OP24<-predict(ARFM24,newdata=TB_SV1)
TB_OP25<-predict(ARFM25,newdata=TB_SV1)
TB_OP26<-predict(ARFM26,newdata=TB_SV1)
TB_OP27<-predict(ARFM27,newdata=TB_SV1)
TB_OP28<-predict(ARFM28,newdata=TB_SV1)
TB_OP29<-predict(ARFM29,newdata=TB_SV1)
TB_OP30<-predict(ARFM30,newdata=TB_SV1)
TB_OP31<-predict(ARFM31,newdata=TB_SV1)
SF_OP1<-predict(ARFM1,newdata=SF_SV1)
SF_OP2<-predict(ARFM2,newdata=SF_SV1)
SF_OP3<-predict(ARFM3,newdata=SF_SV1)
SF_OP4<-predict(ARFM4,newdata=SF_SV1)
SF_OP5<-predict(ARFM5,newdata=SF_SV1)
SF_OP6<-predict(ARFM6,newdata=SF_SV1)
SF_OP7<-predict(ARFM7,newdata=SF_SV1)
SF_OP8<-predict(ARFM8,newdata=SF_SV1)
SF_OP9<-predict(ARFM9,newdata=SF_SV1)
SF_OP10<-predict(ARFM10,newdata=SF_SV1)
SF_OP11<-predict(ARFM11,newdata=SF_SV1)
SF_OP12<-predict(ARFM12,newdata=SF_SV1)
SF_OP13<-predict(ARFM13,newdata=SF_SV1)
SF_OP14<-predict(ARFM14,newdata=SF_SV1)
SF_OP15<-predict(ARFM15,newdata=SF_SV1)
SF_OP16<-predict(ARFM16,newdata=SF_SV1)
SF_OP17<-predict(ARFM17,newdata=SF_SV1)
SF_OP18<-predict(ARFM18,newdata=SF_SV1)
SF_OP19<-predict(ARFM19,newdata=SF_SV1)
SF_OP20<-predict(ARFM20,newdata=SF_SV1)
SF_OP21<-predict(ARFM21,newdata=SF_SV1)
SF_OP22<-predict(ARFM22,newdata=SF_SV1)
SF_OP23<-predict(ARFM23,newdata=SF_SV1)
SF_OP24<-predict(ARFM24,newdata=SF_SV1)
SF_OP25<-predict(ARFM25,newdata=SF_SV1)
SF_OP26<-predict(ARFM26,newdata=SF_SV1)
SF_OP27<-predict(ARFM27,newdata=SF_SV1)
SF_OP28<-predict(ARFM28,newdata=SF_SV1)
SF_OP29<-predict(ARFM29,newdata=SF_SV1)
SF_OP30<-predict(ARFM30,newdata=SF_SV1)
SF_OP31<-predict(ARFM31,newdata=SF_SV1)


```



```{r}

NESB_P1<-predict(IRF1,newdata=NE_SB)
NESB_P2<-predict(IRF2,newdata=NE_SB)
NESB_P3<-predict(IRF3,newdata=NE_SB)
NESB_P4<-predict(IRF4,newdata=NE_SB)
NESB_P5<-predict(IRF5,newdata=NE_SB)
NESB_P6<-predict(IRF6,newdata=NE_SB)
NESB_P7<-predict(IRF7,newdata=NE_SB)
NESB_P8<-predict(IRF8,newdata=NE_SB)
NESB_P9<-predict(IRF9,newdata=NE_SB)
NESB_P10<-predict(IRF10,newdata=NE_SB)
NESB_P11<-predict(IRF11,newdata=NE_SB)
NESB_P12<-predict(IRF12,newdata=NE_SB)
NESB_P13<-predict(IRF13,newdata=NE_SB)
NESB_P14<-predict(IRF14,newdata=NE_SB)
NESB_P15<-predict(IRF15,newdata=NE_SB)
NESB_P16<-predict(IRF16,newdata=NE_SB)
NESB_P17<-predict(IRF17,newdata=NE_SB)
NESB_P18<-predict(IRF18,newdata=NE_SB)
NESB_P19<-predict(IRF19,newdata=NE_SB)
NESB_P20<-predict(IRF20,newdata=NE_SB)
NESB_P21<-predict(IRF21,newdata=NE_SB)
NESB_OP1<-predict(ARFM1,newdata=NE_SB)
NESB_OP2<-predict(ARFM2,newdata=NE_SB)
NESB_OP3<-predict(ARFM3,newdata=NE_SB)
NESB_OP4<-predict(ARFM4,newdata=NE_SB)
NESB_OP5<-predict(ARFM5,newdata=NE_SB)
NESB_OP6<-predict(ARFM6,newdata=NE_SB)
NESB_OP7<-predict(ARFM7,newdata=NE_SB)
NESB_OP8<-predict(ARFM8,newdata=NE_SB)
NESB_OP9<-predict(ARFM9,newdata=NE_SB)
NESB_OP10<-predict(ARFM10,newdata=NE_SB)
NESB_OP11<-predict(ARFM11,newdata=NE_SB)
NESB_OP12<-predict(ARFM12,newdata=NE_SB)
NESB_OP13<-predict(ARFM13,newdata=NE_SB)
NESB_OP14<-predict(ARFM14,newdata=NE_SB)
NESB_OP15<-predict(ARFM15,newdata=NE_SB)
NESB_OP16<-predict(ARFM16,newdata=NE_SB)
NESB_OP17<-predict(ARFM17,newdata=NE_SB)
NESB_OP18<-predict(ARFM18,newdata=NE_SB)
NESB_OP19<-predict(ARFM19,newdata=NE_SB)
NESB_OP20<-predict(ARFM20,newdata=NE_SB)
NESB_OP21<-predict(ARFM21,newdata=NE_SB)
NESB_OP22<-predict(ARFM22,newdata=NE_SB)
NESB_OP23<-predict(ARFM23,newdata=NE_SB)
NESB_OP24<-predict(ARFM24,newdata=NE_SB)
NESB_OP25<-predict(ARFM25,newdata=NE_SB)
NESB_OP26<-predict(ARFM26,newdata=NE_SB)
NESB_OP27<-predict(ARFM27,newdata=NE_SB)
NESB_OP28<-predict(ARFM28,newdata=NE_SB)
NESB_OP29<-predict(ARFM29,newdata=NE_SB)
NESB_OP30<-predict(ARFM30,newdata=NE_SB)
NESB_OP31<-predict(ARFM31,newdata=NE_SB)






LARSB_P1<-predict(IRF1,newdata=LAR_SB)
LARSB_P2<-predict(IRF2,newdata=LAR_SB)
LARSB_P3<-predict(IRF3,newdata=LAR_SB)
LARSB_P4<-predict(IRF4,newdata=LAR_SB)
LARSB_P5<-predict(IRF5,newdata=LAR_SB)
LARSB_P6<-predict(IRF6,newdata=LAR_SB)
LARSB_P7<-predict(IRF7,newdata=LAR_SB)
LARSB_P8<-predict(IRF8,newdata=LAR_SB)
LARSB_P9<-predict(IRF9,newdata=LAR_SB)
LARSB_P10<-predict(IRF10,newdata=LAR_SB)
LARSB_P11<-predict(IRF11,newdata=LAR_SB)
LARSB_P12<-predict(IRF12,newdata=LAR_SB)
LARSB_P13<-predict(IRF13,newdata=LAR_SB)
LARSB_P14<-predict(IRF14,newdata=LAR_SB)
LARSB_P15<-predict(IRF15,newdata=LAR_SB)
LARSB_P16<-predict(IRF16,newdata=LAR_SB)
LARSB_P17<-predict(IRF17,newdata=LAR_SB)
LARSB_P18<-predict(IRF18,newdata=LAR_SB)
LARSB_P19<-predict(IRF19,newdata=LAR_SB)
LARSB_P20<-predict(IRF20,newdata=LAR_SB)
LARSB_P21<-predict(IRF21,newdata=LAR_SB)
LARSB_OP1<-predict(ARFM1,newdata=LAR_SB)
LARSB_OP2<-predict(ARFM2,newdata=LAR_SB)
LARSB_OP3<-predict(ARFM3,newdata=LAR_SB)
LARSB_OP4<-predict(ARFM4,newdata=LAR_SB)
LARSB_OP5<-predict(ARFM5,newdata=LAR_SB)
LARSB_OP6<-predict(ARFM6,newdata=LAR_SB)
LARSB_OP7<-predict(ARFM7,newdata=LAR_SB)
LARSB_OP8<-predict(ARFM8,newdata=LAR_SB)
LARSB_OP9<-predict(ARFM9,newdata=LAR_SB)
LARSB_OP10<-predict(ARFM10,newdata=LAR_SB)
LARSB_OP11<-predict(ARFM11,newdata=LAR_SB)
LARSB_OP12<-predict(ARFM12,newdata=LAR_SB)
LARSB_OP13<-predict(ARFM13,newdata=LAR_SB)
LARSB_OP14<-predict(ARFM14,newdata=LAR_SB)
LARSB_OP15<-predict(ARFM15,newdata=LAR_SB)
LARSB_OP16<-predict(ARFM16,newdata=LAR_SB)
LARSB_OP17<-predict(ARFM17,newdata=LAR_SB)
LARSB_OP18<-predict(ARFM18,newdata=LAR_SB)
LARSB_OP19<-predict(ARFM19,newdata=LAR_SB)
LARSB_OP20<-predict(ARFM20,newdata=LAR_SB)
LARSB_OP21<-predict(ARFM21,newdata=LAR_SB)
LARSB_OP22<-predict(ARFM22,newdata=LAR_SB)
LARSB_OP23<-predict(ARFM23,newdata=LAR_SB)
LARSB_OP24<-predict(ARFM24,newdata=LAR_SB)
LARSB_OP25<-predict(ARFM25,newdata=LAR_SB)
LARSB_OP26<-predict(ARFM26,newdata=LAR_SB)
LARSB_OP27<-predict(ARFM27,newdata=LAR_SB)
LARSB_OP28<-predict(ARFM28,newdata=LAR_SB)
LARSB_OP29<-predict(ARFM29,newdata=LAR_SB)
LARSB_OP30<-predict(ARFM30,newdata=LAR_SB)
LARSB_OP31<-predict(ARFM31,newdata=LAR_SB)
```



```{r}
HOUO_P1<-predict(IRF1,newdata=HOUOAK)
HOUO_P2<-predict(IRF2,newdata=HOUOAK)
HOUO_P3<-predict(IRF3,newdata=HOUOAK)
HOUO_P4<-predict(IRF4,newdata=HOUOAK)
HOUO_P5<-predict(IRF5,newdata=HOUOAK)
HOUO_P6<-predict(IRF6,newdata=HOUOAK)
HOUO_P7<-predict(IRF7,newdata=HOUOAK)
HOUO_P8<-predict(IRF8,newdata=HOUOAK)
HOUO_P9<-predict(IRF9,newdata=HOUOAK)
HOUO_P10<-predict(IRF10,newdata=HOUOAK)
HOUO_P11<-predict(IRF11,newdata=HOUOAK)
HOUO_P12<-predict(IRF12,newdata=HOUOAK)
HOUO_P13<-predict(IRF13,newdata=HOUOAK)
HOUO_P14<-predict(IRF14,newdata=HOUOAK)
HOUO_P15<-predict(IRF15,newdata=HOUOAK)
HOUO_P16<-predict(IRF16,newdata=HOUOAK)
HOUO_P17<-predict(IRF17,newdata=HOUOAK)
HOUO_P18<-predict(IRF18,newdata=HOUOAK)
HOUO_P19<-predict(IRF19,newdata=HOUOAK)
HOUO_P20<-predict(IRF20,newdata=HOUOAK)
HOUO_P21<-predict(IRF21,newdata=HOUOAK)
HOU_OP1<-predict(ARFM1,newdata=HOU_SV1)
HOU_OP2<-predict(ARFM2,newdata=HOU_SV1)
HOU_OP3<-predict(ARFM3,newdata=HOU_SV1)
HOU_OP4<-predict(ARFM4,newdata=HOU_SV1)
HOU_OP5<-predict(ARFM5,newdata=HOU_SV1)
HOU_OP6<-predict(ARFM6,newdata=HOU_SV1)
HOU_OP7<-predict(ARFM7,newdata=HOU_SV1)
HOU_OP8<-predict(ARFM8,newdata=HOU_SV1)
HOU_OP9<-predict(ARFM9,newdata=HOU_SV1)
HOU_OP10<-predict(ARFM10,newdata=HOU_SV1)
HOU_OP11<-predict(ARFM11,newdata=HOU_SV1)
HOU_OP12<-predict(ARFM12,newdata=HOU_SV1)
HOU_OP13<-predict(ARFM13,newdata=HOU_SV1)
HOU_OP14<-predict(ARFM14,newdata=HOU_SV1)
HOU_OP15<-predict(ARFM15,newdata=HOU_SV1)
HOU_OP16<-predict(ARFM16,newdata=HOU_SV1)
HOU_OP17<-predict(ARFM17,newdata=HOU_SV1)
HOU_OP18<-predict(ARFM18,newdata=HOU_SV1)
HOU_OP19<-predict(ARFM19,newdata=HOU_SV1)
HOU_OP20<-predict(ARFM20,newdata=HOU_SV1)
HOU_OP21<-predict(ARFM21,newdata=HOU_SV1)
HOU_OP22<-predict(ARFM22,newdata=HOU_SV1)
HOU_OP23<-predict(ARFM23,newdata=HOU_SV1)
HOU_OP24<-predict(ARFM24,newdata=HOU_SV1)
HOU_OP25<-predict(ARFM25,newdata=HOU_SV1)
HOU_OP26<-predict(ARFM26,newdata=HOU_SV1)
HOU_OP27<-predict(ARFM27,newdata=HOU_SV1)
HOU_OP28<-predict(ARFM28,newdata=HOU_SV1)
HOU_OP29<-predict(ARFM29,newdata=HOU_SV1)
HOU_OP30<-predict(ARFM30,newdata=HOU_SV1)
HOU_OP31<-predict(ARFM31,newdata=HOU_SV1)




```


```{r}
# NE VS LAR 2018

NE_SUB <- data.frame(TT=2.62,
CAY=5.6,
AGG=13.9,
AYTS=-1.1,
ATT=36,
TD=2,
INT=1,
COMP=65.8,
EFF=3.71,
EM=26.79,
TLOS=2.7,
AVG=4.5,
CUSH=5.8,
SEP=3.025,
TAY=11.425,
CTCH=63.7975,
YACR=5.675,
TT_OPP=2.95,
CAY_OPP=7,
AGG_OPP=13.2,
AYTS_OPP=0.1,
ATT_OPP=35,
TD_OPP=2,
INT_OPP=1,
COMP_OPP=64.9,
EFF_OPP=3.65,
EM_OPP=7.81,
TLOS_OPP=2.8,
AVG_OPP=4.9,
CUSH_OPP=6.46,
SEP_OPP=3.22,
TAY_OPP=10.46,
CTCH_OPP=65.668,
YACR_OPP=5.36,
Week = 17
)

LAR_SUB <- data.frame(TT=2.95,
CAY=7,
AGG=13.2,
AYTS=0.1,
ATT=35,
TD=2,
INT=1,
COMP=64.9,
EFF=3.65,
EM=7.81,
TLOS=2.8,
AVG=4.9,
CUSH=6.46,
SEP=3.22,
TAY=10.46,
CTCH=65.668,
YACR=5.36,
TT_OPP=2.62,
CAY_OPP=5.6,
AGG_OPP=13.9,
AYTS_OPP=-1.1,
ATT_OPP=36,
TD_OPP=2,
INT_OPP=1,
COMP_OPP=65.8,
EFF_OPP=3.71,
EM_OPP=26.79,
TLOS_OPP=2.7,
AVG_OPP=4.5,
CUSH_OPP=5.8,
SEP_OPP=3.025,
TAY_OPP=11.425,
CTCH_OPP=63.7975,
YACR_OPP=5.675, 
Week=17
)

```


```{r}
NEET_P1<-predict(IRF1,newdata=NE_SUB)
NEET_P2<-predict(IRF2,newdata=NE_SUB)
NEET_P3<-predict(IRF3,newdata=NE_SUB)
NEET_P4<-predict(IRF4,newdata=NE_SUB)
NEET_P5<-predict(IRF5,newdata=NE_SUB)
NEET_P6<-predict(IRF6,newdata=NE_SUB)
NEET_P7<-predict(IRF7,newdata=NE_SUB)
NEET_P8<-predict(IRF8,newdata=NE_SUB)
NEET_P9<-predict(IRF9,newdata=NE_SUB)
NEET_P10<-predict(IRF10,newdata=NE_SUB)
NEET_P11<-predict(IRF11,newdata=NE_SUB)
NEET_P12<-predict(IRF12,newdata=NE_SUB)
NEET_P13<-predict(IRF13,newdata=NE_SUB)
NEET_P14<-predict(IRF14,newdata=NE_SUB)
NEET_P15<-predict(IRF15,newdata=NE_SUB)
NEET_P16<-predict(IRF16,newdata=NE_SUB)
NEET_P17<-predict(IRF17,newdata=NE_SUB)
NEET_P18<-predict(IRF18,newdata=NE_SUB)
NEET_P19<-predict(IRF19,newdata=NE_SUB)
NEET_P20<-predict(IRF20,newdata=NE_SUB)
NEET_P21<-predict(IRF21,newdata=NE_SUB)
NEET_OP1<-predict(ARFM1,newdata=NE_SUB)
NEET_OP2<-predict(ARFM2,newdata=NE_SUB)
NEET_OP3<-predict(ARFM3,newdata=NE_SUB)
NEET_OP4<-predict(ARFM4,newdata=NE_SUB)
NEET_OP5<-predict(ARFM5,newdata=NE_SUB)
NEET_OP6<-predict(ARFM6,newdata=NE_SUB)
NEET_OP7<-predict(ARFM7,newdata=NE_SUB)
NEET_OP8<-predict(ARFM8,newdata=NE_SUB)
NEET_OP9<-predict(ARFM9,newdata=NE_SUB)
NEET_OP10<-predict(ARFM10,newdata=NE_SUB)
NEET_OP11<-predict(ARFM11,newdata=NE_SUB)
NEET_OP12<-predict(ARFM12,newdata=NE_SUB)
NEET_OP13<-predict(ARFM13,newdata=NE_SUB)
NEET_OP14<-predict(ARFM14,newdata=NE_SUB)
NEET_OP15<-predict(ARFM15,newdata=NE_SUB)
NEET_OP16<-predict(ARFM16,newdata=NE_SUB)
NEET_OP17<-predict(ARFM17,newdata=NE_SUB)
NEET_OP18<-predict(ARFM18,newdata=NE_SUB)
NEET_OP19<-predict(ARFM19,newdata=NE_SUB)
NEET_OP20<-predict(ARFM20,newdata=NE_SUB)
NEET_OP21<-predict(ARFM21,newdata=NE_SUB)
NEET_OP22<-predict(ARFM22,newdata=NE_SUB)
NEET_OP23<-predict(ARFM23,newdata=NE_SUB)
NEET_OP24<-predict(ARFM24,newdata=NE_SUB)
NEET_OP25<-predict(ARFM25,newdata=NE_SUB)
NEET_OP26<-predict(ARFM26,newdata=NE_SUB)
NEET_OP27<-predict(ARFM27,newdata=NE_SUB)
NEET_OP28<-predict(ARFM28,newdata=NE_SUB)
NEET_OP29<-predict(ARFM29,newdata=NE_SUB)
NEET_OP30<-predict(ARFM30,newdata=NE_SUB)
NEET_OP31<-predict(ARFM31,newdata=NE_SUB)






LARET_P1<-predict(IRF1,newdata=LAR_SUB)
LARET_P2<-predict(IRF2,newdata=LAR_SUB)
LARET_P3<-predict(IRF3,newdata=LAR_SUB)
LARET_P4<-predict(IRF4,newdata=LAR_SUB)
LARET_P5<-predict(IRF5,newdata=LAR_SUB)
LARET_P6<-predict(IRF6,newdata=LAR_SUB)
LARET_P7<-predict(IRF7,newdata=LAR_SUB)
LARET_P8<-predict(IRF8,newdata=LAR_SUB)
LARET_P9<-predict(IRF9,newdata=LAR_SUB)
LARET_P10<-predict(IRF10,newdata=LAR_SUB)
LARET_P11<-predict(IRF11,newdata=LAR_SUB)
LARET_P12<-predict(IRF12,newdata=LAR_SUB)
LARET_P13<-predict(IRF13,newdata=LAR_SUB)
LARET_P14<-predict(IRF14,newdata=LAR_SUB)
LARET_P15<-predict(IRF15,newdata=LAR_SUB)
LARET_P16<-predict(IRF16,newdata=LAR_SUB)
LARET_P17<-predict(IRF17,newdata=LAR_SUB)
LARET_P18<-predict(IRF18,newdata=LAR_SUB)
LARET_P19<-predict(IRF19,newdata=LAR_SUB)
LARET_P20<-predict(IRF20,newdata=LAR_SUB)
LARET_P21<-predict(IRF21,newdata=LAR_SUB)
LARET_OP1<-predict(ARFM1,newdata=LAR_SUB)
LARET_OP2<-predict(ARFM2,newdata=LAR_SUB)
LARET_OP3<-predict(ARFM3,newdata=LAR_SUB)
LARET_OP4<-predict(ARFM4,newdata=LAR_SUB)
LARET_OP5<-predict(ARFM5,newdata=LAR_SUB)
LARET_OP6<-predict(ARFM6,newdata=LAR_SUB)
LARET_OP7<-predict(ARFM7,newdata=LAR_SUB)
LARET_OP8<-predict(ARFM8,newdata=LAR_SUB)
LARET_OP9<-predict(ARFM9,newdata=LAR_SUB)
LARET_OP10<-predict(ARFM10,newdata=LAR_SUB)
LARET_OP11<-predict(ARFM11,newdata=LAR_SUB)
LARET_OP12<-predict(ARFM12,newdata=LAR_SUB)
LARET_OP13<-predict(ARFM13,newdata=LAR_SUB)
LARET_OP14<-predict(ARFM14,newdata=LAR_SUB)
LARET_OP15<-predict(ARFM15,newdata=LAR_SUB)
LARET_OP16<-predict(ARFM16,newdata=LAR_SUB)
LARET_OP17<-predict(ARFM17,newdata=LAR_SUB)
LARET_OP18<-predict(ARFM18,newdata=LAR_SUB)
LARET_OP19<-predict(ARFM19,newdata=LAR_SUB)
LARET_OP20<-predict(ARFM20,newdata=LAR_SUB)
LARET_OP21<-predict(ARFM21,newdata=LAR_SUB)
LARET_OP22<-predict(ARFM22,newdata=LAR_SUB)
LARET_OP23<-predict(ARFM23,newdata=LAR_SUB)
LARET_OP24<-predict(ARFM24,newdata=LAR_SUB)
LARET_OP25<-predict(ARFM25,newdata=LAR_SUB)
LARET_OP26<-predict(ARFM26,newdata=LAR_SUB)
LARET_OP27<-predict(ARFM27,newdata=LAR_SUB)
LARET_OP28<-predict(ARFM28,newdata=LAR_SUB)
LARET_OP29<-predict(ARFM29,newdata=LAR_SUB)
LARET_OP30<-predict(ARFM30,newdata=LAR_SUB)
LARET_OP31<-predict(ARFM31,newdata=LAR_SUB)
```

```{r}
NEET_P1
NEET_P2
NEET_P3
NEET_P4
NEET_P5
NEET_P6
NEET_P7
NEET_P8
NEET_P9
NEET_P10
NEET_P11
NEET_P12
NEET_P13
NEET_P14
NEET_P15
NEET_P16
NEET_P17
NEET_P18
NEET_P19
NEET_P20
NEET_P21
NEET_OP1
NEET_OP2
NEET_OP3
NEET_OP4
NEET_OP5
NEET_OP6
NEET_OP7
NEET_OP8
NEET_OP9
NEET_OP10
NEET_OP11
NEET_OP12
NEET_OP13
NEET_OP14
NEET_OP15
NEET_OP16
NEET_OP17
NEET_OP18
NEET_OP19
NEET_OP20
NEET_OP21
NEET_OP22
NEET_OP23
NEET_OP24
NEET_OP25
NEET_OP26
NEET_OP27
NEET_OP28
NEET_OP29
NEET_OP30
NEET_OP31


LARET_P1
LARET_P2
LARET_P3
LARET_P4
LARET_P5
LARET_P6
LARET_P7
LARET_P8
LARET_P9
LARET_P10
LARET_P11
LARET_P12
LARET_P13
LARET_P14
LARET_P15
LARET_P16
LARET_P17
LARET_P18
LARET_P19
LARET_P20
LARET_P21
LARET_OP1
LARET_OP2
LARET_OP3
LARET_OP4
LARET_OP5
LARET_OP6
LARET_OP7
LARET_OP8
LARET_OP9
LARET_OP10
LARET_OP11
LARET_OP12
LARET_OP13
LARET_OP14
LARET_OP15
LARET_OP16
LARET_OP17
LARET_OP18
LARET_OP19
LARET_OP20
LARET_OP21
LARET_OP22
LARET_OP23
LARET_OP24
LARET_OP25
LARET_OP26
LARET_OP27
LARET_OP28
LARET_OP29
LARET_OP30
LARET_OP31


HOUO_P1
HOUO_P2
HOUO_P3
HOUO_P4
HOUO_P5
HOUO_P6
HOUO_P7
HOUO_P8
HOUO_P9
HOUO_P10
HOUO_P11
HOUO_P12
HOUO_P13
HOUO_P14
HOUO_P15
HOUO_P16
HOUO_P17
HOUO_P18
HOUO_P19
HOUO_P20
HOUO_P21

```


```{r}


#BAL
BAL_P1<-predict(IRF1,newdata=BALPIT)
BAL_P2<-predict(IRF2,newdata=BALPIT)
BAL_P3<-predict(IRF3,newdata=BALPIT)
BAL_P4<-predict(IRF4,newdata=BALPIT)
BAL_P5<-predict(IRF5,newdata=BALPIT)
BAL_P6<-predict(IRF6,newdata=BALPIT)
BAL_P7<-predict(IRF7,newdata=BALPIT)
BAL_P8<-predict(IRF8,newdata=BALPIT)
BAL_P9<-predict(IRF9,newdata=BALPIT)
BAL_P10<-predict(IRF10,newdata=BALPIT)
BAL_P11<-predict(IRF11,newdata=BALPIT)
BAL_P12<-predict(IRF12,newdata=BALPIT)
BAL_P13<-predict(IRF13,newdata=BALPIT)
BAL_P14<-predict(IRF14,newdata=BALPIT)
BAL_P15<-predict(IRF15,newdata=BALPIT)
BAL_P16<-predict(IRF16,newdata=BALPIT)
BAL_P17<-predict(IRF17,newdata=BALPIT)
BAL_P18<-predict(IRF18,newdata=BALPIT)
BAL_P19<-predict(IRF19,newdata=BALPIT)
BAL_P20<-predict(IRF20,newdata=BALPIT)
BAL_P21<-predict(IRF21,newdata=BALPIT)
BAL_OP1<-predict(ARFM1,newdata=BALPIT)
BAL_OP2<-predict(ARFM2,newdata=BALPIT)
BAL_OP3<-predict(ARFM3,newdata=BALPIT)
BAL_OP4<-predict(ARFM4,newdata=BALPIT)
BAL_OP5<-predict(ARFM5,newdata=BALPIT)
BAL_OP6<-predict(ARFM6,newdata=BALPIT)
BAL_OP7<-predict(ARFM7,newdata=BALPIT)
BAL_OP8<-predict(ARFM8,newdata=BALPIT)
BAL_OP9<-predict(ARFM9,newdata=BALPIT)
BAL_OP10<-predict(ARFM10,newdata=BALPIT)
BAL_OP11<-predict(ARFM11,newdata=BALPIT)
BAL_OP12<-predict(ARFM12,newdata=BALPIT)
BAL_OP13<-predict(ARFM13,newdata=BALPIT)
BAL_OP14<-predict(ARFM14,newdata=BALPIT)
BAL_OP15<-predict(ARFM15,newdata=BALPIT)
BAL_OP16<-predict(ARFM16,newdata=BALPIT)
BAL_OP17<-predict(ARFM17,newdata=BALPIT)
BAL_OP18<-predict(ARFM18,newdata=BALPIT)
BAL_OP19<-predict(ARFM19,newdata=BALPIT)
BAL_OP20<-predict(ARFM20,newdata=BALPIT)
BAL_OP21<-predict(ARFM21,newdata=BALPIT)
BAL_OP22<-predict(ARFM22,newdata=BALPIT)
BAL_OP23<-predict(ARFM23,newdata=BALPIT)
BAL_OP24<-predict(ARFM24,newdata=BALPIT)
BAL_OP25<-predict(ARFM25,newdata=BALPIT)
BAL_OP26<-predict(ARFM26,newdata=BALPIT)
BAL_OP27<-predict(ARFM27,newdata=BALPIT)
BAL_OP28<-predict(ARFM28,newdata=BALPIT)
BAL_OP29<-predict(ARFM29,newdata=BALPIT)
BAL_OP30<-predict(ARFM30,newdata=BALPIT)
BAL_OP31<-predict(ARFM31,newdata=BALPIT)


#PIT
PIT_P1<-predict(IRF1,newdata=PITBAL)
PIT_P2<-predict(IRF2,newdata=PITBAL)
PIT_P3<-predict(IRF3,newdata=PITBAL)
PIT_P4<-predict(IRF4,newdata=PITBAL)
PIT_P5<-predict(IRF5,newdata=PITBAL)
PIT_P6<-predict(IRF6,newdata=PITBAL)
PIT_P7<-predict(IRF7,newdata=PITBAL)
PIT_P8<-predict(IRF8,newdata=PITBAL)
PIT_P9<-predict(IRF9,newdata=PITBAL)
PIT_P10<-predict(IRF10,newdata=PITBAL)
PIT_P11<-predict(IRF11,newdata=PITBAL)
PIT_P12<-predict(IRF12,newdata=PITBAL)
PIT_P13<-predict(IRF13,newdata=PITBAL)
PIT_P14<-predict(IRF14,newdata=PITBAL)
PIT_P15<-predict(IRF15,newdata=PITBAL)
PIT_P16<-predict(IRF16,newdata=PITBAL)
PIT_P17<-predict(IRF17,newdata=PITBAL)
PIT_P18<-predict(IRF18,newdata=PITBAL)
PIT_P19<-predict(IRF19,newdata=PITBAL)
PIT_P20<-predict(IRF20,newdata=PITBAL)
PIT_P21<-predict(IRF21,newdata=PITBAL)
PIT_OP1<-predict(ARFM1,newdata=PITBAL)
PIT_OP2<-predict(ARFM2,newdata=PITBAL)
PIT_OP3<-predict(ARFM3,newdata=PITBAL)
PIT_OP4<-predict(ARFM4,newdata=PITBAL)
PIT_OP5<-predict(ARFM5,newdata=PITBAL)
PIT_OP6<-predict(ARFM6,newdata=PITBAL)
PIT_OP7<-predict(ARFM7,newdata=PITBAL)
PIT_OP8<-predict(ARFM8,newdata=PITBAL)
PIT_OP9<-predict(ARFM9,newdata=PITBAL)
PIT_OP10<-predict(ARFM10,newdata=PITBAL)
PIT_OP11<-predict(ARFM11,newdata=PITBAL)
PIT_OP12<-predict(ARFM12,newdata=PITBAL)
PIT_OP13<-predict(ARFM13,newdata=PITBAL)
PIT_OP14<-predict(ARFM14,newdata=PITBAL)
PIT_OP15<-predict(ARFM15,newdata=PITBAL)
PIT_OP16<-predict(ARFM16,newdata=PITBAL)
PIT_OP17<-predict(ARFM17,newdata=PITBAL)
PIT_OP18<-predict(ARFM18,newdata=PITBAL)
PIT_OP19<-predict(ARFM19,newdata=PITBAL)
PIT_OP20<-predict(ARFM20,newdata=PITBAL)
PIT_OP21<-predict(ARFM21,newdata=PITBAL)
PIT_OP22<-predict(ARFM22,newdata=PITBAL)
PIT_OP23<-predict(ARFM23,newdata=PITBAL)
PIT_OP24<-predict(ARFM24,newdata=PITBAL)
PIT_OP25<-predict(ARFM25,newdata=PITBAL)
PIT_OP26<-predict(ARFM26,newdata=PITBAL)
PIT_OP27<-predict(ARFM27,newdata=PITBAL)
PIT_OP28<-predict(ARFM28,newdata=PITBAL)
PIT_OP29<-predict(ARFM29,newdata=PITBAL)
PIT_OP30<-predict(ARFM30,newdata=PITBAL)
PIT_OP31<-predict(ARFM31,newdata=PITBAL)


#ARI
ARI_P1<-predict(IRF1,newdata=ARILAR)
ARI_P2<-predict(IRF2,newdata=ARILAR)
ARI_P3<-predict(IRF3,newdata=ARILAR)
ARI_P4<-predict(IRF4,newdata=ARILAR)
ARI_P5<-predict(IRF5,newdata=ARILAR)
ARI_P6<-predict(IRF6,newdata=ARILAR)
ARI_P7<-predict(IRF7,newdata=ARILAR)
ARI_P8<-predict(IRF8,newdata=ARILAR)
ARI_P9<-predict(IRF9,newdata=ARILAR)
ARI_P10<-predict(IRF10,newdata=ARILAR)
ARI_P11<-predict(IRF11,newdata=ARILAR)
ARI_P12<-predict(IRF12,newdata=ARILAR)
ARI_P13<-predict(IRF13,newdata=ARILAR)
ARI_P14<-predict(IRF14,newdata=ARILAR)
ARI_P15<-predict(IRF15,newdata=ARILAR)
ARI_P16<-predict(IRF16,newdata=ARILAR)
ARI_P17<-predict(IRF17,newdata=ARILAR)
ARI_P18<-predict(IRF18,newdata=ARILAR)
ARI_P19<-predict(IRF19,newdata=ARILAR)
ARI_P20<-predict(IRF20,newdata=ARILAR)
ARI_P21<-predict(IRF21,newdata=ARILAR)
ARI_OP1<-predict(ARFM1,newdata=ARILAR)
ARI_OP2<-predict(ARFM2,newdata=ARILAR)
ARI_OP3<-predict(ARFM3,newdata=ARILAR)
ARI_OP4<-predict(ARFM4,newdata=ARILAR)
ARI_OP5<-predict(ARFM5,newdata=ARILAR)
ARI_OP6<-predict(ARFM6,newdata=ARILAR)
ARI_OP7<-predict(ARFM7,newdata=ARILAR)
ARI_OP8<-predict(ARFM8,newdata=ARILAR)
ARI_OP9<-predict(ARFM9,newdata=ARILAR)
ARI_OP10<-predict(ARFM10,newdata=ARILAR)
ARI_OP11<-predict(ARFM11,newdata=ARILAR)
ARI_OP12<-predict(ARFM12,newdata=ARILAR)
ARI_OP13<-predict(ARFM13,newdata=ARILAR)
ARI_OP14<-predict(ARFM14,newdata=ARILAR)
ARI_OP15<-predict(ARFM15,newdata=ARILAR)
ARI_OP16<-predict(ARFM16,newdata=ARILAR)
ARI_OP17<-predict(ARFM17,newdata=ARILAR)
ARI_OP18<-predict(ARFM18,newdata=ARILAR)
ARI_OP19<-predict(ARFM19,newdata=ARILAR)
ARI_OP20<-predict(ARFM20,newdata=ARILAR)
ARI_OP21<-predict(ARFM21,newdata=ARILAR)
ARI_OP22<-predict(ARFM22,newdata=ARILAR)
ARI_OP23<-predict(ARFM23,newdata=ARILAR)
ARI_OP24<-predict(ARFM24,newdata=ARILAR)
ARI_OP25<-predict(ARFM25,newdata=ARILAR)
ARI_OP26<-predict(ARFM26,newdata=ARILAR)
ARI_OP27<-predict(ARFM27,newdata=ARILAR)
ARI_OP28<-predict(ARFM28,newdata=ARILAR)
ARI_OP29<-predict(ARFM29,newdata=ARILAR)
ARI_OP30<-predict(ARFM30,newdata=ARILAR)
ARI_OP31<-predict(ARFM31,newdata=ARILAR)


#ATL
ATL_P1<-predict(IRF1,newdata=ATLCAR)
ATL_P2<-predict(IRF2,newdata=ATLCAR)
ATL_P3<-predict(IRF3,newdata=ATLCAR)
ATL_P4<-predict(IRF4,newdata=ATLCAR)
ATL_P5<-predict(IRF5,newdata=ATLCAR)
ATL_P6<-predict(IRF6,newdata=ATLCAR)
ATL_P7<-predict(IRF7,newdata=ATLCAR)
ATL_P8<-predict(IRF8,newdata=ATLCAR)
ATL_P9<-predict(IRF9,newdata=ATLCAR)
ATL_P10<-predict(IRF10,newdata=ATLCAR)
ATL_P11<-predict(IRF11,newdata=ATLCAR)
ATL_P12<-predict(IRF12,newdata=ATLCAR)
ATL_P13<-predict(IRF13,newdata=ATLCAR)
ATL_P14<-predict(IRF14,newdata=ATLCAR)
ATL_P15<-predict(IRF15,newdata=ATLCAR)
ATL_P16<-predict(IRF16,newdata=ATLCAR)
ATL_P17<-predict(IRF17,newdata=ATLCAR)
ATL_P18<-predict(IRF18,newdata=ATLCAR)
ATL_P19<-predict(IRF19,newdata=ATLCAR)
ATL_P20<-predict(IRF20,newdata=ATLCAR)
ATL_P21<-predict(IRF21,newdata=ATLCAR)
ATL_OP1<-predict(ARFM1,newdata=ATLCAR)
ATL_OP2<-predict(ARFM2,newdata=ATLCAR)
ATL_OP3<-predict(ARFM3,newdata=ATLCAR)
ATL_OP4<-predict(ARFM4,newdata=ATLCAR)
ATL_OP5<-predict(ARFM5,newdata=ATLCAR)
ATL_OP6<-predict(ARFM6,newdata=ATLCAR)
ATL_OP7<-predict(ARFM7,newdata=ATLCAR)
ATL_OP8<-predict(ARFM8,newdata=ATLCAR)
ATL_OP9<-predict(ARFM9,newdata=ATLCAR)
ATL_OP10<-predict(ARFM10,newdata=ATLCAR)
ATL_OP11<-predict(ARFM11,newdata=ATLCAR)
ATL_OP12<-predict(ARFM12,newdata=ATLCAR)
ATL_OP13<-predict(ARFM13,newdata=ATLCAR)
ATL_OP14<-predict(ARFM14,newdata=ATLCAR)
ATL_OP15<-predict(ARFM15,newdata=ATLCAR)
ATL_OP16<-predict(ARFM16,newdata=ATLCAR)
ATL_OP17<-predict(ARFM17,newdata=ATLCAR)
ATL_OP18<-predict(ARFM18,newdata=ATLCAR)
ATL_OP19<-predict(ARFM19,newdata=ATLCAR)
ATL_OP20<-predict(ARFM20,newdata=ATLCAR)
ATL_OP21<-predict(ARFM21,newdata=ATLCAR)
ATL_OP22<-predict(ARFM22,newdata=ATLCAR)
ATL_OP23<-predict(ARFM23,newdata=ATLCAR)
ATL_OP24<-predict(ARFM24,newdata=ATLCAR)
ATL_OP25<-predict(ARFM25,newdata=ATLCAR)
ATL_OP26<-predict(ARFM26,newdata=ATLCAR)
ATL_OP27<-predict(ARFM27,newdata=ATLCAR)
ATL_OP28<-predict(ARFM28,newdata=ATLCAR)
ATL_OP29<-predict(ARFM29,newdata=ATLCAR)
ATL_OP30<-predict(ARFM30,newdata=ATLCAR)
ATL_OP31<-predict(ARFM31,newdata=ATLCAR)


#CAR
CAR_P1<-predict(IRF1,newdata=CARATL)
CAR_P2<-predict(IRF2,newdata=CARATL)
CAR_P3<-predict(IRF3,newdata=CARATL)
CAR_P4<-predict(IRF4,newdata=CARATL)
CAR_P5<-predict(IRF5,newdata=CARATL)
CAR_P6<-predict(IRF6,newdata=CARATL)
CAR_P7<-predict(IRF7,newdata=CARATL)
CAR_P8<-predict(IRF8,newdata=CARATL)
CAR_P9<-predict(IRF9,newdata=CARATL)
CAR_P10<-predict(IRF10,newdata=CARATL)
CAR_P11<-predict(IRF11,newdata=CARATL)
CAR_P12<-predict(IRF12,newdata=CARATL)
CAR_P13<-predict(IRF13,newdata=CARATL)
CAR_P14<-predict(IRF14,newdata=CARATL)
CAR_P15<-predict(IRF15,newdata=CARATL)
CAR_P16<-predict(IRF16,newdata=CARATL)
CAR_P17<-predict(IRF17,newdata=CARATL)
CAR_P18<-predict(IRF18,newdata=CARATL)
CAR_P19<-predict(IRF19,newdata=CARATL)
CAR_P20<-predict(IRF20,newdata=CARATL)
CAR_P21<-predict(IRF21,newdata=CARATL)
CAR_OP1<-predict(ARFM1,newdata=CARATL)
CAR_OP2<-predict(ARFM2,newdata=CARATL)
CAR_OP3<-predict(ARFM3,newdata=CARATL)
CAR_OP4<-predict(ARFM4,newdata=CARATL)
CAR_OP5<-predict(ARFM5,newdata=CARATL)
CAR_OP6<-predict(ARFM6,newdata=CARATL)
CAR_OP7<-predict(ARFM7,newdata=CARATL)
CAR_OP8<-predict(ARFM8,newdata=CARATL)
CAR_OP9<-predict(ARFM9,newdata=CARATL)
CAR_OP10<-predict(ARFM10,newdata=CARATL)
CAR_OP11<-predict(ARFM11,newdata=CARATL)
CAR_OP12<-predict(ARFM12,newdata=CARATL)
CAR_OP13<-predict(ARFM13,newdata=CARATL)
CAR_OP14<-predict(ARFM14,newdata=CARATL)
CAR_OP15<-predict(ARFM15,newdata=CARATL)
CAR_OP16<-predict(ARFM16,newdata=CARATL)
CAR_OP17<-predict(ARFM17,newdata=CARATL)
CAR_OP18<-predict(ARFM18,newdata=CARATL)
CAR_OP19<-predict(ARFM19,newdata=CARATL)
CAR_OP20<-predict(ARFM20,newdata=CARATL)
CAR_OP21<-predict(ARFM21,newdata=CARATL)
CAR_OP22<-predict(ARFM22,newdata=CARATL)
CAR_OP23<-predict(ARFM23,newdata=CARATL)
CAR_OP24<-predict(ARFM24,newdata=CARATL)
CAR_OP25<-predict(ARFM25,newdata=CARATL)
CAR_OP26<-predict(ARFM26,newdata=CARATL)
CAR_OP27<-predict(ARFM27,newdata=CARATL)
CAR_OP28<-predict(ARFM28,newdata=CARATL)
CAR_OP29<-predict(ARFM29,newdata=CARATL)
CAR_OP30<-predict(ARFM30,newdata=CARATL)
CAR_OP31<-predict(ARFM31,newdata=CARATL)


#BUF
BUF_P1<-predict(IRF1,newdata=BUFNYJ)
BUF_P2<-predict(IRF2,newdata=BUFNYJ)
BUF_P3<-predict(IRF3,newdata=BUFNYJ)
BUF_P4<-predict(IRF4,newdata=BUFNYJ)
BUF_P5<-predict(IRF5,newdata=BUFNYJ)
BUF_P6<-predict(IRF6,newdata=BUFNYJ)
BUF_P7<-predict(IRF7,newdata=BUFNYJ)
BUF_P8<-predict(IRF8,newdata=BUFNYJ)
BUF_P9<-predict(IRF9,newdata=BUFNYJ)
BUF_P10<-predict(IRF10,newdata=BUFNYJ)
BUF_P11<-predict(IRF11,newdata=BUFNYJ)
BUF_P12<-predict(IRF12,newdata=BUFNYJ)
BUF_P13<-predict(IRF13,newdata=BUFNYJ)
BUF_P14<-predict(IRF14,newdata=BUFNYJ)
BUF_P15<-predict(IRF15,newdata=BUFNYJ)
BUF_P16<-predict(IRF16,newdata=BUFNYJ)
BUF_P17<-predict(IRF17,newdata=BUFNYJ)
BUF_P18<-predict(IRF18,newdata=BUFNYJ)
BUF_P19<-predict(IRF19,newdata=BUFNYJ)
BUF_P20<-predict(IRF20,newdata=BUFNYJ)
BUF_P21<-predict(IRF21,newdata=BUFNYJ)
BUF_OP1<-predict(ARFM1,newdata=BUFNYJ)
BUF_OP2<-predict(ARFM2,newdata=BUFNYJ)
BUF_OP3<-predict(ARFM3,newdata=BUFNYJ)
BUF_OP4<-predict(ARFM4,newdata=BUFNYJ)
BUF_OP5<-predict(ARFM5,newdata=BUFNYJ)
BUF_OP6<-predict(ARFM6,newdata=BUFNYJ)
BUF_OP7<-predict(ARFM7,newdata=BUFNYJ)
BUF_OP8<-predict(ARFM8,newdata=BUFNYJ)
BUF_OP9<-predict(ARFM9,newdata=BUFNYJ)
BUF_OP10<-predict(ARFM10,newdata=BUFNYJ)
BUF_OP11<-predict(ARFM11,newdata=BUFNYJ)
BUF_OP12<-predict(ARFM12,newdata=BUFNYJ)
BUF_OP13<-predict(ARFM13,newdata=BUFNYJ)
BUF_OP14<-predict(ARFM14,newdata=BUFNYJ)
BUF_OP15<-predict(ARFM15,newdata=BUFNYJ)
BUF_OP16<-predict(ARFM16,newdata=BUFNYJ)
BUF_OP17<-predict(ARFM17,newdata=BUFNYJ)
BUF_OP18<-predict(ARFM18,newdata=BUFNYJ)
BUF_OP19<-predict(ARFM19,newdata=BUFNYJ)
BUF_OP20<-predict(ARFM20,newdata=BUFNYJ)
BUF_OP21<-predict(ARFM21,newdata=BUFNYJ)
BUF_OP22<-predict(ARFM22,newdata=BUFNYJ)
BUF_OP23<-predict(ARFM23,newdata=BUFNYJ)
BUF_OP24<-predict(ARFM24,newdata=BUFNYJ)
BUF_OP25<-predict(ARFM25,newdata=BUFNYJ)
BUF_OP26<-predict(ARFM26,newdata=BUFNYJ)
BUF_OP27<-predict(ARFM27,newdata=BUFNYJ)
BUF_OP28<-predict(ARFM28,newdata=BUFNYJ)
BUF_OP29<-predict(ARFM29,newdata=BUFNYJ)
BUF_OP30<-predict(ARFM30,newdata=BUFNYJ)
BUF_OP31<-predict(ARFM31,newdata=BUFNYJ)


#NYJ
NYJ_P1<-predict(IRF1,newdata=NYJNE)
NYJ_P2<-predict(IRF2,newdata=NYJNE)
NYJ_P3<-predict(IRF3,newdata=NYJNE)
NYJ_P4<-predict(IRF4,newdata=NYJNE)
NYJ_P5<-predict(IRF5,newdata=NYJNE)
NYJ_P6<-predict(IRF6,newdata=NYJNE)
NYJ_P7<-predict(IRF7,newdata=NYJNE)
NYJ_P8<-predict(IRF8,newdata=NYJNE)
NYJ_P9<-predict(IRF9,newdata=NYJNE)
NYJ_P10<-predict(IRF10,newdata=NYJNE)
NYJ_P11<-predict(IRF11,newdata=NYJNE)
NYJ_P12<-predict(IRF12,newdata=NYJNE)
NYJ_P13<-predict(IRF13,newdata=NYJNE)
NYJ_P14<-predict(IRF14,newdata=NYJNE)
NYJ_P15<-predict(IRF15,newdata=NYJNE)
NYJ_P16<-predict(IRF16,newdata=NYJNE)
NYJ_P17<-predict(IRF17,newdata=NYJNE)
NYJ_P18<-predict(IRF18,newdata=NYJNE)
NYJ_P19<-predict(IRF19,newdata=NYJNE)
NYJ_P20<-predict(IRF20,newdata=NYJNE)
NYJ_P21<-predict(IRF21,newdata=NYJNE)
NYJ_OP1<-predict(ARFM1,newdata=NYJNE)
NYJ_OP2<-predict(ARFM2,newdata=NYJNE)
NYJ_OP3<-predict(ARFM3,newdata=NYJNE)
NYJ_OP4<-predict(ARFM4,newdata=NYJNE)
NYJ_OP5<-predict(ARFM5,newdata=NYJNE)
NYJ_OP6<-predict(ARFM6,newdata=NYJNE)
NYJ_OP7<-predict(ARFM7,newdata=NYJNE)
NYJ_OP8<-predict(ARFM8,newdata=NYJNE)
NYJ_OP9<-predict(ARFM9,newdata=NYJNE)
NYJ_OP10<-predict(ARFM10,newdata=NYJNE)
NYJ_OP11<-predict(ARFM11,newdata=NYJNE)
NYJ_OP12<-predict(ARFM12,newdata=NYJNE)
NYJ_OP13<-predict(ARFM13,newdata=NYJNE)
NYJ_OP14<-predict(ARFM14,newdata=NYJNE)
NYJ_OP15<-predict(ARFM15,newdata=NYJNE)
NYJ_OP16<-predict(ARFM16,newdata=NYJNE)
NYJ_OP17<-predict(ARFM17,newdata=NYJNE)
NYJ_OP18<-predict(ARFM18,newdata=NYJNE)
NYJ_OP19<-predict(ARFM19,newdata=NYJNE)
NYJ_OP20<-predict(ARFM20,newdata=NYJNE)
NYJ_OP21<-predict(ARFM21,newdata=NYJNE)
NYJ_OP22<-predict(ARFM22,newdata=NYJNE)
NYJ_OP23<-predict(ARFM23,newdata=NYJNE)
NYJ_OP24<-predict(ARFM24,newdata=NYJNE)
NYJ_OP25<-predict(ARFM25,newdata=NYJNE)
NYJ_OP26<-predict(ARFM26,newdata=NYJNE)
NYJ_OP27<-predict(ARFM27,newdata=NYJNE)
NYJ_OP28<-predict(ARFM28,newdata=NYJNE)
NYJ_OP29<-predict(ARFM29,newdata=NYJNE)
NYJ_OP30<-predict(ARFM30,newdata=NYJNE)
NYJ_OP31<-predict(ARFM31,newdata=NYJNE)


#CHI
CHI_P1<-predict(IRF1,newdata=CHIGB)
CHI_P2<-predict(IRF2,newdata=CHIGB)
CHI_P3<-predict(IRF3,newdata=CHIGB)
CHI_P4<-predict(IRF4,newdata=CHIGB)
CHI_P5<-predict(IRF5,newdata=CHIGB)
CHI_P6<-predict(IRF6,newdata=CHIGB)
CHI_P7<-predict(IRF7,newdata=CHIGB)
CHI_P8<-predict(IRF8,newdata=CHIGB)
CHI_P9<-predict(IRF9,newdata=CHIGB)
CHI_P10<-predict(IRF10,newdata=CHIGB)
CHI_P11<-predict(IRF11,newdata=CHIGB)
CHI_P12<-predict(IRF12,newdata=CHIGB)
CHI_P13<-predict(IRF13,newdata=CHIGB)
CHI_P14<-predict(IRF14,newdata=CHIGB)
CHI_P15<-predict(IRF15,newdata=CHIGB)
CHI_P16<-predict(IRF16,newdata=CHIGB)
CHI_P17<-predict(IRF17,newdata=CHIGB)
CHI_P18<-predict(IRF18,newdata=CHIGB)
CHI_P19<-predict(IRF19,newdata=CHIGB)
CHI_P20<-predict(IRF20,newdata=CHIGB)
CHI_P21<-predict(IRF21,newdata=CHIGB)
CHI_OP1<-predict(ARFM1,newdata=CHIGB)
CHI_OP2<-predict(ARFM2,newdata=CHIGB)
CHI_OP3<-predict(ARFM3,newdata=CHIGB)
CHI_OP4<-predict(ARFM4,newdata=CHIGB)
CHI_OP5<-predict(ARFM5,newdata=CHIGB)
CHI_OP6<-predict(ARFM6,newdata=CHIGB)
CHI_OP7<-predict(ARFM7,newdata=CHIGB)
CHI_OP8<-predict(ARFM8,newdata=CHIGB)
CHI_OP9<-predict(ARFM9,newdata=CHIGB)
CHI_OP10<-predict(ARFM10,newdata=CHIGB)
CHI_OP11<-predict(ARFM11,newdata=CHIGB)
CHI_OP12<-predict(ARFM12,newdata=CHIGB)
CHI_OP13<-predict(ARFM13,newdata=CHIGB)
CHI_OP14<-predict(ARFM14,newdata=CHIGB)
CHI_OP15<-predict(ARFM15,newdata=CHIGB)
CHI_OP16<-predict(ARFM16,newdata=CHIGB)
CHI_OP17<-predict(ARFM17,newdata=CHIGB)
CHI_OP18<-predict(ARFM18,newdata=CHIGB)
CHI_OP19<-predict(ARFM19,newdata=CHIGB)
CHI_OP20<-predict(ARFM20,newdata=CHIGB)
CHI_OP21<-predict(ARFM21,newdata=CHIGB)
CHI_OP22<-predict(ARFM22,newdata=CHIGB)
CHI_OP23<-predict(ARFM23,newdata=CHIGB)
CHI_OP24<-predict(ARFM24,newdata=CHIGB)
CHI_OP25<-predict(ARFM25,newdata=CHIGB)
CHI_OP26<-predict(ARFM26,newdata=CHIGB)
CHI_OP27<-predict(ARFM27,newdata=CHIGB)
CHI_OP28<-predict(ARFM28,newdata=CHIGB)
CHI_OP29<-predict(ARFM29,newdata=CHIGB)
CHI_OP30<-predict(ARFM30,newdata=CHIGB)
CHI_OP31<-predict(ARFM31,newdata=CHIGB)


#GB
GB_P1<-predict(IRF1,newdata=GBCHI)
GB_P2<-predict(IRF2,newdata=GBCHI)
GB_P3<-predict(IRF3,newdata=GBCHI)
GB_P4<-predict(IRF4,newdata=GBCHI)
GB_P5<-predict(IRF5,newdata=GBCHI)
GB_P6<-predict(IRF6,newdata=GBCHI)
GB_P7<-predict(IRF7,newdata=GBCHI)
GB_P8<-predict(IRF8,newdata=GBCHI)
GB_P9<-predict(IRF9,newdata=GBCHI)
GB_P10<-predict(IRF10,newdata=GBCHI)
GB_P11<-predict(IRF11,newdata=GBCHI)
GB_P12<-predict(IRF12,newdata=GBCHI)
GB_P13<-predict(IRF13,newdata=GBCHI)
GB_P14<-predict(IRF14,newdata=GBCHI)
GB_P15<-predict(IRF15,newdata=GBCHI)
GB_P16<-predict(IRF16,newdata=GBCHI)
GB_P17<-predict(IRF17,newdata=GBCHI)
GB_P18<-predict(IRF18,newdata=GBCHI)
GB_P19<-predict(IRF19,newdata=GBCHI)
GB_P20<-predict(IRF20,newdata=GBCHI)
GB_P21<-predict(IRF21,newdata=GBCHI)
GB_OP1<-predict(ARFM1,newdata=GBCHI)
GB_OP2<-predict(ARFM2,newdata=GBCHI)
GB_OP3<-predict(ARFM3,newdata=GBCHI)
GB_OP4<-predict(ARFM4,newdata=GBCHI)
GB_OP5<-predict(ARFM5,newdata=GBCHI)
GB_OP6<-predict(ARFM6,newdata=GBCHI)
GB_OP7<-predict(ARFM7,newdata=GBCHI)
GB_OP8<-predict(ARFM8,newdata=GBCHI)
GB_OP9<-predict(ARFM9,newdata=GBCHI)
GB_OP10<-predict(ARFM10,newdata=GBCHI)
GB_OP11<-predict(ARFM11,newdata=GBCHI)
GB_OP12<-predict(ARFM12,newdata=GBCHI)
GB_OP13<-predict(ARFM13,newdata=GBCHI)
GB_OP14<-predict(ARFM14,newdata=GBCHI)
GB_OP15<-predict(ARFM15,newdata=GBCHI)
GB_OP16<-predict(ARFM16,newdata=GBCHI)
GB_OP17<-predict(ARFM17,newdata=GBCHI)
GB_OP18<-predict(ARFM18,newdata=GBCHI)
GB_OP19<-predict(ARFM19,newdata=GBCHI)
GB_OP20<-predict(ARFM20,newdata=GBCHI)
GB_OP21<-predict(ARFM21,newdata=GBCHI)
GB_OP22<-predict(ARFM22,newdata=GBCHI)
GB_OP23<-predict(ARFM23,newdata=GBCHI)
GB_OP24<-predict(ARFM24,newdata=GBCHI)
GB_OP25<-predict(ARFM25,newdata=GBCHI)
GB_OP26<-predict(ARFM26,newdata=GBCHI)
GB_OP27<-predict(ARFM27,newdata=GBCHI)
GB_OP28<-predict(ARFM28,newdata=GBCHI)
GB_OP29<-predict(ARFM29,newdata=GBCHI)
GB_OP30<-predict(ARFM30,newdata=GBCHI)
GB_OP31<-predict(ARFM31,newdata=GBCHI)


#CIN
CIN_P1<-predict(IRF1,newdata=CINCLE)
CIN_P2<-predict(IRF2,newdata=CINCLE)
CIN_P3<-predict(IRF3,newdata=CINCLE)
CIN_P4<-predict(IRF4,newdata=CINCLE)
CIN_P5<-predict(IRF5,newdata=CINCLE)
CIN_P6<-predict(IRF6,newdata=CINCLE)
CIN_P7<-predict(IRF7,newdata=CINCLE)
CIN_P8<-predict(IRF8,newdata=CINCLE)
CIN_P9<-predict(IRF9,newdata=CINCLE)
CIN_P10<-predict(IRF10,newdata=CINCLE)
CIN_P11<-predict(IRF11,newdata=CINCLE)
CIN_P12<-predict(IRF12,newdata=CINCLE)
CIN_P13<-predict(IRF13,newdata=CINCLE)
CIN_P14<-predict(IRF14,newdata=CINCLE)
CIN_P15<-predict(IRF15,newdata=CINCLE)
CIN_P16<-predict(IRF16,newdata=CINCLE)
CIN_P17<-predict(IRF17,newdata=CINCLE)
CIN_P18<-predict(IRF18,newdata=CINCLE)
CIN_P19<-predict(IRF19,newdata=CINCLE)
CIN_P20<-predict(IRF20,newdata=CINCLE)
CIN_P21<-predict(IRF21,newdata=CINCLE)
CIN_OP1<-predict(ARFM1,newdata=CINCLE)
CIN_OP2<-predict(ARFM2,newdata=CINCLE)
CIN_OP3<-predict(ARFM3,newdata=CINCLE)
CIN_OP4<-predict(ARFM4,newdata=CINCLE)
CIN_OP5<-predict(ARFM5,newdata=CINCLE)
CIN_OP6<-predict(ARFM6,newdata=CINCLE)
CIN_OP7<-predict(ARFM7,newdata=CINCLE)
CIN_OP8<-predict(ARFM8,newdata=CINCLE)
CIN_OP9<-predict(ARFM9,newdata=CINCLE)
CIN_OP10<-predict(ARFM10,newdata=CINCLE)
CIN_OP11<-predict(ARFM11,newdata=CINCLE)
CIN_OP12<-predict(ARFM12,newdata=CINCLE)
CIN_OP13<-predict(ARFM13,newdata=CINCLE)
CIN_OP14<-predict(ARFM14,newdata=CINCLE)
CIN_OP15<-predict(ARFM15,newdata=CINCLE)
CIN_OP16<-predict(ARFM16,newdata=CINCLE)
CIN_OP17<-predict(ARFM17,newdata=CINCLE)
CIN_OP18<-predict(ARFM18,newdata=CINCLE)
CIN_OP19<-predict(ARFM19,newdata=CINCLE)
CIN_OP20<-predict(ARFM20,newdata=CINCLE)
CIN_OP21<-predict(ARFM21,newdata=CINCLE)
CIN_OP22<-predict(ARFM22,newdata=CINCLE)
CIN_OP23<-predict(ARFM23,newdata=CINCLE)
CIN_OP24<-predict(ARFM24,newdata=CINCLE)
CIN_OP25<-predict(ARFM25,newdata=CINCLE)
CIN_OP26<-predict(ARFM26,newdata=CINCLE)
CIN_OP27<-predict(ARFM27,newdata=CINCLE)
CIN_OP28<-predict(ARFM28,newdata=CINCLE)
CIN_OP29<-predict(ARFM29,newdata=CINCLE)
CIN_OP30<-predict(ARFM30,newdata=CINCLE)
CIN_OP31<-predict(ARFM31,newdata=CINCLE)


#CLE
CLE_P1<-predict(IRF1,newdata=CLECIN)
CLE_P2<-predict(IRF2,newdata=CLECIN)
CLE_P3<-predict(IRF3,newdata=CLECIN)
CLE_P4<-predict(IRF4,newdata=CLECIN)
CLE_P5<-predict(IRF5,newdata=CLECIN)
CLE_P6<-predict(IRF6,newdata=CLECIN)
CLE_P7<-predict(IRF7,newdata=CLECIN)
CLE_P8<-predict(IRF8,newdata=CLECIN)
CLE_P9<-predict(IRF9,newdata=CLECIN)
CLE_P10<-predict(IRF10,newdata=CLECIN)
CLE_P11<-predict(IRF11,newdata=CLECIN)
CLE_P12<-predict(IRF12,newdata=CLECIN)
CLE_P13<-predict(IRF13,newdata=CLECIN)
CLE_P14<-predict(IRF14,newdata=CLECIN)
CLE_P15<-predict(IRF15,newdata=CLECIN)
CLE_P16<-predict(IRF16,newdata=CLECIN)
CLE_P17<-predict(IRF17,newdata=CLECIN)
CLE_P18<-predict(IRF18,newdata=CLECIN)
CLE_P19<-predict(IRF19,newdata=CLECIN)
CLE_P20<-predict(IRF20,newdata=CLECIN)
CLE_P21<-predict(IRF21,newdata=CLECIN)
CLE_OP1<-predict(ARFM1,newdata=CLECIN)
CLE_OP2<-predict(ARFM2,newdata=CLECIN)
CLE_OP3<-predict(ARFM3,newdata=CLECIN)
CLE_OP4<-predict(ARFM4,newdata=CLECIN)
CLE_OP5<-predict(ARFM5,newdata=CLECIN)
CLE_OP6<-predict(ARFM6,newdata=CLECIN)
CLE_OP7<-predict(ARFM7,newdata=CLECIN)
CLE_OP8<-predict(ARFM8,newdata=CLECIN)
CLE_OP9<-predict(ARFM9,newdata=CLECIN)
CLE_OP10<-predict(ARFM10,newdata=CLECIN)
CLE_OP11<-predict(ARFM11,newdata=CLECIN)
CLE_OP12<-predict(ARFM12,newdata=CLECIN)
CLE_OP13<-predict(ARFM13,newdata=CLECIN)
CLE_OP14<-predict(ARFM14,newdata=CLECIN)
CLE_OP15<-predict(ARFM15,newdata=CLECIN)
CLE_OP16<-predict(ARFM16,newdata=CLECIN)
CLE_OP17<-predict(ARFM17,newdata=CLECIN)
CLE_OP18<-predict(ARFM18,newdata=CLECIN)
CLE_OP19<-predict(ARFM19,newdata=CLECIN)
CLE_OP20<-predict(ARFM20,newdata=CLECIN)
CLE_OP21<-predict(ARFM21,newdata=CLECIN)
CLE_OP22<-predict(ARFM22,newdata=CLECIN)
CLE_OP23<-predict(ARFM23,newdata=CLECIN)
CLE_OP24<-predict(ARFM24,newdata=CLECIN)
CLE_OP25<-predict(ARFM25,newdata=CLECIN)
CLE_OP26<-predict(ARFM26,newdata=CLECIN)
CLE_OP27<-predict(ARFM27,newdata=CLECIN)
CLE_OP28<-predict(ARFM28,newdata=CLECIN)
CLE_OP29<-predict(ARFM29,newdata=CLECIN)
CLE_OP30<-predict(ARFM30,newdata=CLECIN)
CLE_OP31<-predict(ARFM31,newdata=CLECIN)



#DEN
DEN_P1<-predict(IRF1,newdata=DENKC)
DEN_P2<-predict(IRF2,newdata=DENKC)
DEN_P3<-predict(IRF3,newdata=DENKC)
DEN_P4<-predict(IRF4,newdata=DENKC)
DEN_P5<-predict(IRF5,newdata=DENKC)
DEN_P6<-predict(IRF6,newdata=DENKC)
DEN_P7<-predict(IRF7,newdata=DENKC)
DEN_P8<-predict(IRF8,newdata=DENKC)
DEN_P9<-predict(IRF9,newdata=DENKC)
DEN_P10<-predict(IRF10,newdata=DENKC)
DEN_P11<-predict(IRF11,newdata=DENKC)
DEN_P12<-predict(IRF12,newdata=DENKC)
DEN_P13<-predict(IRF13,newdata=DENKC)
DEN_P14<-predict(IRF14,newdata=DENKC)
DEN_P15<-predict(IRF15,newdata=DENKC)
DEN_P16<-predict(IRF16,newdata=DENKC)
DEN_P17<-predict(IRF17,newdata=DENKC)
DEN_P18<-predict(IRF18,newdata=DENKC)
DEN_P19<-predict(IRF19,newdata=DENKC)
DEN_P20<-predict(IRF20,newdata=DENKC)
DEN_P21<-predict(IRF21,newdata=DENKC)
DEN_OP1<-predict(ARFM1,newdata=DENKC)
DEN_OP2<-predict(ARFM2,newdata=DENKC)
DEN_OP3<-predict(ARFM3,newdata=DENKC)
DEN_OP4<-predict(ARFM4,newdata=DENKC)
DEN_OP5<-predict(ARFM5,newdata=DENKC)
DEN_OP6<-predict(ARFM6,newdata=DENKC)
DEN_OP7<-predict(ARFM7,newdata=DENKC)
DEN_OP8<-predict(ARFM8,newdata=DENKC)
DEN_OP9<-predict(ARFM9,newdata=DENKC)
DEN_OP10<-predict(ARFM10,newdata=DENKC)
DEN_OP11<-predict(ARFM11,newdata=DENKC)
DEN_OP12<-predict(ARFM12,newdata=DENKC)
DEN_OP13<-predict(ARFM13,newdata=DENKC)
DEN_OP14<-predict(ARFM14,newdata=DENKC)
DEN_OP15<-predict(ARFM15,newdata=DENKC)
DEN_OP16<-predict(ARFM16,newdata=DENKC)
DEN_OP17<-predict(ARFM17,newdata=DENKC)
DEN_OP18<-predict(ARFM18,newdata=DENKC)
DEN_OP19<-predict(ARFM19,newdata=DENKC)
DEN_OP20<-predict(ARFM20,newdata=DENKC)
DEN_OP21<-predict(ARFM21,newdata=DENKC)
DEN_OP22<-predict(ARFM22,newdata=DENKC)
DEN_OP23<-predict(ARFM23,newdata=DENKC)
DEN_OP24<-predict(ARFM24,newdata=DENKC)
DEN_OP25<-predict(ARFM25,newdata=DENKC)
DEN_OP26<-predict(ARFM26,newdata=DENKC)
DEN_OP27<-predict(ARFM27,newdata=DENKC)
DEN_OP28<-predict(ARFM28,newdata=DENKC)
DEN_OP29<-predict(ARFM29,newdata=DENKC)
DEN_OP30<-predict(ARFM30,newdata=DENKC)
DEN_OP31<-predict(ARFM31,newdata=DENKC)


#KC
KC_P1<-predict(IRF1,newdata=KCDEN)
KC_P2<-predict(IRF2,newdata=KCDEN)
KC_P3<-predict(IRF3,newdata=KCDEN)
KC_P4<-predict(IRF4,newdata=KCDEN)
KC_P5<-predict(IRF5,newdata=KCDEN)
KC_P6<-predict(IRF6,newdata=KCDEN)
KC_P7<-predict(IRF7,newdata=KCDEN)
KC_P8<-predict(IRF8,newdata=KCDEN)
KC_P9<-predict(IRF9,newdata=KCDEN)
KC_P10<-predict(IRF10,newdata=KCDEN)
KC_P11<-predict(IRF11,newdata=KCDEN)
KC_P12<-predict(IRF12,newdata=KCDEN)
KC_P13<-predict(IRF13,newdata=KCDEN)
KC_P14<-predict(IRF14,newdata=KCDEN)
KC_P15<-predict(IRF15,newdata=KCDEN)
KC_P16<-predict(IRF16,newdata=KCDEN)
KC_P17<-predict(IRF17,newdata=KCDEN)
KC_P18<-predict(IRF18,newdata=KCDEN)
KC_P19<-predict(IRF19,newdata=KCDEN)
KC_P20<-predict(IRF20,newdata=KCDEN)
KC_P21<-predict(IRF21,newdata=KCDEN)
KC_OP1<-predict(ARFM1,newdata=KCDEN)
KC_OP2<-predict(ARFM2,newdata=KCDEN)
KC_OP3<-predict(ARFM3,newdata=KCDEN)
KC_OP4<-predict(ARFM4,newdata=KCDEN)
KC_OP5<-predict(ARFM5,newdata=KCDEN)
KC_OP6<-predict(ARFM6,newdata=KCDEN)
KC_OP7<-predict(ARFM7,newdata=KCDEN)
KC_OP8<-predict(ARFM8,newdata=KCDEN)
KC_OP9<-predict(ARFM9,newdata=KCDEN)
KC_OP10<-predict(ARFM10,newdata=KCDEN)
KC_OP11<-predict(ARFM11,newdata=KCDEN)
KC_OP12<-predict(ARFM12,newdata=KCDEN)
KC_OP13<-predict(ARFM13,newdata=KCDEN)
KC_OP14<-predict(ARFM14,newdata=KCDEN)
KC_OP15<-predict(ARFM15,newdata=KCDEN)
KC_OP16<-predict(ARFM16,newdata=KCDEN)
KC_OP17<-predict(ARFM17,newdata=KCDEN)
KC_OP18<-predict(ARFM18,newdata=KCDEN)
KC_OP19<-predict(ARFM19,newdata=KCDEN)
KC_OP20<-predict(ARFM20,newdata=KCDEN)
KC_OP21<-predict(ARFM21,newdata=KCDEN)
KC_OP22<-predict(ARFM22,newdata=KCDEN)
KC_OP23<-predict(ARFM23,newdata=KCDEN)
KC_OP24<-predict(ARFM24,newdata=KCDEN)
KC_OP25<-predict(ARFM25,newdata=KCDEN)
KC_OP26<-predict(ARFM26,newdata=KCDEN)
KC_OP27<-predict(ARFM27,newdata=KCDEN)
KC_OP28<-predict(ARFM28,newdata=KCDEN)
KC_OP29<-predict(ARFM29,newdata=KCDEN)
KC_OP30<-predict(ARFM30,newdata=KCDEN)
KC_OP31<-predict(ARFM31,newdata=KCDEN)


#DET
DET_P1<-predict(IRF1,newdata=DETMIN)
DET_P2<-predict(IRF2,newdata=DETMIN)
DET_P3<-predict(IRF3,newdata=DETMIN)
DET_P4<-predict(IRF4,newdata=DETMIN)
DET_P5<-predict(IRF5,newdata=DETMIN)
DET_P6<-predict(IRF6,newdata=DETMIN)
DET_P7<-predict(IRF7,newdata=DETMIN)
DET_P8<-predict(IRF8,newdata=DETMIN)
DET_P9<-predict(IRF9,newdata=DETMIN)
DET_P10<-predict(IRF10,newdata=DETMIN)
DET_P11<-predict(IRF11,newdata=DETMIN)
DET_P12<-predict(IRF12,newdata=DETMIN)
DET_P13<-predict(IRF13,newdata=DETMIN)
DET_P14<-predict(IRF14,newdata=DETMIN)
DET_P15<-predict(IRF15,newdata=DETMIN)
DET_P16<-predict(IRF16,newdata=DETMIN)
DET_P17<-predict(IRF17,newdata=DETMIN)
DET_P18<-predict(IRF18,newdata=DETMIN)
DET_P19<-predict(IRF19,newdata=DETMIN)
DET_P20<-predict(IRF20,newdata=DETMIN)
DET_P21<-predict(IRF21,newdata=DETMIN)
DET_OP1<-predict(ARFM1,newdata=DETMIN)
DET_OP2<-predict(ARFM2,newdata=DETMIN)
DET_OP3<-predict(ARFM3,newdata=DETMIN)
DET_OP4<-predict(ARFM4,newdata=DETMIN)
DET_OP5<-predict(ARFM5,newdata=DETMIN)
DET_OP6<-predict(ARFM6,newdata=DETMIN)
DET_OP7<-predict(ARFM7,newdata=DETMIN)
DET_OP8<-predict(ARFM8,newdata=DETMIN)
DET_OP9<-predict(ARFM9,newdata=DETMIN)
DET_OP10<-predict(ARFM10,newdata=DETMIN)
DET_OP11<-predict(ARFM11,newdata=DETMIN)
DET_OP12<-predict(ARFM12,newdata=DETMIN)
DET_OP13<-predict(ARFM13,newdata=DETMIN)
DET_OP14<-predict(ARFM14,newdata=DETMIN)
DET_OP15<-predict(ARFM15,newdata=DETMIN)
DET_OP16<-predict(ARFM16,newdata=DETMIN)
DET_OP17<-predict(ARFM17,newdata=DETMIN)
DET_OP18<-predict(ARFM18,newdata=DETMIN)
DET_OP19<-predict(ARFM19,newdata=DETMIN)
DET_OP20<-predict(ARFM20,newdata=DETMIN)
DET_OP21<-predict(ARFM21,newdata=DETMIN)
DET_OP22<-predict(ARFM22,newdata=DETMIN)
DET_OP23<-predict(ARFM23,newdata=DETMIN)
DET_OP24<-predict(ARFM24,newdata=DETMIN)
DET_OP25<-predict(ARFM25,newdata=DETMIN)
DET_OP26<-predict(ARFM26,newdata=DETMIN)
DET_OP27<-predict(ARFM27,newdata=DETMIN)
DET_OP28<-predict(ARFM28,newdata=DETMIN)
DET_OP29<-predict(ARFM29,newdata=DETMIN)
DET_OP30<-predict(ARFM30,newdata=DETMIN)
DET_OP31<-predict(ARFM31,newdata=DETMIN)

#MIN
MIN_P1<-predict(IRF1,newdata=MINDET)
MIN_P2<-predict(IRF2,newdata=MINDET)
MIN_P3<-predict(IRF3,newdata=MINDET)
MIN_P4<-predict(IRF4,newdata=MINDET)
MIN_P5<-predict(IRF5,newdata=MINDET)
MIN_P6<-predict(IRF6,newdata=MINDET)
MIN_P7<-predict(IRF7,newdata=MINDET)
MIN_P8<-predict(IRF8,newdata=MINDET)
MIN_P9<-predict(IRF9,newdata=MINDET)
MIN_P10<-predict(IRF10,newdata=MINDET)
MIN_P11<-predict(IRF11,newdata=MINDET)
MIN_P12<-predict(IRF12,newdata=MINDET)
MIN_P13<-predict(IRF13,newdata=MINDET)
MIN_P14<-predict(IRF14,newdata=MINDET)
MIN_P15<-predict(IRF15,newdata=MINDET)
MIN_P16<-predict(IRF16,newdata=MINDET)
MIN_P17<-predict(IRF17,newdata=MINDET)
MIN_P18<-predict(IRF18,newdata=MINDET)
MIN_P19<-predict(IRF19,newdata=MINDET)
MIN_P20<-predict(IRF20,newdata=MINDET)
MIN_P21<-predict(IRF21,newdata=MINDET)
MIN_OP1<-predict(ARFM1,newdata=MINDET)
MIN_OP2<-predict(ARFM2,newdata=MINDET)
MIN_OP3<-predict(ARFM3,newdata=MINDET)
MIN_OP4<-predict(ARFM4,newdata=MINDET)
MIN_OP5<-predict(ARFM5,newdata=MINDET)
MIN_OP6<-predict(ARFM6,newdata=MINDET)
MIN_OP7<-predict(ARFM7,newdata=MINDET)
MIN_OP8<-predict(ARFM8,newdata=MINDET)
MIN_OP9<-predict(ARFM9,newdata=MINDET)
MIN_OP10<-predict(ARFM10,newdata=MINDET)
MIN_OP11<-predict(ARFM11,newdata=MINDET)
MIN_OP12<-predict(ARFM12,newdata=MINDET)
MIN_OP13<-predict(ARFM13,newdata=MINDET)
MIN_OP14<-predict(ARFM14,newdata=MINDET)
MIN_OP15<-predict(ARFM15,newdata=MINDET)
MIN_OP16<-predict(ARFM16,newdata=MINDET)
MIN_OP17<-predict(ARFM17,newdata=MINDET)
MIN_OP18<-predict(ARFM18,newdata=MINDET)
MIN_OP19<-predict(ARFM19,newdata=MINDET)
MIN_OP20<-predict(ARFM20,newdata=MINDET)
MIN_OP21<-predict(ARFM21,newdata=MINDET)
MIN_OP22<-predict(ARFM22,newdata=MINDET)
MIN_OP23<-predict(ARFM23,newdata=MINDET)
MIN_OP24<-predict(ARFM24,newdata=MINDET)
MIN_OP25<-predict(ARFM25,newdata=MINDET)
MIN_OP26<-predict(ARFM26,newdata=MINDET)
MIN_OP27<-predict(ARFM27,newdata=MINDET)
MIN_OP28<-predict(ARFM28,newdata=MINDET)
MIN_OP29<-predict(ARFM29,newdata=MINDET)
MIN_OP30<-predict(ARFM30,newdata=MINDET)
MIN_OP31<-predict(ARFM31,newdata=MINDET)


#IND
IND_P1<-predict(IRF1,newdata=INDTEN)
IND_P2<-predict(IRF2,newdata=INDTEN)
IND_P3<-predict(IRF3,newdata=INDTEN)
IND_P4<-predict(IRF4,newdata=INDTEN)
IND_P5<-predict(IRF5,newdata=INDTEN)
IND_P6<-predict(IRF6,newdata=INDTEN)
IND_P7<-predict(IRF7,newdata=INDTEN)
IND_P8<-predict(IRF8,newdata=INDTEN)
IND_P9<-predict(IRF9,newdata=INDTEN)
IND_P10<-predict(IRF10,newdata=INDTEN)
IND_P11<-predict(IRF11,newdata=INDTEN)
IND_P12<-predict(IRF12,newdata=INDTEN)
IND_P13<-predict(IRF13,newdata=INDTEN)
IND_P14<-predict(IRF14,newdata=INDTEN)
IND_P15<-predict(IRF15,newdata=INDTEN)
IND_P16<-predict(IRF16,newdata=INDTEN)
IND_P17<-predict(IRF17,newdata=INDTEN)
IND_P18<-predict(IRF18,newdata=INDTEN)
IND_P19<-predict(IRF19,newdata=INDTEN)
IND_P20<-predict(IRF20,newdata=INDTEN)
IND_P21<-predict(IRF21,newdata=INDTEN)
IND_OP1<-predict(ARFM1,newdata=INDTEN)
IND_OP2<-predict(ARFM2,newdata=INDTEN)
IND_OP3<-predict(ARFM3,newdata=INDTEN)
IND_OP4<-predict(ARFM4,newdata=INDTEN)
IND_OP5<-predict(ARFM5,newdata=INDTEN)
IND_OP6<-predict(ARFM6,newdata=INDTEN)
IND_OP7<-predict(ARFM7,newdata=INDTEN)
IND_OP8<-predict(ARFM8,newdata=INDTEN)
IND_OP9<-predict(ARFM9,newdata=INDTEN)
IND_OP10<-predict(ARFM10,newdata=INDTEN)
IND_OP11<-predict(ARFM11,newdata=INDTEN)
IND_OP12<-predict(ARFM12,newdata=INDTEN)
IND_OP13<-predict(ARFM13,newdata=INDTEN)
IND_OP14<-predict(ARFM14,newdata=INDTEN)
IND_OP15<-predict(ARFM15,newdata=INDTEN)
IND_OP16<-predict(ARFM16,newdata=INDTEN)
IND_OP17<-predict(ARFM17,newdata=INDTEN)
IND_OP18<-predict(ARFM18,newdata=INDTEN)
IND_OP19<-predict(ARFM19,newdata=INDTEN)
IND_OP20<-predict(ARFM20,newdata=INDTEN)
IND_OP21<-predict(ARFM21,newdata=INDTEN)
IND_OP22<-predict(ARFM22,newdata=INDTEN)
IND_OP23<-predict(ARFM23,newdata=INDTEN)
IND_OP24<-predict(ARFM24,newdata=INDTEN)
IND_OP25<-predict(ARFM25,newdata=INDTEN)
IND_OP26<-predict(ARFM26,newdata=INDTEN)
IND_OP27<-predict(ARFM27,newdata=INDTEN)
IND_OP28<-predict(ARFM28,newdata=INDTEN)
IND_OP29<-predict(ARFM29,newdata=INDTEN)
IND_OP30<-predict(ARFM30,newdata=INDTEN)
IND_OP31<-predict(ARFM31,newdata=INDTEN)


#TEN
TEN_P1<-predict(IRF1,newdata=TENIND)
TEN_P2<-predict(IRF2,newdata=TENIND)
TEN_P3<-predict(IRF3,newdata=TENIND)
TEN_P4<-predict(IRF4,newdata=TENIND)
TEN_P5<-predict(IRF5,newdata=TENIND)
TEN_P6<-predict(IRF6,newdata=TENIND)
TEN_P7<-predict(IRF7,newdata=TENIND)
TEN_P8<-predict(IRF8,newdata=TENIND)
TEN_P9<-predict(IRF9,newdata=TENIND)
TEN_P10<-predict(IRF10,newdata=TENIND)
TEN_P11<-predict(IRF11,newdata=TENIND)
TEN_P12<-predict(IRF12,newdata=TENIND)
TEN_P13<-predict(IRF13,newdata=TENIND)
TEN_P14<-predict(IRF14,newdata=TENIND)
TEN_P15<-predict(IRF15,newdata=TENIND)
TEN_P16<-predict(IRF16,newdata=TENIND)
TEN_P17<-predict(IRF17,newdata=TENIND)
TEN_P18<-predict(IRF18,newdata=TENIND)
TEN_P19<-predict(IRF19,newdata=TENIND)
TEN_P20<-predict(IRF20,newdata=TENIND)
TEN_P21<-predict(IRF21,newdata=TENIND)
TEN_OP1<-predict(ARFM1,newdata=TENIND)
TEN_OP2<-predict(ARFM2,newdata=TENIND)
TEN_OP3<-predict(ARFM3,newdata=TENIND)
TEN_OP4<-predict(ARFM4,newdata=TENIND)
TEN_OP5<-predict(ARFM5,newdata=TENIND)
TEN_OP6<-predict(ARFM6,newdata=TENIND)
TEN_OP7<-predict(ARFM7,newdata=TENIND)
TEN_OP8<-predict(ARFM8,newdata=TENIND)
TEN_OP9<-predict(ARFM9,newdata=TENIND)
TEN_OP10<-predict(ARFM10,newdata=TENIND)
TEN_OP11<-predict(ARFM11,newdata=TENIND)
TEN_OP12<-predict(ARFM12,newdata=TENIND)
TEN_OP13<-predict(ARFM13,newdata=TENIND)
TEN_OP14<-predict(ARFM14,newdata=TENIND)
TEN_OP15<-predict(ARFM15,newdata=TENIND)
TEN_OP16<-predict(ARFM16,newdata=TENIND)
TEN_OP17<-predict(ARFM17,newdata=TENIND)
TEN_OP18<-predict(ARFM18,newdata=TENIND)
TEN_OP19<-predict(ARFM19,newdata=TENIND)
TEN_OP20<-predict(ARFM20,newdata=TENIND)
TEN_OP21<-predict(ARFM21,newdata=TENIND)
TEN_OP22<-predict(ARFM22,newdata=TENIND)
TEN_OP23<-predict(ARFM23,newdata=TENIND)
TEN_OP24<-predict(ARFM24,newdata=TENIND)
TEN_OP25<-predict(ARFM25,newdata=TENIND)
TEN_OP26<-predict(ARFM26,newdata=TENIND)
TEN_OP27<-predict(ARFM27,newdata=TENIND)
TEN_OP28<-predict(ARFM28,newdata=TENIND)
TEN_OP29<-predict(ARFM29,newdata=TENIND)
TEN_OP30<-predict(ARFM30,newdata=TENIND)
TEN_OP31<-predict(ARFM31,newdata=TENIND)


#JAX
JAX_P1<-predict(IRF1,newdata=JAXIND)
JAX_P2<-predict(IRF2,newdata=JAXIND)
JAX_P3<-predict(IRF3,newdata=JAXIND)
JAX_P4<-predict(IRF4,newdata=JAXIND)
JAX_P5<-predict(IRF5,newdata=JAXIND)
JAX_P6<-predict(IRF6,newdata=JAXIND)
JAX_P7<-predict(IRF7,newdata=JAXIND)
JAX_P8<-predict(IRF8,newdata=JAXIND)
JAX_P9<-predict(IRF9,newdata=JAXIND)
JAX_P10<-predict(IRF10,newdata=JAXIND)
JAX_P11<-predict(IRF11,newdata=JAXIND)
JAX_P12<-predict(IRF12,newdata=JAXIND)
JAX_P13<-predict(IRF13,newdata=JAXIND)
JAX_P14<-predict(IRF14,newdata=JAXIND)
JAX_P15<-predict(IRF15,newdata=JAXIND)
JAX_P16<-predict(IRF16,newdata=JAXIND)
JAX_P17<-predict(IRF17,newdata=JAXIND)
JAX_P18<-predict(IRF18,newdata=JAXIND)
JAX_P19<-predict(IRF19,newdata=JAXIND)
JAX_P20<-predict(IRF20,newdata=JAXIND)
JAX_P21<-predict(IRF21,newdata=JAXIND)
JAX_OP1<-predict(ARFM1,newdata=JAXIND)
JAX_OP2<-predict(ARFM2,newdata=JAXIND)
JAX_OP3<-predict(ARFM3,newdata=JAXIND)
JAX_OP4<-predict(ARFM4,newdata=JAXIND)
JAX_OP5<-predict(ARFM5,newdata=JAXIND)
JAX_OP6<-predict(ARFM6,newdata=JAXIND)
JAX_OP7<-predict(ARFM7,newdata=JAXIND)
JAX_OP8<-predict(ARFM8,newdata=JAXIND)
JAX_OP9<-predict(ARFM9,newdata=JAXIND)
JAX_OP10<-predict(ARFM10,newdata=JAXIND)
JAX_OP11<-predict(ARFM11,newdata=JAXIND)
JAX_OP12<-predict(ARFM12,newdata=JAXIND)
JAX_OP13<-predict(ARFM13,newdata=JAXIND)
JAX_OP14<-predict(ARFM14,newdata=JAXIND)
JAX_OP15<-predict(ARFM15,newdata=JAXIND)
JAX_OP16<-predict(ARFM16,newdata=JAXIND)
JAX_OP17<-predict(ARFM17,newdata=JAXIND)
JAX_OP18<-predict(ARFM18,newdata=JAXIND)
JAX_OP19<-predict(ARFM19,newdata=JAXIND)
JAX_OP20<-predict(ARFM20,newdata=JAXIND)
JAX_OP21<-predict(ARFM21,newdata=JAXIND)
JAX_OP22<-predict(ARFM22,newdata=JAXIND)
JAX_OP23<-predict(ARFM23,newdata=JAXIND)
JAX_OP24<-predict(ARFM24,newdata=JAXIND)
JAX_OP25<-predict(ARFM25,newdata=JAXIND)
JAX_OP26<-predict(ARFM26,newdata=JAXIND)
JAX_OP27<-predict(ARFM27,newdata=JAXIND)
JAX_OP28<-predict(ARFM28,newdata=JAXIND)
JAX_OP29<-predict(ARFM29,newdata=JAXIND)
JAX_OP30<-predict(ARFM30,newdata=JAXIND)
JAX_OP31<-predict(ARFM31,newdata=JAXIND)


#PHI
PHI_P1<-predict(IRF1,newdata=PHIWAS)
PHI_P2<-predict(IRF2,newdata=PHIWAS)
PHI_P3<-predict(IRF3,newdata=PHIWAS)
PHI_P4<-predict(IRF4,newdata=PHIWAS)
PHI_P5<-predict(IRF5,newdata=PHIWAS)
PHI_P6<-predict(IRF6,newdata=PHIWAS)
PHI_P7<-predict(IRF7,newdata=PHIWAS)
PHI_P8<-predict(IRF8,newdata=PHIWAS)
PHI_P9<-predict(IRF9,newdata=PHIWAS)
PHI_P10<-predict(IRF10,newdata=PHIWAS)
PHI_P11<-predict(IRF11,newdata=PHIWAS)
PHI_P12<-predict(IRF12,newdata=PHIWAS)
PHI_P13<-predict(IRF13,newdata=PHIWAS)
PHI_P14<-predict(IRF14,newdata=PHIWAS)
PHI_P15<-predict(IRF15,newdata=PHIWAS)
PHI_P16<-predict(IRF16,newdata=PHIWAS)
PHI_P17<-predict(IRF17,newdata=PHIWAS)
PHI_P18<-predict(IRF18,newdata=PHIWAS)
PHI_P19<-predict(IRF19,newdata=PHIWAS)
PHI_P20<-predict(IRF20,newdata=PHIWAS)
PHI_P21<-predict(IRF21,newdata=PHIWAS)
PHI_OP1<-predict(ARFM1,newdata=PHIWAS)
PHI_OP2<-predict(ARFM2,newdata=PHIWAS)
PHI_OP3<-predict(ARFM3,newdata=PHIWAS)
PHI_OP4<-predict(ARFM4,newdata=PHIWAS)
PHI_OP5<-predict(ARFM5,newdata=PHIWAS)
PHI_OP6<-predict(ARFM6,newdata=PHIWAS)
PHI_OP7<-predict(ARFM7,newdata=PHIWAS)
PHI_OP8<-predict(ARFM8,newdata=PHIWAS)
PHI_OP9<-predict(ARFM9,newdata=PHIWAS)
PHI_OP10<-predict(ARFM10,newdata=PHIWAS)
PHI_OP11<-predict(ARFM11,newdata=PHIWAS)
PHI_OP12<-predict(ARFM12,newdata=PHIWAS)
PHI_OP13<-predict(ARFM13,newdata=PHIWAS)
PHI_OP14<-predict(ARFM14,newdata=PHIWAS)
PHI_OP15<-predict(ARFM15,newdata=PHIWAS)
PHI_OP16<-predict(ARFM16,newdata=PHIWAS)
PHI_OP17<-predict(ARFM17,newdata=PHIWAS)
PHI_OP18<-predict(ARFM18,newdata=PHIWAS)
PHI_OP19<-predict(ARFM19,newdata=PHIWAS)
PHI_OP20<-predict(ARFM20,newdata=PHIWAS)
PHI_OP21<-predict(ARFM21,newdata=PHIWAS)
PHI_OP22<-predict(ARFM22,newdata=PHIWAS)
PHI_OP23<-predict(ARFM23,newdata=PHIWAS)
PHI_OP24<-predict(ARFM24,newdata=PHIWAS)
PHI_OP25<-predict(ARFM25,newdata=PHIWAS)
PHI_OP26<-predict(ARFM26,newdata=PHIWAS)
PHI_OP27<-predict(ARFM27,newdata=PHIWAS)
PHI_OP28<-predict(ARFM28,newdata=PHIWAS)
PHI_OP29<-predict(ARFM29,newdata=PHIWAS)
PHI_OP30<-predict(ARFM30,newdata=PHIWAS)
PHI_OP31<-predict(ARFM31,newdata=PHIWAS)


#WAS
WAS_P1<-predict(IRF1,newdata=WASPHI)
WAS_P2<-predict(IRF2,newdata=WASPHI)
WAS_P3<-predict(IRF3,newdata=WASPHI)
WAS_P4<-predict(IRF4,newdata=WASPHI)
WAS_P5<-predict(IRF5,newdata=WASPHI)
WAS_P6<-predict(IRF6,newdata=WASPHI)
WAS_P7<-predict(IRF7,newdata=WASPHI)
WAS_P8<-predict(IRF8,newdata=WASPHI)
WAS_P9<-predict(IRF9,newdata=WASPHI)
WAS_P10<-predict(IRF10,newdata=WASPHI)
WAS_P11<-predict(IRF11,newdata=WASPHI)
WAS_P12<-predict(IRF12,newdata=WASPHI)
WAS_P13<-predict(IRF13,newdata=WASPHI)
WAS_P14<-predict(IRF14,newdata=WASPHI)
WAS_P15<-predict(IRF15,newdata=WASPHI)
WAS_P16<-predict(IRF16,newdata=WASPHI)
WAS_P17<-predict(IRF17,newdata=WASPHI)
WAS_P18<-predict(IRF18,newdata=WASPHI)
WAS_P19<-predict(IRF19,newdata=WASPHI)
WAS_P20<-predict(IRF20,newdata=WASPHI)
WAS_P21<-predict(IRF21,newdata=WASPHI)
WAS_OP1<-predict(ARFM1,newdata=WASPHI)
WAS_OP2<-predict(ARFM2,newdata=WASPHI)
WAS_OP3<-predict(ARFM3,newdata=WASPHI)
WAS_OP4<-predict(ARFM4,newdata=WASPHI)
WAS_OP5<-predict(ARFM5,newdata=WASPHI)
WAS_OP6<-predict(ARFM6,newdata=WASPHI)
WAS_OP7<-predict(ARFM7,newdata=WASPHI)
WAS_OP8<-predict(ARFM8,newdata=WASPHI)
WAS_OP9<-predict(ARFM9,newdata=WASPHI)
WAS_OP10<-predict(ARFM10,newdata=WASPHI)
WAS_OP11<-predict(ARFM11,newdata=WASPHI)
WAS_OP12<-predict(ARFM12,newdata=WASPHI)
WAS_OP13<-predict(ARFM13,newdata=WASPHI)
WAS_OP14<-predict(ARFM14,newdata=WASPHI)
WAS_OP15<-predict(ARFM15,newdata=WASPHI)
WAS_OP16<-predict(ARFM16,newdata=WASPHI)
WAS_OP17<-predict(ARFM17,newdata=WASPHI)
WAS_OP18<-predict(ARFM18,newdata=WASPHI)
WAS_OP19<-predict(ARFM19,newdata=WASPHI)
WAS_OP20<-predict(ARFM20,newdata=WASPHI)
WAS_OP21<-predict(ARFM21,newdata=WASPHI)
WAS_OP22<-predict(ARFM22,newdata=WASPHI)
WAS_OP23<-predict(ARFM23,newdata=WASPHI)
WAS_OP24<-predict(ARFM24,newdata=WASPHI)
WAS_OP25<-predict(ARFM25,newdata=WASPHI)
WAS_OP26<-predict(ARFM26,newdata=WASPHI)
WAS_OP27<-predict(ARFM27,newdata=WASPHI)
WAS_OP28<-predict(ARFM28,newdata=WASPHI)
WAS_OP29<-predict(ARFM29,newdata=WASPHI)
WAS_OP30<-predict(ARFM30,newdata=WASPHI)
WAS_OP31<-predict(ARFM31,newdata=WASPHI)



#LAR
LAR_P1<-predict(IRF1,newdata=LAR2)
LAR_P2<-predict(IRF2,newdata=LAR2)
LAR_P3<-predict(IRF3,newdata=LAR2)
LAR_P4<-predict(IRF4,newdata=LAR2)
LAR_P5<-predict(IRF5,newdata=LAR2)
LAR_P6<-predict(IRF6,newdata=LAR2)
LAR_P7<-predict(IRF7,newdata=LAR2)
LAR_P8<-predict(IRF8,newdata=LAR2)
LAR_P9<-predict(IRF9,newdata=LAR2)
LAR_P10<-predict(IRF10,newdata=LAR2)
LAR_P11<-predict(IRF11,newdata=LAR2)
LAR_P12<-predict(IRF12,newdata=LAR2)
LAR_P13<-predict(IRF13,newdata=LAR2)
LAR_P14<-predict(IRF14,newdata=LAR2)
LAR_P15<-predict(IRF15,newdata=LAR2)
LAR_P16<-predict(IRF16,newdata=LAR2)
LAR_P17<-predict(IRF17,newdata=LAR2)
LAR_P18<-predict(IRF18,newdata=LAR2)
LAR_P19<-predict(IRF19,newdata=LAR2)
LAR_P20<-predict(IRF20,newdata=LAR2)
LAR_P21<-predict(IRF21,newdata=LAR2)
LAR_OP1<-predict(ARFM1,newdata=LAR2)
LAR_OP2<-predict(ARFM2,newdata=LAR2)
LAR_OP3<-predict(ARFM3,newdata=LAR2)
LAR_OP4<-predict(ARFM4,newdata=LAR2)
LAR_OP5<-predict(ARFM5,newdata=LAR2)
LAR_OP6<-predict(ARFM6,newdata=LAR2)
LAR_OP7<-predict(ARFM7,newdata=LAR2)
LAR_OP8<-predict(ARFM8,newdata=LAR2)
LAR_OP9<-predict(ARFM9,newdata=LAR2)
LAR_OP10<-predict(ARFM10,newdata=LAR2)
LAR_OP11<-predict(ARFM11,newdata=LAR2)
LAR_OP12<-predict(ARFM12,newdata=LAR2)
LAR_OP13<-predict(ARFM13,newdata=LAR2)
LAR_OP14<-predict(ARFM14,newdata=LAR2)
LAR_OP15<-predict(ARFM15,newdata=LAR2)
LAR_OP16<-predict(ARFM16,newdata=LAR2)
LAR_OP17<-predict(ARFM17,newdata=LAR2)
LAR_OP18<-predict(ARFM18,newdata=LAR2)
LAR_OP19<-predict(ARFM19,newdata=LAR2)
LAR_OP20<-predict(ARFM20,newdata=LAR2)
LAR_OP21<-predict(ARFM21,newdata=LAR2)
LAR_OP22<-predict(ARFM22,newdata=LAR2)
LAR_OP23<-predict(ARFM23,newdata=LAR2)
LAR_OP24<-predict(ARFM24,newdata=LAR2)
LAR_OP25<-predict(ARFM25,newdata=LAR2)
LAR_OP26<-predict(ARFM26,newdata=LAR2)
LAR_OP27<-predict(ARFM27,newdata=LAR2)
LAR_OP28<-predict(ARFM28,newdata=LAR2)
LAR_OP29<-predict(ARFM29,newdata=LAR2)
LAR_OP30<-predict(ARFM30,newdata=LAR2)
LAR_OP31<-predict(ARFM31,newdata=LAR2)


#NE
NE_P1<-predict(IRF1,newdata=NE2)
NE_P2<-predict(IRF2,newdata=NE2)
NE_P3<-predict(IRF3,newdata=NE2)
NE_P4<-predict(IRF4,newdata=NE2)
NE_P5<-predict(IRF5,newdata=NE2)
NE_P6<-predict(IRF6,newdata=NE2)
NE_P7<-predict(IRF7,newdata=NE2)
NE_P8<-predict(IRF8,newdata=NE2)
NE_P9<-predict(IRF9,newdata=NE2)
NE_P10<-predict(IRF10,newdata=NE2)
NE_P11<-predict(IRF11,newdata=NE2)
NE_P12<-predict(IRF12,newdata=NE2)
NE_P13<-predict(IRF13,newdata=NE2)
NE_P14<-predict(IRF14,newdata=NE2)
NE_P15<-predict(IRF15,newdata=NE2)
NE_P16<-predict(IRF16,newdata=NE2)
NE_P17<-predict(IRF17,newdata=NE2)
NE_P18<-predict(IRF18,newdata=NE2)
NE_P19<-predict(IRF19,newdata=NE2)
NE_P20<-predict(IRF20,newdata=NE2)
NE_P21<-predict(IRF21,newdata=NE2)
NE_OP1<-predict(ARFM1,newdata=NE2)
NE_OP2<-predict(ARFM2,newdata=NE2)
NE_OP3<-predict(ARFM3,newdata=NE2)
NE_OP4<-predict(ARFM4,newdata=NE2)
NE_OP5<-predict(ARFM5,newdata=NE2)
NE_OP6<-predict(ARFM6,newdata=NE2)
NE_OP7<-predict(ARFM7,newdata=NE2)
NE_OP8<-predict(ARFM8,newdata=NE2)
NE_OP9<-predict(ARFM9,newdata=NE2)
NE_OP10<-predict(ARFM10,newdata=NE2)
NE_OP11<-predict(ARFM11,newdata=NE2)
NE_OP12<-predict(ARFM12,newdata=NE2)
NE_OP13<-predict(ARFM13,newdata=NE2)
NE_OP14<-predict(ARFM14,newdata=NE2)
NE_OP15<-predict(ARFM15,newdata=NE2)
NE_OP16<-predict(ARFM16,newdata=NE2)
NE_OP17<-predict(ARFM17,newdata=NE2)
NE_OP18<-predict(ARFM18,newdata=NE2)
NE_OP19<-predict(ARFM19,newdata=NE2)
NE_OP20<-predict(ARFM20,newdata=NE2)
NE_OP21<-predict(ARFM21,newdata=NE2)
NE_OP22<-predict(ARFM22,newdata=NE2)
NE_OP23<-predict(ARFM23,newdata=NE2)
NE_OP24<-predict(ARFM24,newdata=NE2)
NE_OP25<-predict(ARFM25,newdata=NE2)
NE_OP26<-predict(ARFM26,newdata=NE2)
NE_OP27<-predict(ARFM27,newdata=NE2)
NE_OP28<-predict(ARFM28,newdata=NE2)
NE_OP29<-predict(ARFM29,newdata=NE2)
NE_OP30<-predict(ARFM30,newdata=NE2)
NE_OP31<-predict(ARFM31,newdata=NE2)



```



```{r}
NEET_P1
NEET_P2
NEET_P3
NEET_P4
NEET_P5
NEET_P6
NEET_P7
NEET_P8
NEET_P9
NEET_P10
NEET_P11
NEET_P12
NEET_P13
NEET_P14
NEET_P15
NEET_P16
NEET_P17
NEET_P18
NEET_P19
NEET_P20
NEET_P21
NEET_OP1
NEET_OP2
NEET_OP3
NEET_OP4
NEET_OP5
NEET_OP6
NEET_OP7
NEET_OP8
NEET_OP9
NEET_OP10
NEET_OP11
NEET_OP12
NEET_OP13
NEET_OP14
NEET_OP15
NEET_OP16
NEET_OP17
NEET_OP18
NEET_OP19
NEET_OP20
NEET_OP21
NEET_OP22
NEET_OP23
NEET_OP24
NEET_OP25
NEET_OP26
NEET_OP27
NEET_OP28
NEET_OP29
NEET_OP30
NEET_OP31




BAL_P1
BAL_P2
BAL_P3
BAL_P4
BAL_P5
BAL_P6
BAL_P7
BAL_P8
BAL_P9
BAL_P10
BAL_P11
BAL_P12
BAL_P13
BAL_P14
BAL_P15
BAL_P16
BAL_P17
BAL_P18
BAL_P19
BAL_P20
BAL_P21
BAL_OP1
BAL_OP2
BAL_OP3
BAL_OP4
BAL_OP5
BAL_OP6
BAL_OP7
BAL_OP8
BAL_OP9
BAL_OP10
BAL_OP11
BAL_OP12
BAL_OP13
BAL_OP14
BAL_OP15
BAL_OP16
BAL_OP17
BAL_OP18
BAL_OP19
BAL_OP20
BAL_OP21
BAL_OP22
BAL_OP23
BAL_OP24
BAL_OP25
BAL_OP26
BAL_OP27
BAL_OP28
BAL_OP29
BAL_OP30
BAL_OP31





PIT_P1
PIT_P2
PIT_P3
PIT_P4
PIT_P5
PIT_P6
PIT_P7
PIT_P8
PIT_P9
PIT_P10
PIT_P11
PIT_P12
PIT_P13
PIT_P14
PIT_P15
PIT_P16
PIT_P17
PIT_P18
PIT_P19
PIT_P20
PIT_P21
PIT_OP1
PIT_OP2
PIT_OP3
PIT_OP4
PIT_OP5
PIT_OP6
PIT_OP7
PIT_OP8
PIT_OP9
PIT_OP10
PIT_OP11
PIT_OP12
PIT_OP13
PIT_OP14
PIT_OP15
PIT_OP16
PIT_OP17
PIT_OP18
PIT_OP19
PIT_OP20
PIT_OP21
PIT_OP22
PIT_OP23
PIT_OP24
PIT_OP25
PIT_OP26
PIT_OP27
PIT_OP28
PIT_OP29
PIT_OP30
PIT_OP31

ARI_P1
ARI_P2
ARI_P3
ARI_P4
ARI_P5
ARI_P6
ARI_P7
ARI_P8
ARI_P9
ARI_P10
ARI_P11
ARI_P12
ARI_P13
ARI_P14
ARI_P15
ARI_P16
ARI_P17
ARI_P18
ARI_P19
ARI_P20
ARI_P21
ARI_OP1
ARI_OP2
ARI_OP3
ARI_OP4
ARI_OP5
ARI_OP6
ARI_OP7
ARI_OP8
ARI_OP9
ARI_OP10
ARI_OP11
ARI_OP12
ARI_OP13
ARI_OP14
ARI_OP15
ARI_OP16
ARI_OP17
ARI_OP18
ARI_OP19
ARI_OP20
ARI_OP21
ARI_OP22
ARI_OP23
ARI_OP24
ARI_OP25
ARI_OP26
ARI_OP27
ARI_OP28
ARI_OP29
ARI_OP30
ARI_OP31


ATL_P1
ATL_P2
ATL_P3
ATL_P4
ATL_P5
ATL_P6
ATL_P7
ATL_P8
ATL_P9
ATL_P10
ATL_P11
ATL_P12
ATL_P13
ATL_P14
ATL_P15
ATL_P16
ATL_P17
ATL_P18
ATL_P19
ATL_P20
ATL_P21
ATL_OP1
ATL_OP2
ATL_OP3
ATL_OP4
ATL_OP5
ATL_OP6
ATL_OP7
ATL_OP8
ATL_OP9
ATL_OP10
ATL_OP11
ATL_OP12
ATL_OP13
ATL_OP14
ATL_OP15
ATL_OP16
ATL_OP17
ATL_OP18
ATL_OP19
ATL_OP20
ATL_OP21
ATL_OP22
ATL_OP23
ATL_OP24
ATL_OP25
ATL_OP26
ATL_OP27
ATL_OP28
ATL_OP29
ATL_OP30
ATL_OP31



CAR_P1
CAR_P2
CAR_P3
CAR_P4
CAR_P5
CAR_P6
CAR_P7
CAR_P8
CAR_P9
CAR_P10
CAR_P11
CAR_P12
CAR_P13
CAR_P14
CAR_P15
CAR_P16
CAR_P17
CAR_P18
CAR_P19
CAR_P20
CAR_P21
CAR_OP1
CAR_OP2
CAR_OP3
CAR_OP4
CAR_OP5
CAR_OP6
CAR_OP7
CAR_OP8
CAR_OP9
CAR_OP10
CAR_OP11
CAR_OP12
CAR_OP13
CAR_OP14
CAR_OP15
CAR_OP16
CAR_OP17
CAR_OP18
CAR_OP19
CAR_OP20
CAR_OP21
CAR_OP22
CAR_OP23
CAR_OP24
CAR_OP25
CAR_OP26
CAR_OP27
CAR_OP28
CAR_OP29
CAR_OP30
CAR_OP31



BUF_P1
BUF_P2
BUF_P3
BUF_P4
BUF_P5
BUF_P6
BUF_P7
BUF_P8
BUF_P9
BUF_P10
BUF_P11
BUF_P12
BUF_P13
BUF_P14
BUF_P15
BUF_P16
BUF_P17
BUF_P18
BUF_P19
BUF_P20
BUF_P21
BUF_OP1
BUF_OP2
BUF_OP3
BUF_OP4
BUF_OP5
BUF_OP6
BUF_OP7
BUF_OP8
BUF_OP9
BUF_OP10
BUF_OP11
BUF_OP12
BUF_OP13
BUF_OP14
BUF_OP15
BUF_OP16
BUF_OP17
BUF_OP18
BUF_OP19
BUF_OP20
BUF_OP21
BUF_OP22
BUF_OP23
BUF_OP24
BUF_OP25
BUF_OP26
BUF_OP27
BUF_OP28
BUF_OP29
BUF_OP30
BUF_OP31



NYJ_P1
NYJ_P2
NYJ_P3
NYJ_P4
NYJ_P5
NYJ_P6
NYJ_P7
NYJ_P8
NYJ_P9
NYJ_P10
NYJ_P11
NYJ_P12
NYJ_P13
NYJ_P14
NYJ_P15
NYJ_P16
NYJ_P17
NYJ_P18
NYJ_P19
NYJ_P20
NYJ_P21
NYJ_OP1
NYJ_OP2
NYJ_OP3
NYJ_OP4
NYJ_OP5
NYJ_OP6
NYJ_OP7
NYJ_OP8
NYJ_OP9
NYJ_OP10
NYJ_OP11
NYJ_OP12
NYJ_OP13
NYJ_OP14
NYJ_OP15
NYJ_OP16
NYJ_OP17
NYJ_OP18
NYJ_OP19
NYJ_OP20
NYJ_OP21
NYJ_OP22
NYJ_OP23
NYJ_OP24
NYJ_OP25
NYJ_OP26
NYJ_OP27
NYJ_OP28
NYJ_OP29
NYJ_OP30
NYJ_OP31



CHI_P1
CHI_P2
CHI_P3
CHI_P4
CHI_P5
CHI_P6
CHI_P7
CHI_P8
CHI_P9
CHI_P10
CHI_P11
CHI_P12
CHI_P13
CHI_P14
CHI_P15
CHI_P16
CHI_P17
CHI_P18
CHI_P19
CHI_P20
CHI_P21
CHI_OP1
CHI_OP2
CHI_OP3
CHI_OP4
CHI_OP5
CHI_OP6
CHI_OP7
CHI_OP8
CHI_OP9
CHI_OP10
CHI_OP11
CHI_OP12
CHI_OP13
CHI_OP14
CHI_OP15
CHI_OP16
CHI_OP17
CHI_OP18
CHI_OP19
CHI_OP20
CHI_OP21
CHI_OP22
CHI_OP23
CHI_OP24
CHI_OP25
CHI_OP26
CHI_OP27
CHI_OP28
CHI_OP29
CHI_OP30
CHI_OP31



GB_P1
GB_P2
GB_P3
GB_P4
GB_P5
GB_P6
GB_P7
GB_P8
GB_P9
GB_P10
GB_P11
GB_P12
GB_P13
GB_P14
GB_P15
GB_P16
GB_P17
GB_P18
GB_P19
GB_P20
GB_P21
GB_OP1
GB_OP2
GB_OP3
GB_OP4
GB_OP5
GB_OP6
GB_OP7
GB_OP8
GB_OP9
GB_OP10
GB_OP11
GB_OP12
GB_OP13
GB_OP14
GB_OP15
GB_OP16
GB_OP17
GB_OP18
GB_OP19
GB_OP20
GB_OP21
GB_OP22
GB_OP23
GB_OP24
GB_OP25
GB_OP26
GB_OP27
GB_OP28
GB_OP29
GB_OP30
GB_OP31



CIN_P1
CIN_P2
CIN_P3
CIN_P4
CIN_P5
CIN_P6
CIN_P7
CIN_P8
CIN_P9
CIN_P10
CIN_P11
CIN_P12
CIN_P13
CIN_P14
CIN_P15
CIN_P16
CIN_P17
CIN_P18
CIN_P19
CIN_P20
CIN_P21
CIN_OP1
CIN_OP2
CIN_OP3
CIN_OP4
CIN_OP5
CIN_OP6
CIN_OP7
CIN_OP8
CIN_OP9
CIN_OP10
CIN_OP11
CIN_OP12
CIN_OP13
CIN_OP14
CIN_OP15
CIN_OP16
CIN_OP17
CIN_OP18
CIN_OP19
CIN_OP20
CIN_OP21
CIN_OP22
CIN_OP23
CIN_OP24
CIN_OP25
CIN_OP26
CIN_OP27
CIN_OP28
CIN_OP29
CIN_OP30
CIN_OP31



CLE_P1
CLE_P2
CLE_P3
CLE_P4
CLE_P5
CLE_P6
CLE_P7
CLE_P8
CLE_P9
CLE_P10
CLE_P11
CLE_P12
CLE_P13
CLE_P14
CLE_P15
CLE_P16
CLE_P17
CLE_P18
CLE_P19
CLE_P20
CLE_P21
CLE_OP1
CLE_OP2
CLE_OP3
CLE_OP4
CLE_OP5
CLE_OP6
CLE_OP7
CLE_OP8
CLE_OP9
CLE_OP10
CLE_OP11
CLE_OP12
CLE_OP13
CLE_OP14
CLE_OP15
CLE_OP16
CLE_OP17
CLE_OP18
CLE_OP19
CLE_OP20
CLE_OP21
CLE_OP22
CLE_OP23
CLE_OP24
CLE_OP25
CLE_OP26
CLE_OP27
CLE_OP28
CLE_OP29
CLE_OP30
CLE_OP31



DEN_P1
DEN_P2
DEN_P3
DEN_P4
DEN_P5
DEN_P6
DEN_P7
DEN_P8
DEN_P9
DEN_P10
DEN_P11
DEN_P12
DEN_P13
DEN_P14
DEN_P15
DEN_P16
DEN_P17
DEN_P18
DEN_P19
DEN_P20
DEN_P21
DEN_OP1
DEN_OP2
DEN_OP3
DEN_OP4
DEN_OP5
DEN_OP6
DEN_OP7
DEN_OP8
DEN_OP9
DEN_OP10
DEN_OP11
DEN_OP12
DEN_OP13
DEN_OP14
DEN_OP15
DEN_OP16
DEN_OP17
DEN_OP18
DEN_OP19
DEN_OP20
DEN_OP21
DEN_OP22
DEN_OP23
DEN_OP24
DEN_OP25
DEN_OP26
DEN_OP27
DEN_OP28
DEN_OP29
DEN_OP30
DEN_OP31



KC_P1
KC_P2
KC_P3
KC_P4
KC_P5
KC_P6
KC_P7
KC_P8
KC_P9
KC_P10
KC_P11
KC_P12
KC_P13
KC_P14
KC_P15
KC_P16
KC_P17
KC_P18
KC_P19
KC_P20
KC_P21
KC_OP1
KC_OP2
KC_OP3
KC_OP4
KC_OP5
KC_OP6
KC_OP7
KC_OP8
KC_OP9
KC_OP10
KC_OP11
KC_OP12
KC_OP13
KC_OP14
KC_OP15
KC_OP16
KC_OP17
KC_OP18
KC_OP19
KC_OP20
KC_OP21
KC_OP22
KC_OP23
KC_OP24
KC_OP25
KC_OP26
KC_OP27
KC_OP28
KC_OP29
KC_OP30
KC_OP31



DET_P1
DET_P2
DET_P3
DET_P4
DET_P5
DET_P6
DET_P7
DET_P8
DET_P9
DET_P10
DET_P11
DET_P12
DET_P13
DET_P14
DET_P15
DET_P16
DET_P17
DET_P18
DET_P19
DET_P20
DET_P21
DET_OP1
DET_OP2
DET_OP3
DET_OP4
DET_OP5
DET_OP6
DET_OP7
DET_OP8
DET_OP9
DET_OP10
DET_OP11
DET_OP12
DET_OP13
DET_OP14
DET_OP15
DET_OP16
DET_OP17
DET_OP18
DET_OP19
DET_OP20
DET_OP21
DET_OP22
DET_OP23
DET_OP24
DET_OP25
DET_OP26
DET_OP27
DET_OP28
DET_OP29
DET_OP30
DET_OP31



MIN_P1
MIN_P2
MIN_P3
MIN_P4
MIN_P5
MIN_P6
MIN_P7
MIN_P8
MIN_P9
MIN_P10
MIN_P11
MIN_P12
MIN_P13
MIN_P14
MIN_P15
MIN_P16
MIN_P17
MIN_P18
MIN_P19
MIN_P20
MIN_P21
MIN_OP1
MIN_OP2
MIN_OP3
MIN_OP4
MIN_OP5
MIN_OP6
MIN_OP7
MIN_OP8
MIN_OP9
MIN_OP10
MIN_OP11
MIN_OP12
MIN_OP13
MIN_OP14
MIN_OP15
MIN_OP16
MIN_OP17
MIN_OP18
MIN_OP19
MIN_OP20
MIN_OP21
MIN_OP22
MIN_OP23
MIN_OP24
MIN_OP25
MIN_OP26
MIN_OP27
MIN_OP28
MIN_OP29
MIN_OP30
MIN_OP31



IND_P1
IND_P2
IND_P3
IND_P4
IND_P5
IND_P6
IND_P7
IND_P8
IND_P9
IND_P10
IND_P11
IND_P12
IND_P13
IND_P14
IND_P15
IND_P16
IND_P17
IND_P18
IND_P19
IND_P20
IND_P21
IND_OP1
IND_OP2
IND_OP3
IND_OP4
IND_OP5
IND_OP6
IND_OP7
IND_OP8
IND_OP9
IND_OP10
IND_OP11
IND_OP12
IND_OP13
IND_OP14
IND_OP15
IND_OP16
IND_OP17
IND_OP18
IND_OP19
IND_OP20
IND_OP21
IND_OP22
IND_OP23
IND_OP24
IND_OP25
IND_OP26
IND_OP27
IND_OP28
IND_OP29
IND_OP30
IND_OP31



TEN_P1
TEN_P2
TEN_P3
TEN_P4
TEN_P5
TEN_P6
TEN_P7
TEN_P8
TEN_P9
TEN_P10
TEN_P11
TEN_P12
TEN_P13
TEN_P14
TEN_P15
TEN_P16
TEN_P17
TEN_P18
TEN_P19
TEN_P20
TEN_P21
TEN_OP1
TEN_OP2
TEN_OP3
TEN_OP4
TEN_OP5
TEN_OP6
TEN_OP7
TEN_OP8
TEN_OP9
TEN_OP10
TEN_OP11
TEN_OP12
TEN_OP13
TEN_OP14
TEN_OP15
TEN_OP16
TEN_OP17
TEN_OP18
TEN_OP19
TEN_OP20
TEN_OP21
TEN_OP22
TEN_OP23
TEN_OP24
TEN_OP25
TEN_OP26
TEN_OP27
TEN_OP28
TEN_OP29
TEN_OP30
TEN_OP31



JAX_P1
JAX_P2
JAX_P3
JAX_P4
JAX_P5
JAX_P6
JAX_P7
JAX_P8
JAX_P9
JAX_P10
JAX_P11
JAX_P12
JAX_P13
JAX_P14
JAX_P15
JAX_P16
JAX_P17
JAX_P18
JAX_P19
JAX_P20
JAX_P21
JAX_OP1
JAX_OP2
JAX_OP3
JAX_OP4
JAX_OP5
JAX_OP6
JAX_OP7
JAX_OP8
JAX_OP9
JAX_OP10
JAX_OP11
JAX_OP12
JAX_OP13
JAX_OP14
JAX_OP15
JAX_OP16
JAX_OP17
JAX_OP18
JAX_OP19
JAX_OP20
JAX_OP21
JAX_OP22
JAX_OP23
JAX_OP24
JAX_OP25
JAX_OP26
JAX_OP27
JAX_OP28
JAX_OP29
JAX_OP30
JAX_OP31



PHI_P1
PHI_P2
PHI_P3
PHI_P4
PHI_P5
PHI_P6
PHI_P7
PHI_P8
PHI_P9
PHI_P10
PHI_P11
PHI_P12
PHI_P13
PHI_P14
PHI_P15
PHI_P16
PHI_P17
PHI_P18
PHI_P19
PHI_P20
PHI_P21
PHI_OP1
PHI_OP2
PHI_OP3
PHI_OP4
PHI_OP5
PHI_OP6
PHI_OP7
PHI_OP8
PHI_OP9
PHI_OP10
PHI_OP11
PHI_OP12
PHI_OP13
PHI_OP14
PHI_OP15
PHI_OP16
PHI_OP17
PHI_OP18
PHI_OP19
PHI_OP20
PHI_OP21
PHI_OP22
PHI_OP23
PHI_OP24
PHI_OP25
PHI_OP26
PHI_OP27
PHI_OP28
PHI_OP29
PHI_OP30
PHI_OP31



WAS_P1
WAS_P2
WAS_P3
WAS_P4
WAS_P5
WAS_P6
WAS_P7
WAS_P8
WAS_P9
WAS_P10
WAS_P11
WAS_P12
WAS_P13
WAS_P14
WAS_P15
WAS_P16
WAS_P17
WAS_P18
WAS_P19
WAS_P20
WAS_P21
WAS_OP1
WAS_OP2
WAS_OP3
WAS_OP4
WAS_OP5
WAS_OP6
WAS_OP7
WAS_OP8
WAS_OP9
WAS_OP10
WAS_OP11
WAS_OP12
WAS_OP13
WAS_OP14
WAS_OP15
WAS_OP16
WAS_OP17
WAS_OP18
WAS_OP19
WAS_OP20
WAS_OP21
WAS_OP22
WAS_OP23
WAS_OP24
WAS_OP25
WAS_OP26
WAS_OP27
WAS_OP28
WAS_OP29
WAS_OP30
WAS_OP31




LAR_P1
LAR_P2
LAR_P3
LAR_P4
LAR_P5
LAR_P6
LAR_P7
LAR_P8
LAR_P9
LAR_P10
LAR_P11
LAR_P12
LAR_P13
LAR_P14
LAR_P15
LAR_P16
LAR_P17
LAR_P18
LAR_P19
LAR_P20
LAR_P21
LAR_OP1
LAR_OP2
LAR_OP3
LAR_OP4
LAR_OP5
LAR_OP6
LAR_OP7
LAR_OP8
LAR_OP9
LAR_OP10
LAR_OP11
LAR_OP12
LAR_OP13
LAR_OP14
LAR_OP15
LAR_OP16
LAR_OP17
LAR_OP18
LAR_OP19
LAR_OP20
LAR_OP21
LAR_OP22
LAR_OP23
LAR_OP24
LAR_OP25
LAR_OP26
LAR_OP27
LAR_OP28
LAR_OP29
LAR_OP30
LAR_OP31

NE_P1
NE_P2
NE_P3
NE_P4
NE_P5
NE_P6
NE_P7
NE_P8
NE_P9
NE_P10
NE_P11
NE_P12
NE_P13
NE_P14
NE_P15
NE_P16
NE_P17
NE_P18
NE_P19
NE_P20
NE_P21
NE_OP1
NE_OP2
NE_OP3
NE_OP4
NE_OP5
NE_OP6
NE_OP7
NE_OP8
NE_OP9
NE_OP10
NE_OP11
NE_OP12
NE_OP13
NE_OP14
NE_OP15
NE_OP16
NE_OP17
NE_OP18
NE_OP19
NE_OP20
NE_OP21
NE_OP22
NE_OP23
NE_OP24
NE_OP25
NE_OP26
NE_OP27
NE_OP28
NE_OP29
NE_OP30
NE_OP31

```



